-- FISCAL-03: aplicar explicitamente por banco tenant após backup.
ALTER TABLE clientes
 ADD COLUMN IF NOT EXISTS person_type VARCHAR(7) NOT NULL DEFAULT 'PF',
 ADD COLUMN IF NOT EXISTS foreign_id VARCHAR(50) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS state_registration_indicator CHAR(1) NOT NULL DEFAULT '9',
 ADD COLUMN IF NOT EXISTS rg VARCHAR(30) NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS country_code VARCHAR(4) NOT NULL DEFAULT '1058',
 ADD COLUMN IF NOT EXISTS country_name VARCHAR(60) NOT NULL DEFAULT 'BRASIL',
 ADD COLUMN IF NOT EXISTS observations TEXT NULL,
 ADD COLUMN IF NOT EXISTS role_customer TINYINT(1) NOT NULL DEFAULT 1,
 ADD COLUMN IF NOT EXISTS role_supplier TINYINT(1) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS role_seller TINYINT(1) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS role_carrier TINYINT(1) NOT NULL DEFAULT 0;
