-- FISCAL-01: aplicar explicitamente em cada banco mini_erp_tenant_* após backup.
-- Idempotente e aditiva; não deve ser executada no banco MAIN mini_erp.
CREATE TABLE IF NOT EXISTS establishments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT UNSIGNED NOT NULL,
    tax_id VARCHAR(14) NOT NULL,
    legal_name VARCHAR(150) NOT NULL,
    trade_name VARCHAR(150) NOT NULL DEFAULT '',
    state_registration VARCHAR(30) NOT NULL,
    st_registration VARCHAR(30) NOT NULL DEFAULT '',
    municipal_registration VARCHAR(30) NOT NULL DEFAULT '',
    cnae VARCHAR(7) NOT NULL DEFAULT '',
    tax_regime_code CHAR(1) NOT NULL,
    street VARCHAR(150) NOT NULL,
    number VARCHAR(20) NOT NULL,
    complement VARCHAR(100) NOT NULL DEFAULT '',
    district VARCHAR(100) NOT NULL,
    city_ibge_code CHAR(7) NOT NULL,
    city_name VARCHAR(100) NOT NULL,
    state CHAR(2) NOT NULL,
    postal_code CHAR(8) NOT NULL,
    country_code VARCHAR(4) NOT NULL DEFAULT '1058',
    country_name VARCHAR(60) NOT NULL DEFAULT 'BRASIL',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    email VARCHAR(150) NOT NULL DEFAULT '',
    establishment_type VARCHAR(20) NOT NULL DEFAULT 'MATRIZ',
    is_primary TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(10) NOT NULL DEFAULT 'ativo',
    fiscal_readiness VARCHAR(20) NOT NULL DEFAULT 'INCOMPLETE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_establishments_tenant_tax_id (tenant_id, tax_id),
    KEY idx_establishments_primary (tenant_id, is_primary)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
