<?php
declare(strict_types=1);
namespace MiniErp\Fiscal;
use DateTimeImmutable; use InvalidArgumentException;
final readonly class FiscalTaxRule {
 public function __construct(public ?int $id,public int $tenantId,public string $code,public int $version,public int $priority,public DateTimeImmutable $validFrom,public ?DateTimeImmutable $validTo,public string $sourceDocument,public string $sourceVersion,public string $sourceDate,public array $conditions,public string $cfop,public array $icms=[],public array $ipi=[],public array $pis=[],public array $cofins=[],public array $ibsCbs=[],public array $selectiveTax=[],public string $status='ACTIVE',public string $fixtureKind='PRODUCTION'){if($tenantId<1||$version<1||$code===''||$sourceDocument===''||$sourceVersion===''||$sourceDate==='')throw new InvalidArgumentException('Regra fiscal sem identidade, versão ou fonte.');if(!preg_match('/^\d{4}$/',$cfop))throw new InvalidArgumentException('Regra exige CFOP final com 4 dígitos.');if($validTo&&$validTo<$validFrom)throw new InvalidArgumentException('Vigência inválida.');$allowed=['crt','origin_state','destination_state','recipient_type','ie_indicator','country_code','ncm','cest','product_origin','product_id','tax_benefit_code','direction','model','purpose','final_consumer','icms_contributor','presence','cfop_hint'];foreach(array_keys($conditions) as $key)if(!in_array($key,$allowed,true))throw new InvalidArgumentException("Condição não suportada: $key");}
 public function isEffective(DateTimeImmutable $date):bool{return $this->status==='ACTIVE'&&$date>=$this->validFrom&&($this->validTo===null||$date<=$this->validTo);}
 public function matches(FiscalTaxContext $context):bool{if($context->tenantId!==$this->tenantId||!$this->isEffective($context->operationDate))return false;$values=$context->values();foreach($this->conditions as $key=>$expected){$actual=$values[$key]??null;if(is_array($expected)){if(!in_array($actual,$expected,true))return false;}elseif($actual!==$expected)return false;}return true;}
 public function specificity():int{return count($this->conditions);}
}
