<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Platform\TabularImportReader;
use MiniErp\Platform\TenantCatalogImportService;
function ci(bool$condition,string$message):void{if(!$condition)throw new RuntimeException($message);}
$file=tempnam(sys_get_temp_dir(),'catalog-import-');file_put_contents($file,"\xEF\xBB\xBFsep=;\r\nCODIGO;DESCRICAO;CODIGO_NCM;PRECO\r\n001;Produto teste;12345678;10,50\r\n002;Outro;87654321;20\r\n");
try{$table=(new TabularImportReader())->read($file,'produtos.csv');ci($table['headers']===['codigo','descricao','codigo_ncm','preco'],'header normalization');ci(count($table['rows'])===2&&$table['rows'][0]['data']['codigo']==='001','csv rows and leading zero');}finally{unlink($file);}
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('CREATE TABLE produtos(codigo TEXT PRIMARY KEY);CREATE TABLE product_taxes(product_id INTEGER PRIMARY KEY,icms_cst TEXT);CREATE TABLE clientes(cpf_cnpj TEXT);CREATE TABLE fornecedores(cpf_cnpj TEXT);CREATE TABLE cfops(codigo TEXT PRIMARY KEY);CREATE TABLE tax_rule_versions(tenant_id INTEGER,rule_code TEXT,rule_version INTEGER);CREATE TABLE establishment_icms_defaults(tenant_id INTEGER,uf TEXT,valid_from TEXT);INSERT INTO produtos VALUES("001")');
$service=new TenantCatalogImportService();$result=$service->simulate($pdo,7,'produtos',$table['rows'],'produtos.csv');ci($result['summary']['valid']===2,'two valid products');ci($result['summary']['update']===1&&$result['summary']['create']===1,'create/update classification');ci($result['valid_rows'][0]['preco']==='10.500000','Brazilian decimal');
$legacy=$service->simulate($pdo,7,'produtos',[['line'=>2,'data'=>['codigo'=>'3','preco_compra'=>'90,00','preco_venda'=>'329,90','sit'=>'060','unidade'=>'UN','estoque'=>'7,00','descricao'=>'REGUA DE MEDICAO','ativo'=>'N','pis_st'=>'01','pis_perc'=>'0,65','cofins_st'=>'01','cofins_perc'=>'3,00','codigo_ncm'=>'90261029','csosn'=>'500','csosn_nfce'=>'500','cean'=>'357098','unidade_trib'=>'UN','quantidade_trib'=>'1','estoque_minimo'=>'2,00']]],'legado.xlsx');$product=$legacy['valid_rows'][0];ci($product['cost_price']==='90.000000'&&$product['preco']==='329.900000','legacy prices');ci($product['ncm']==='90261029'&&$product['status']==='inativo','legacy fiscal and active flag');ci($product['_product_taxes']['icms']==='500'&&$product['_product_taxes']['pis']==='01','legacy product taxes');ci($product['_product_taxes']['icms_cst']==='060'&&$product['_product_taxes']['icms_consumer_cst']==='500','product ICMS profiles');ci($product['_product_taxes']['pis_output_rate']==='0.650000'&&$product['_product_taxes']['cofins_output_rate']==='3.000000','product tax rates');
$bad=$service->simulate($pdo,7,'cfops',[['line'=>2,'data'=>['codigo'=>'5102','descricao'=>'Venda']],['line'=>3,'data'=>['codigo'=>'5102','descricao'=>'Duplicado']],['line'=>4,'data'=>['codigo'=>'999','descricao'=>'Inválido']]],'cfops.csv');ci($bad['summary']['valid']===1&&$bad['summary']['errors']===2,'duplicates and invalid CFOP blocked');
$icms=$service->simulate($pdo,7,'icms_uf',[['line'=>2,'data'=>['uf_destino'=>'AC','aliquota_pf'=>'7','aliquota_cf'=>'7','aliquota_interna'=>'17','aliquota_interestadual'=>'7','valid_from'=>'2026-09-02']],['line'=>3,'data'=>['uf_destino'=>'EX','aliquota'=>'7','valid_from'=>'2026-09-02']]],'ICMS_UF.xlsx');ci($icms['summary']['valid']===1&&$icms['summary']['errors']===1,'ICMS UF and exterior validation');ci($icms['valid_rows'][0]['juridica_rate']==='7.000000'&&$icms['valid_rows'][0]['internal_rate']==='17.000000','ICMS UF rates');
echo "CatalogImportSimulation OK\n";
