<?php
declare(strict_types=1);
require_once __DIR__ . '/../src/Contracts/EstablishmentRepositoryContract.php'; require_once __DIR__ . '/../src/Services/EstablishmentData.php'; require_once __DIR__ . '/../src/Services/EstablishmentService.php'; require_once __DIR__ . '/../src/Services/FiscalReadiness.php';
use MiniErp\Contracts\EstablishmentRepositoryContract; use MiniErp\Services\EstablishmentData; use MiniErp\Services\EstablishmentService; use MiniErp\Services\FiscalReadiness;
function fiscalAssert(bool $ok, string $message): void { if (!$ok) { fwrite(STDERR, "ASSERTION FAILED: {$message}\n"); exit(1); } }
final class MemoryEstablishments implements EstablishmentRepositoryContract { public array $rows=[]; public function schemaAvailable(): bool{return true;} public function findPrimaryForTenant(int $id):?array{return $this->rows[$id]??null;} public function savePrimaryForTenant(int $id,array $data):array{$data['tenant_id']=$id;return $this->rows[$id]=$data;} }
$payload=['tax_id'=>'12.ABC.345/01DE-35','legal_name'=>'Empresa Fiscal Ltda','trade_name'=>'Fiscal','state_registration'=>'123','st_registration'=>'456','municipal_registration'=>'789','cnae'=>'4711302','tax_regime_code'=>'1','street'=>'Rua Um','number'=>'10','complement'=>'Sala 2','district'=>'Centro','city_ibge_code'=>'3550308','city_name'=>'São Paulo','state'=>'sp','postal_code'=>'01001000','country_code'=>'1058','country_name'=>'Brasil','phone'=>'1133334444','email'=>'fiscal@example.test','status'=>'ativo'];
$repository=new MemoryEstablishments(); $service=new EstablishmentService($repository); $saved=$service->save(21,new EstablishmentData($payload));
foreach (['tax_id','legal_name','trade_name','state_registration','st_registration','municipal_registration','cnae','tax_regime_code','street','number','complement','district','city_ibge_code','city_name','state','postal_code','country_code','country_name','phone','email','establishment_type','is_primary','status','fiscal_readiness'] as $field) fiscalAssert(array_key_exists($field,$saved),"round-trip field {$field}");
fiscalAssert($saved['tax_id']==='12ABC34501DE35','alphanumeric CNPJ preserved and normalized'); fiscalAssert($saved['tenant_id']===21,'canonical tenant identity'); fiscalAssert($service->find(22)===null,'tenant B cannot read tenant A');
$updated=$service->save(21,new EstablishmentData(array_merge($payload,['trade_name'=>'Fiscal Atualizada','phone'=>'11999999999']))); fiscalAssert($updated['trade_name']==='Fiscal Atualizada','update round-trip'); fiscalAssert($service->find(21)['phone']==='11999999999','updated value can be read');
$readiness=(new FiscalReadiness())->evaluate($saved); fiscalAssert($readiness['status']==='INCOMPLETE','readiness stays independent and incomplete'); fiscalAssert($readiness['items']['certificate_a1']===false,'certificate remains pending');
try { new EstablishmentData(array_merge($payload,['tax_id'=>'123'])); fiscalAssert(false,'invalid tax id rejected'); } catch (InvalidArgumentException) {}
echo "EstablishmentService OK\n";
