<?php
declare(strict_types=1);
if(getenv('RUN_FISCAL_REAL_READ_TESTS')!=='1'){echo "FiscalDanfePreviewRealOrderReadOnly SKIPPED\n";exit;}
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Fiscal\TaxRuleResolver;
use MiniErp\Repositories\{FiscalOperationRepository,MariaDbTaxRuleRepository};
use MiniErp\Services\{CreateInternalFiscalDocumentService,FiscalDanfePreviewService};
$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$tenant=14;$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname=mini_erp_tenant_14;charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$cache=sys_get_temp_dir().'/minierp-preview-real-read-'.bin2hex(random_bytes(4));$count=fn(string$table)=>(int)$pdo->query("SELECT COUNT(*) FROM {$table} WHERE tenant_id={$tenant}")->fetchColumn();$series=fn()=>(int)$pdo->query("SELECT COALESCE(MAX(next_number),0) FROM fiscal_series WHERE tenant_id={$tenant}")->fetchColumn();$keys=fn()=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id={$tenant} AND access_key IS NOT NULL")->fetchColumn();$before=['documents'=>$count('fiscal_documents'),'reservations'=>$count('fiscal_number_reservations'),'series'=>$series(),'keys'=>$keys()];$code='';$message='';$result=[];$operations=new FiscalOperationRepository($pdo,$tenant);$taxResolver=new TaxRuleResolver(new MariaDbTaxRuleRepository($pdo,$tenant));
try{$service=new FiscalDanfePreviewService($pdo,$operations,$taxResolver,$cache);for($i=0;$i<10;$i++)$result=$service->render(5);$code='READY';}catch(Throwable$e){$code=property_exists($e,'errorCode')?(string)$e->errorCode:get_class($e);$message=$e->getMessage();}
$after=['documents'=>$count('fiscal_documents'),'reservations'=>$count('fiscal_number_reservations'),'series'=>$series(),'keys'=>$keys()];if($before!==$after)throw new RuntimeException('real read preview mutated fiscal state');if($code!=='READY')throw new RuntimeException('real order preview failed: '.$code.' '.$message);if(($result['model']??'')!=='55'||($result['renderer']??'')!=='NFePHP\\DA\\NFe\\Danfe'||($result['page_format']??'')!=='A4')throw new RuntimeException('real order renderer/model');if(($result['tax_status']??'')!=='PENDING'||!in_array('FISCAL_RULE_NOT_FOUND',array_column($result['warnings']??[],'code'),true))throw new RuntimeException('missing tax warning');foreach(['Notebook Gamer Nitro +5','TRIBUTAÇÃO PENDENTE','SEM VALOR FISCAL','NÃO TRANSMITIDA À SEFAZ','<mod>55</mod>']as$needle)if(!str_contains((string)$result['xml'],$needle))throw new RuntimeException('real preview missing '.$needle);if(!str_starts_with((string)$result['bytes'],'%PDF')||strlen((string)$result['bytes'])<10000)throw new RuntimeException('real preview PDF invalid');
$pdo->beginTransaction();try{$real=(new CreateInternalFiscalDocumentService($operations,$taxResolver))->create(5,hash('sha256','PROMPT-040-REAL-PREFLIGHT-ROLLBACK'),999);if(($real['status']??'')!=='FISCAL_PENDING')throw new RuntimeException('real note must remain blocked');$realBlockers=$real['pending']??[];}finally{$pdo->rollBack();}$afterReal=['documents'=>$count('fiscal_documents'),'reservations'=>$count('fiscal_number_reservations'),'series'=>$series(),'keys'=>$keys()];if($before!==$afterReal)throw new RuntimeException('rolled-back real preflight changed fiscal state');
if(is_dir($cache)){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($cache,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$file)$file->isDir()?rmdir($file->getPathname()):unlink($file->getPathname());rmdir($cache);}
echo json_encode(['tenant'=>$tenant,'order'=>5,'preview'=>$code,'model'=>$result['model'],'renderer'=>$result['renderer'],'product'=>'Notebook Gamer Nitro +5','tax_engine'=>$result['tax_status'],'warnings'=>array_column($result['warnings'],'code'),'pdf_bytes'=>strlen($result['bytes']),'a4'=>$result['page_format']==='A4'?'PASS':'FAIL','previews'=>10,'documents_before'=>$before['documents'],'documents_after'=>$afterReal['documents'],'next_number_before'=>$before['series'],'next_number_after'=>$afterReal['series'],'reservations_before'=>$before['reservations'],'reservations_after'=>$afterReal['reservations'],'official_keys'=>$afterReal['keys']-$before['keys'],'certificate_used'=>false,'real_note'=>'BLOCKED','real_blockers'=>$realBlockers,'sefaz_calls'=>0],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),PHP_EOL;
