<?php
declare(strict_types=1);
if(getenv('RUN_FISCAL_MARIADB_TESTS')!=='1'){echo "FiscalSaleMariaDbIntegration SKIPPED\n";exit;}
foreach(['Contracts/TaxRuleRepositoryContract.php','Fiscal/FiscalTaxContext.php','Fiscal/FiscalTaxRule.php','Fiscal/FiscalTaxResolution.php','Fiscal/TaxRuleResolver.php','Repositories/MariaDbTaxRuleRepository.php','Repositories/FiscalOperationRepository.php','Services/CreateInternalFiscalDocumentService.php'] as $f)require_once __DIR__.'/../src/'.$f;
use MiniErp\Fiscal\{FiscalTaxRule,TaxRuleResolver};use MiniErp\Repositories\{MariaDbTaxRuleRepository,FiscalOperationRepository};use MiniErp\Services\CreateInternalFiscalDocumentService;
$c=require __DIR__.'/../config.php';$d=$c['db'];$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname=mini_erp_tenant_14;charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->beginTransaction();
try{
 $ops=new FiscalOperationRepository($pdo,14);$h=['tipo'=>'saida','establishment_id'=>5,'cliente_id'=>1,'data_venda'=>'2026-08-21','operation_nature'=>'TEST_ONLY','fiscal_model'=>'55','purpose'=>'NORMAL','presence_indicator'=>'1','condicao_pagamento'=>'avista','payment_method'=>'01','desconto_valor'=>'1','frete'=>'2'];$order=$ops->createOrder($h,[['produto_id'=>7,'quantidade'=>'2','preco_unitario'=>'10','desconto'=>'1']],999);if($ops->order($order)['grand_total']!=='21.00')throw new RuntimeException('totals');
 $m1=$ops->createMirror($order,999);$pdo->prepare('UPDATE produtos SET nome=? WHERE id=7')->execute(['ALTERADO APOS ESPELHO']);$mirror=json_decode($pdo->query("SELECT operation_snapshot_json FROM fiscal_mirrors WHERE id=$m1")->fetchColumn(),true,512,JSON_THROW_ON_ERROR);if(!str_contains($mirror['items'][0]['nome'],'Notebook Gamer'))throw new RuntimeException('mirror immutable');if($ops->createMirror($order,999)===$m1)throw new RuntimeException('mirror versions');
 $taxRepo=new MariaDbTaxRuleRepository($pdo,14);$svc=new CreateInternalFiscalDocumentService($ops,new TaxRuleResolver($taxRepo));if($svc->create($order,hash('sha256','pending'),999)['status']!=='FISCAL_PENDING')throw new RuntimeException('pending');$taxRepo->addVersion(new FiscalTaxRule(null,14,'TEST_ONLY_FISCAL06',1,10,new DateTimeImmutable('2026-01-01'),null,'TEST_ONLY','v1','2026-01-01',[],'5102',['cst'=>'TEST'],['cst'=>'TEST'],['cst'=>'TEST'],['cst'=>'TEST'],['cst'=>'TEST','cClassTrib'=>'TEST'],['cst'=>'TEST'],'ACTIVE','TEST_ONLY'));
 $svc=new CreateInternalFiscalDocumentService($ops,new TaxRuleResolver($taxRepo));$ready=$svc->create($order,hash('sha256','ready'),999);if($ready['status']!=='FISCAL_READY')throw new RuntimeException('ready');if((int)$svc->create($order,hash('sha256','ready'),999)['id']!==(int)$ready['id'])throw new RuntimeException('idempotency');$snap=$pdo->query('SELECT product_snapshot_json,tax_resolution_json FROM fiscal_document_items WHERE fiscal_document_id='.(int)$ready['id'])->fetch();$product=json_decode($snap['product_snapshot_json'],true,512,JSON_THROW_ON_ERROR);$tax=json_decode($snap['tax_resolution_json'],true,512,JSON_THROW_ON_ERROR);if(!str_contains($product['nome'],'ALTERADO')||$tax['cfop']!=='5102')throw new RuntimeException('snapshots');echo "FiscalSaleMariaDbIntegration OK (rollback)\n";
}finally{if($pdo->inTransaction())$pdo->rollBack();}
