<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Fiscal\{FiscalDocumentDTO,FiscalNfeXmlBuilder,FiscalXmlSigner,NfeAccessKeyGenerator,OfficialNfeXsdValidator};
function xb(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function infNFeC14n(string $xml):string{$dom=new DOMDocument();$dom->loadXML($xml);$node=$dom->getElementsByTagName('infNFe')->item(0);if(!$node)throw new RuntimeException('infNFe ausente');return (string)$node->C14N();}
$issuer=['tax_id'=>'12ABC34501DE35','legal_name'=>'EMITENTE TEST ONLY','trade_name'=>'TESTE','state_registration'=>'110042490114','tax_regime_code'=>3,'street'=>'RUA TESTE','number'=>'100','district'=>'CENTRO','city_ibge_code'=>'3550308','city_name'=>'SAO PAULO','state'=>'SP','postal_code'=>'01001000'];
$recipient=['cpf_cnpj'=>'12345678901','nome'=>'DESTINATARIO TEST ONLY','state_registration_indicator'=>9,'street'=>'RUA DESTINO','number'=>'20','district'=>'CENTRO','city_ibge_code'=>'3550308','city_name'=>'SAO PAULO','state'=>'SP','postal_code'=>'01001000'];
$tax=['cfop'=>'5102','icms'=>['cst'=>'00','modBC'=>3,'base'=>'10.00','rate'=>'18.0000','amount'=>'1.80'],'pis'=>['cst'=>'01','base'=>'10.00','rate'=>'1.6500','amount'=>'0.17'],'cofins'=>['cst'=>'01','base'=>'10.00','rate'=>'7.6000','amount'=>'0.76'],'ipi'=>['cst'=>'99','legal_code'=>'999','base'=>'10.00','rate'=>'0.0000','amount'=>'0.00'],'ibsCbs'=>[],'selectiveTax'=>[]];
$item=['product'=>['codigo'=>'T1','nome'=>'PRODUTO TEST ONLY','ncm'=>'84713012','unidade'=>'UN','taxable_unit'=>'UN','merchandise_origin'=>'0'],'tax'=>$tax,'values'=>['quantity_commercial'=>'1.0000','quantity_taxable'=>'1.0000','unit_value_commercial'=>'10.0000','unit_value_taxable'=>'10.0000','gross_total'=>'10.00','net_total'=>'10.00']];
$password=bin2hex(random_bytes(18));$openssl=['config'=>'C:/xampp/php/extras/openssl/openssl.cnf','private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA,'digest_alg'=>'sha256'];$private=openssl_pkey_new($openssl);$csr=openssl_csr_new(['commonName'=>'MINIERP FISCAL TEST ONLY','organizationName'=>'TEST ONLY - NO LEGAL VALUE','countryName'=>'BR'],$private,$openssl);$certificate=openssl_csr_sign($csr,null,$private,2,$openssl);openssl_pkcs12_export($certificate,$pfx,$private,$password);xb(is_string($pfx)&&$pfx!=='','PFX TEST_ONLY em memória');
$keygen=new NfeAccessKeyGenerator();$validator=new OfficialNfeXsdValidator(__DIR__.'/../resources/fiscal/xsd/nfe/010e-v1.02/NFe');$builder=new FiscalNfeXmlBuilder();$signer=new FiscalXmlSigner();
try{$signer->signTestOnly('<NFe/>',$pfx,$password.'wrong');throw new RuntimeException('senha incorreta aceita');}catch(Throwable $e){xb($e->getMessage()!=='senha incorreta aceita','senha incorreta rejeitada');}
foreach(['55','65'] as $model){$key=$keygen->generate('35','2608',$issuer['tax_id'],$model,1,1,1,'87654321');$dto=new FiscalDocumentDTO(1,14,$model,$issuer,$recipient,[$item],['model'=>$model,'operation_nature'=>'VENDA','operation_type'=>'EXIT','products'=>'10.00','grand'=>'10.00','purpose'=>1,'final_consumer'=>1,'presence_indicator'=>1],['method'=>'01','amount'=>'10.00'],['freight_mode'=>9]);$xml=$builder->build($dto,['access_key'=>$key,'uf_code'=>'35','numeric_code'=>'87654321','series'=>1,'number'=>1,'issued_at'=>'2026-08-21T12:00:00-03:00','environment'=>2,'emission_type'=>1,'destination_scope'=>1]);xb(str_contains($xml,"<mod>{$model}</mod>"),"modelo {$model}");xb(str_contains($xml,'12ABC34501DE35'),'CNPJ alfa');xb(str_contains($xml,'<IPI>')&&str_contains($xml,'<PIS>')&&str_contains($xml,'<COFINS>'),'tributos clássicos');xb(!str_contains($xml,'Signature')&&!str_contains($xml,'protNFe'),'não assinado/protocolo');try{$validator->validate($xml);throw new RuntimeException('XSD aceitou NFe sem assinatura');}catch(RuntimeException $e){xb(str_contains($e->getMessage(),'Signature'),'XSD oficial deve exigir assinatura');}$signed=$signer->signTestOnly($xml,$pfx,$password);xb($signed['status']==='SIGNED_TEST_ONLY'&&$signed['reference']==='#NFe'.$key,'assinatura e Reference');xb($signed['unsigned_sha256']!==$signed['signed_sha256'],'hashes distintos');$validator->validate($signed['xml']);xb($signer->verify($signed['xml']),'XMLDSig local');$tampered=str_replace('10.00','11.00',$signed['xml']);xb(!$signer->verify($tampered),'alteração invalida assinatura');}
xb(infNFeC14n($xml)===infNFeC14n($signed['xml']),'assinatura preserva conteudo fiscal');
foreach(['Signature','SignedInfo','DigestValue','SignatureValue','X509Certificate'] as $tag)xb(str_contains($signed['xml'],"<{$tag}"),"XMLDSig {$tag}");
$rtcTax=$tax;
$rtcTax['ibsCbs']=['CST'=>'000','cClassTrib'=>'000001','vBC'=>'10.00','gIBSUF_pIBSUF'=>'0.1000','gIBSUF_vIBSUF'=>'0.01','gIBSMun_pIBSMun'=>'0.0000','gIBSMun_vIBSMun'=>'0.00','gCBS_pCBS'=>'0.9000','gCBS_vCBS'=>'0.09'];
$rtcTax['selectiveTax']=['CSTIS'=>'000','cClassTribIS'=>'000001','vBCIS'=>'10.00','pIS'=>'1.0000','vIS'=>'0.10'];
$rtcItem=$item;$rtcItem['tax']=$rtcTax;
$rtcKey=$keygen->generate('35','2608',$issuer['tax_id'],'55',1,2,1,'87654322');
$rtcDto=new FiscalDocumentDTO(2,14,'55',$issuer,$recipient,[$rtcItem],['model'=>'55','operation_nature'=>'CENARIO ESTRUTURAL RTC TEST ONLY','operation_type'=>'EXIT','products'=>'10.00','grand'=>'10.00','purpose'=>1,'final_consumer'=>1,'presence_indicator'=>1],['method'=>'01','amount'=>'10.00'],['freight_mode'=>9]);
$rtcXml=$builder->build($rtcDto,['access_key'=>$rtcKey,'uf_code'=>'35','numeric_code'=>'87654322','series'=>1,'number'=>2,'issued_at'=>'2026-08-21T12:00:00-03:00','environment'=>2,'emission_type'=>1]);
xb(str_contains($rtcXml,'<IBSCBS>')&&str_contains($rtcXml,'<cClassTrib>000001</cClassTrib>'),'RTC IBS/CBS estrutural');
xb(str_contains($rtcXml,'<IS>')&&str_contains($rtcXml,'<cClassTribIS>000001</cClassTribIS>'),'IS estrutural');
$rtcSigned=$signer->signTestOnly($rtcXml,$pfx,$password);$validator->validate($rtcSigned['xml']);xb($signer->verify($rtcSigned['xml']),'RTC/IS assinado e valido');
$snIssuer=$issuer;$snIssuer['tax_regime_code']=1;$snTax=$tax;$snTax['icms']=['csosn'=>'102'];$snTax['ipi']=[];$snTax['pis']=['cst'=>'49','base'=>'0.00','rate'=>'0.00','amount'=>'0.00'];$snTax['cofins']=['cst'=>'49','base'=>'0.00','rate'=>'0.00','amount'=>'0.00'];$snItem=$item;$snItem['tax']=$snTax;$snKey=$keygen->generate('35','2608',$snIssuer['tax_id'],'55',37,1,1,'87654323');$snDto=new FiscalDocumentDTO(3,14,'55',$snIssuer,$recipient,[$snItem],['model'=>'55','operation_nature'=>'VENDA TEST ONLY','operation_type'=>'EXIT','products'=>'10.00','grand'=>'10.00','purpose'=>1,'final_consumer'=>1,'presence_indicator'=>1],['method'=>'01','amount'=>'10.00'],['freight_mode'=>9]);$snXml=$builder->build($snDto,['access_key'=>$snKey,'uf_code'=>'35','numeric_code'=>'87654323','series'=>37,'number'=>1,'issued_at'=>'2026-08-24T12:00:00-03:00','environment'=>2,'emission_type'=>1]);xb(str_contains($snXml,'<ICMSSN102>')&&str_contains($snXml,'<CSOSN>102</CSOSN>'),'CRT 1 usa tag ICMSSN');$snSigned=$signer->signTestOnly($snXml,$pfx,$password);$validator->validate($snSigned['xml']);xb($signer->verify($snSigned['xml']),'XML Simples Nacional assinado e XSD valido');
unset($pfx,$private,$csr,$certificate,$password);
echo "FiscalXmlBuilder OK\n";
