<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Services\{FiscalDanfeException,FiscalPreviewModelResolver};
function route_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
$resolver=new FiscalPreviewModelResolver();route_assert($resolver->resolve('55','65')==='55','operation precedence');route_assert($resolver->resolve('65','55')==='65','explicit 65');route_assert($resolver->resolve(null,'55')==='55','company 55 fallback');route_assert($resolver->resolve('', '65')==='65','company 65 fallback');route_assert($resolver->resolveWithSource('65','55')===['model'=>'65','source'=>'EXPLICIT'],'explicit source');route_assert($resolver->resolveWithSource(null,'55')===['model'=>'55','source'=>'ESTABLISHMENT_DEFAULT'],'default source');$blocked=false;try{$resolver->resolve('99','55');}catch(FiscalDanfeException$e){$blocked=$e->errorCode==='FISCAL_DOCUMENT_MODEL_UNSUPPORTED';}route_assert($blocked,'unsupported model fail closed');$notSelected=false;try{$resolver->resolve(null,null);}catch(FiscalDanfeException$e){$notSelected=$e->errorCode==='MODEL_NOT_SELECTED';}route_assert($notSelected,'missing model fail closed');
$js=(string)file_get_contents(__DIR__.'/../public/assets/app.js');foreach(["window.open('', '_blank')",'previewWindow.location.href = previewLink.href','window.location.href = previewLink.href']as$needle)route_assert(str_contains($js,$needle),'mobile preview contract '.$needle);route_assert(!str_contains($js,'previewWindow.location.replace'),'preview popup navigation contract');
$page=(string)file_get_contents(__DIR__.'/../public/index.php');foreach(["data.set('fiscal_action',fiscalAction)",'result.order_id','else location.href=result.danfe_url']as$needle)route_assert(str_contains($page,$needle),'order preview submit contract '.$needle);
$service=(string)file_get_contents(__DIR__.'/../src/Services/FiscalDanfePreviewService.php');route_assert(str_contains($service,".'|'.\$model.'|'.\$modelSource.'|'")&&str_contains($service,"'model-'.\$model"),'model/source must scope cache');
echo "FiscalPreviewRoutingAndNewTab PASS\n";
