<?php
declare(strict_types=1);
require_once __DIR__.'/../src/Services/EstablishmentData.php'; require_once __DIR__.'/../src/Services/EstablishmentFiscalCompleteness.php';
use MiniErp\Services\EstablishmentData; use MiniErp\Services\EstablishmentFiscalCompleteness;
function emitterAssert(bool $ok,string $message):void{if(!$ok){fwrite(STDERR,"ASSERTION FAILED: {$message}\n");exit(1);}}
$root=dirname(__DIR__);$form=file_get_contents($root.'/public/includes/establishment_form.php');$data=file_get_contents($root.'/src/Services/EstablishmentData.php');$repo=file_get_contents($root.'/src/Repositories/TenantEstablishmentRepository.php');$migration=file_get_contents($root.'/migrations/20260821_create_tenant_establishments.sql');$coverage=file_get_contents($root.'/docs/fiscal/FISCAL-01D-establishment-field-completion.md');$rules=file_get_contents($root.'/docs/fiscal/FISCAL-FIELD-IMPLEMENTATION-RULES.md');
$map=['emit/CNPJ'=>'tax_id','emit/xNome'=>'legal_name','emit/xFant'=>'trade_name','emit/IE'=>'state_registration','emit/IEST'=>'st_registration','emit/IM'=>'municipal_registration','emit/CNAE'=>'cnae','emit/CRT'=>'tax_regime_code','enderEmit/xLgr'=>'street','enderEmit/nro'=>'number','enderEmit/xCpl'=>'complement','enderEmit/xBairro'=>'district','enderEmit/cMun'=>'city_ibge_code','enderEmit/xMun'=>'city_name','enderEmit/UF'=>'state','enderEmit/CEP'=>'postal_code','enderEmit/cPais'=>'country_code','enderEmit/xPais'=>'country_name','enderEmit/fone'=>'phone'];
foreach($map as $tag=>$field){emitterAssert(str_contains($form,'name="'.$field.'"'),"UI {$tag}");emitterAssert(str_contains($data,"'{$field}'"),"backend {$tag}");emitterAssert(str_contains($migration,$field),"column {$tag}");emitterAssert(str_contains($coverage,'`'.$tag.'`')&&str_contains($coverage,'`'.$field.'`'),"traceability {$tag}");}
$input=['tax_id'=>'12ABC34501DE35','legal_name'=>'Empresa','trade_name'=>'Fantasia','state_registration'=>'123','st_registration'=>'','municipal_registration'=>'','cnae'=>'','tax_regime_code'=>'2','street'=>'Rua','number'=>'10','complement'=>'','district'=>'Centro','city_ibge_code'=>'4106902','city_name'=>'Curitiba','state'=>'PR','postal_code'=>'80000000','country_code'=>'1058','country_name'=>'BRASIL','phone'=>'41999999999','email'=>'','status'=>'ativo'];$row=(new EstablishmentData($input))->toArray();$complete=(new EstablishmentFiscalCompleteness())->evaluate($row);emitterAssert($complete['emit_ready'],'emit origins complete');emitterAssert($complete['contact_complete'],'contact complete');foreach(['certificate_ready','nfe_configuration_ready','nfce_configuration_ready','homologation_ready','production_ready'] as $future)emitterAssert($complete[$future]===false,"{$future} false");
emitterAssert(str_contains($repo,'WHERE tenant_id = :tenant_id'),'tenant scoped repository');emitterAssert(!str_contains($form,'name="access_key"')&&!str_contains($form,'name="certificate"')&&!str_contains($form,'name="protocol"'),'derived/secret/SEFAZ values are not inputs');foreach(['USER_INPUT','CONFIGURATION','DERIVED','CALCULATED','TAX_RULE','SECRET','SEFAZ_RESPONSE','Snapshot'] as $rule)emitterAssert(str_contains($rules,$rule),"rules cover {$rule}");echo "Fiscal01DEmitterCoverage OK\n";
