<?php
declare(strict_types=1);
if(getenv('RUN_FISCAL_MARIADB_TESTS')!=='1'){echo"FiscalDanfeLogoMatrixTest SKIPPED\n";exit;}
require __DIR__.'/../vendor/autoload.php';require __DIR__.'/helpers/FiscalPipelineTestSupport.php';
use MiniErp\Fiscal\{FiscalArtifactStorage,FiscalDanfeLogoStorage};use MiniErp\Repositories\FiscalArtifactRepository;use MiniErp\Services\{FiscalDanfeException,FiscalDanfeService};
[$server,$pdo,$database]=fiscal_test_db();$tenant=997027;$est=997127;$root=sys_get_temp_dir().'/minierp-logo-matrix-'.bin2hex(random_bytes(4));
function removeLogoTree(string$dir):void{if(!is_dir($dir))return;foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}rmdir($dir);}
try{$cert=fiscal_seed_certificate($pdo,$tenant,$est,'12345678000195','LOGO MATRIX');$seed=fiscal_seed_document($pdo,$tenant,$est);$artifactRoot=$root.'/artifacts';$pipeline=fiscal_pipeline_service($pdo,$tenant,null,$artifactRoot,$cert['storage_root'].'/certs',$cert['storage_root'].'/secrets');$pipeline->prepare($tenant,(int)$seed['document_id'],999);$repo=new FiscalArtifactRepository($pdo,$tenant);$artifact=$repo->findByDocumentVersion((int)$seed['document_id'],1,'NFE');fiscal_assert($artifact!==null,'artifact missing');$logos=$root.'/logos';mkdir($logos.'/tenant-'.$tenant,0700,true);$reference='tenant-'.$tenant.'/logo.png';$logo=$logos.'/'.$reference;$image=imagecreatetruecolor(180,60);$white=imagecolorallocate($image,255,255,255);$blue=imagecolorallocate($image,20,70,160);imagefill($image,0,0,$white);imagefilledrectangle($image,8,8,172,52,$blue);imagepng($image,$logo);imagedestroy($image);$service=new FiscalDanfeService($repo,new FiscalArtifactStorage($artifactRoot),$root.'/cache','1.1.6',new FiscalDanfeLogoStorage($logos));
 $without=$service->render((int)$artifact['id']);fiscal_assert(str_starts_with($without['bytes'],'%PDF')&&$without['page_format']==='A4'&&!$without['logo_applied'],'without logo');
 $with=$service->render((int)$artifact['id'],$reference);fiscal_assert(str_starts_with($with['bytes'],'%PDF')&&$with['page_format']==='A4'&&$with['logo_applied']&&$with['cache']==='MISS','valid logo/application/cache miss');
 $withHit=$service->render((int)$artifact['id'],$reference);fiscal_assert($withHit['cache']==='HIT','valid logo cache hit');
 unlink($logo);$invalid=$service->render((int)$artifact['id'],$reference);fiscal_assert(str_starts_with($invalid['bytes'],'%PDF')&&!$invalid['logo_applied']&&$invalid['logo_warning']==='DANFE_LOGO_UNAVAILABLE','invalid logo safe fallback');
 foreach(['../outside.png','C:\\outside.png','tenant-'.($tenant+1).'/logo.png']as$bad){try{$service->render((int)$artifact['id'],$bad);throw new RuntimeException('unsafe logo accepted');}catch(FiscalDanfeException$e){fiscal_assert(in_array($e->errorCode,['DANFE_LOGO_REFERENCE_BLOCKED','DANFE_LOGO_CROSS_TENANT_BLOCKED'],true),'wrong logo block');}}
 fiscal_assert($without['logo_checksum']==='none'&&$with['logo_checksum']!=='none','logo checksum/cache key');echo"FiscalDanfeLogoMatrixTest OK without/valid/invalid/traversal/cross-tenant/cache/A4\n";
}finally{fiscal_drop_database($server,$database);removeLogoTree($root);}
