<?php
declare(strict_types=1);
if(getenv('RUN_FISCAL_MARIADB_TESTS')!=='1'){echo"FiscalDocumentDoubleSubmitHttpTest SKIPPED\n";exit;}
require __DIR__.'/../vendor/autoload.php';require __DIR__.'/helpers/FiscalPipelineTestSupport.php';
use MiniErp\Fiscal\{A1CertificateInspector,FiscalMasterKey,LocalEncryptedSecretStorage,PrivateCertificateStorage};use MiniErp\Repositories\FiscalConfigurationRepository;use MiniErp\Services\EstablishmentFiscalConfigurationService;
$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$server=new PDO("mysql:host={$d['host']};port={$d['port']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$tenant=927027;$tenantDb='mini_erp_tenant_'.$tenant;$control='mini_erp_http_test_'.bin2hex(random_bytes(4));$root=sys_get_temp_dir().'/minierp-http-'.bin2hex(random_bytes(4));$sessions=$root.'/sessions';mkdir($sessions,0700,true);$servers=[];
function httpRemoveTree(string$dir):void{if(!is_dir($dir))return;foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}rmdir($dir);}
function httpSqlFile(PDO$pdo,string$file):void{$sql=(string)file_get_contents($file);foreach(array_filter(array_map('trim',preg_split('/;\s*(?:\R|$)/',$sql)?:[]))as$stmt)$pdo->exec($stmt);}
function httpWait(int$port):void{for($i=0;$i<80;$i++){if($s=@fsockopen('127.0.0.1',$port,$e,$m,.1)){fclose($s);return;}usleep(100000);}throw new RuntimeException('HTTP server did not start');}
try{
 $server->exec("CREATE DATABASE `$tenantDb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$server->exec("CREATE DATABASE `$control` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname=$tenantDb;charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);httpSqlFile($pdo,__DIR__.'/../database/tenant-template/v1/schema.sql');httpSqlFile($pdo,__DIR__.'/../migrations/20260822_complete_fiscal_artifact_runtime.sql');httpSqlFile($pdo,__DIR__.'/../migrations/20260824_create_fiscal_document_events.sql');
 $ctl=new PDO("mysql:host={$d['host']};port={$d['port']};dbname=$control;charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$ctl->exec('CREATE TABLE tenants(id INT PRIMARY KEY,db_name VARCHAR(190) NOT NULL)');$ctl->prepare('INSERT INTO tenants(id,db_name)VALUES(?,?)')->execute([$tenant,$tenantDb]);
 $pdo->prepare("INSERT INTO establishments(id,tenant_id,tax_id,legal_name,trade_name,state_registration,tax_regime_code,street,number,district,city_ibge_code,city_name,state,postal_code,fiscal_readiness)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([1,$tenant,'12345678000195','Emitente HTTP TEST','Emitente HTTP TEST','123456789','1','Rua A','100','Centro','3550308','Sao Paulo','SP','01001000','READY']);
 $pdo->exec("INSERT INTO clientes(id,nome,email,cpf_cnpj,inscricao_estadual,logradouro,numero,bairro,municipio,codigo_municipal,codigo_ibge,uf,cep,person_type,pessoa_fisica,state_registration_indicator,country_code,country_name)VALUES(1,'Cliente HTTP TEST','test@example.invalid','98765432000110','987654321','Rua B','20','Centro','Sao Paulo','3550308','3550308','SP','01002000','PJ','nao','1','1058','BRASIL')");
 $pdo->exec("INSERT INTO produtos(id,nome,codigo,ncm,merchandise_origin,unidade,taxable_unit,conversion_factor,gtin,gtin_tributable,cfop_padrao,preco,status)VALUES(1,'Produto HTTP TEST','HTTP-001','01012100','0','UN','UN',1,'SEM GTIN','SEM GTIN','5102',100,'ativo')");
 $pdo->prepare("INSERT INTO tax_rule_versions(tenant_id,rule_code,rule_version,priority,valid_from,source_document,source_version,source_date,conditions_json,cfop,icms_json,ipi_json,pis_json,cofins_json,ibs_cbs_json,selective_tax_json,status,fixture_kind)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$tenant,'HTTP-TEST',1,100,'2020-01-01','TEST_ONLY','1','2020-01-01','{}','5102','{"cst":"00","modBC":"3","base":"100.00","rate":"18.00","amount":"18.00"}','{}','{"cst":"01","base":"100.00","rate":"0.65","amount":"0.65"}','{"cst":"01","base":"100.00","rate":"3.00","amount":"3.00"}','{}','{}','ACTIVE','TEST_ONLY']);
 $pdo->exec("INSERT INTO fiscal_orders(id,tenant_id,operation_type,establishment_id,person_id,internal_code,operation_date,commercial_status,fiscal_status,operation_nature,fiscal_model,purpose,final_consumer,presence_indicator,payment_condition,payment_method,freight_mode,products_total,grand_total,created_by)VALUES(1,$tenant,'EXIT',1,1,'HTTP-ORDER','2026-08-24','SAVED','NOT_CREATED','Venda','55','NORMAL',1,'1','A VISTA','01','9',100,100,999)");$pdo->exec("INSERT INTO fiscal_order_items(order_id,product_id,quantity,unit_price,gross_total,net_total)VALUES(1,1,1,100,100,100)");$pdo->exec("INSERT INTO fiscal_series(tenant_id,establishment_id,model,series,next_number,environment,emission_type,process_version,active)VALUES($tenant,1,'55',1,1,2,1,'HTTP_TEST',1)");
 putenv('APP_ENV=testing');putenv('DB_NAME='.$control);putenv('FISCAL_TEST_STORAGE_ROOT='.$root);putenv('FISCAL_SECRET_KEY='.str_repeat('H',32));$configRepo=new FiscalConfigurationRepository($pdo,$tenant);$certService=new EstablishmentFiscalConfigurationService($configRepo,new A1CertificateInspector(),new PrivateCertificateStorage($root.'/storage/fiscal/certificates'),new LocalEncryptedSecretStorage($root.'/storage/fiscal/secrets',FiscalMasterKey::resolve($root)),$tenant);$opt=['config'=>'C:/xampp/php/extras/openssl/openssl.cnf','private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA,'digest_alg'=>'sha256'];$key=openssl_pkey_new($opt);$csr=openssl_csr_new(['commonName'=>'HTTP TEST','organizationName'=>'TEST ONLY','serialNumber'=>'12345678000195','countryName'=>'BR'],$key,$opt);$x509=openssl_csr_sign($csr,null,$key,2,$opt);$pass=bin2hex(random_bytes(12));$pfx='';openssl_pkcs12_export($x509,$pfx,$key,$pass);$certService->upload(1,'http-test.pfx',$pfx,$pass,'12345678000195',999);
 $sid='HTTP'.bin2hex(random_bytes(12));$csrf=bin2hex(random_bytes(32));$sessionScript='session_id('.var_export($sid,true).');session_start();$_SESSION["erp_tenant_id"]='.$tenant.';$_SESSION["erp_user_id"]=999;$_SESSION["erp_fiscal_csrf"]='.var_export($csrf,true).';session_write_close();';$makeSession=proc_open(['C:/xampp/php/php.exe','-d','session.save_path='.$sessions,'-r',$sessionScript],[1=>['pipe','w'],2=>['pipe','w']],$sp);proc_close($makeSession);
 $ports=[19270+random_int(0,100),19400+random_int(0,100)];foreach($ports as$port){$proc=proc_open(['C:/xampp/php/php.exe','-d','session.save_path='.$sessions,'-S','127.0.0.1:'.$port,'-t',__DIR__.'/../public'],[1=>['pipe','w'],2=>['pipe','w']],$pipes,__DIR__.'/..');$servers[]=[$proc,$pipes];httpWait($port);}
 $token=hash('sha256','HTTP-DOUBLE-SUBMIT-027');$fields=['fiscal_action=note','idempotency_key='.$token,'order_id=1','tipo=saida','cliente_id=1','data_venda=2026-08-24','operation_nature=Venda','fiscal_model=55','purpose=NORMAL','final_consumer=1','presence_indicator=1','condicao_pagamento=A+VISTA','payment_method=01','freight_mode=9','itens[0][produto_id]=1','itens[0][quantidade]=1','itens[0][preco_unitario]=100'];$cookie='PHPSESSID='.$sid.'; erp_fiscal_csrf='.$csrf;$clients=[];foreach($ports as$port){$cmd=['curl.exe','-sS','-w',"\n%{http_code}",'-X','POST','-H','Sec-Fetch-Site: same-origin','-b',$cookie];foreach($fields as$field){$cmd[]='--data';$cmd[]=$field;}$cmd[]='http://127.0.0.1:'.$port.'/fiscal_action.php';$clients[]=[$p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes),$pipes];}
 $responses=[];foreach($clients as[$proc,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($proc);fiscal_assert($exit===0,'curl failed '.$err);$parts=preg_split('/\R/',$out);$status=(int)array_pop($parts);$json=json_decode(implode("\n",$parts),true);fiscal_assert(in_array($status,[200,422],true)&&is_array($json),'invalid HTTP/JSON '.json_encode([$out,$err,$status]));fiscal_assert($status===200||($json['error_code']??'')==='REQUEST_CONCURRENT_RETRY','unsafe concurrent response '.json_encode([$status,$json]));$responses[]=[$status,$json];}
 $documents=(int)$pdo->query("SELECT COUNT(*) FROM fiscal_documents WHERE tenant_id=$tenant AND idempotency_key='$token'")->fetchColumn();$reservations=(int)$pdo->query("SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn();$numbers=(int)$pdo->query("SELECT COUNT(DISTINCT number) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn();$cnfs=(int)$pdo->query("SELECT COUNT(DISTINCT cnf) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn();$keys=(int)$pdo->query("SELECT COUNT(DISTINCT access_key) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn();$artifacts=(int)$pdo->query("SELECT COUNT(*) FROM fiscal_artifacts WHERE tenant_id=$tenant AND status='XSD_VALID_OFFLINE'")->fetchColumn();foreach([$documents,$reservations,$numbers,$cnfs,$keys,$artifacts]as$count)fiscal_assert($count===1,'HTTP double submit created duplicate');
 $thirdCmd=['curl.exe','-sS','-X','POST','-H','Sec-Fetch-Site: same-origin','-b',$cookie];foreach($fields as$field){$thirdCmd[]='--data';$thirdCmd[]=$field;}$thirdCmd[]='http://127.0.0.1:'.$ports[0].'/fiscal_action.php';$p=proc_open($thirdCmd,[1=>['pipe','w'],2=>['pipe','w']],$pp);$third=json_decode(stream_get_contents($pp[1]),true);fclose($pp[1]);fclose($pp[2]);proc_close($p);fiscal_assert(($third['success']??false)===true,'post-success idempotency failed');fiscal_assert((int)$pdo->query("SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn()===1,'third POST duplicated reservation');
 $badFields=$fields;$badCookie='PHPSESSID='.$sid.'; erp_fiscal_csrf=bad';$cmd=['curl.exe','-sS','-w',"\n%{http_code}",'-X','POST','-H','Sec-Fetch-Site: same-origin','-b',$badCookie];foreach($badFields as$field){$cmd[]='--data';$cmd[]=$field;}$cmd[]='http://127.0.0.1:'.$ports[0].'/fiscal_action.php';$p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$bp);$bad=stream_get_contents($bp[1]);fclose($bp[1]);fclose($bp[2]);proc_close($p);fiscal_assert(str_ends_with(trim($bad),'403')&&str_contains($bad,'CSRF_INVALID'),'CSRF was not enforced');
 $mirrorToken=hash('sha256','HTTP-MIRROR-027');$mirrorFields=array_map(fn($v)=>str_starts_with($v,'fiscal_action=')?'fiscal_action=mirror':(str_starts_with($v,'idempotency_key=')?'idempotency_key='.$mirrorToken:$v),$fields);$mclients=[];foreach($ports as$port){$cmd=['curl.exe','-sS','-X','POST','-H','Sec-Fetch-Site: same-origin','-b',$cookie];foreach($mirrorFields as$field){$cmd[]='--data';$cmd[]=$field;}$cmd[]='http://127.0.0.1:'.$port.'/fiscal_action.php';$mclients[]=[$p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$mp),$mp];}foreach($mclients as[$p,$mp]){stream_get_contents($mp[1]);stream_get_contents($mp[2]);fclose($mp[1]);fclose($mp[2]);proc_close($p);}fiscal_assert((int)$pdo->query("SELECT COUNT(*) FROM fiscal_mirrors WHERE tenant_id=$tenant")->fetchColumn()===1,'mirror double submit duplicated snapshot');
 $authCmd=['curl.exe','-sS','-w',"\n%{http_code}",'-X','POST','--data','fiscal_action=retry','http://127.0.0.1:'.$ports[0].'/fiscal_action.php'];$p=proc_open($authCmd,[1=>['pipe','w'],2=>['pipe','w']],$ap);$authOut=stream_get_contents($ap[1]);fclose($ap[1]);fclose($ap[2]);proc_close($p);fiscal_assert(str_ends_with(trim($authOut),'401')&&str_contains($authOut,'UNAUTHENTICATED'),'HTTP auth was not enforced');
 echo'FiscalDocumentDoubleSubmitHttpTest OK requests=2 documents=1 reservations=1 nNF=1 cNF=1 keys=1 artifacts=1 third=idempotent mirror=1 auth=401 csrf=403 responses='.json_encode($responses,JSON_UNESCAPED_UNICODE)."\n";
}finally{foreach($servers as[$proc,$pipes]){proc_terminate($proc);foreach($pipes as$pipe)if(is_resource($pipe))fclose($pipe);proc_close($proc);}try{$server->exec("DROP DATABASE IF EXISTS `$tenantDb`");$server->exec("DROP DATABASE IF EXISTS `$control`");}catch(Throwable){}httpRemoveTree($root);putenv('APP_ENV');putenv('DB_NAME');putenv('FISCAL_TEST_STORAGE_ROOT');}
