<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Fiscal\{A1CertificateInspector,LocalEncryptedSecretStorage,PrivateCertificateStorage};use MiniErp\Services\FiscalReadiness;
function f2(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'minierp-f02-'.bin2hex(random_bytes(6));mkdir($tmp,0700,true);$password=bin2hex(random_bytes(16));$taxId='12345678000195';$opts=['config'=>'C:/xampp/php/extras/openssl/openssl.cnf','private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA,'digest_alg'=>'sha256'];$key=openssl_pkey_new($opts);$csr=openssl_csr_new(['commonName'=>'MINIERP A1 TEST ONLY','organizationName'=>'NO LEGAL VALUE','serialNumber'=>$taxId,'countryName'=>'BR'],$key,$opts);$x509=openssl_csr_sign($csr,null,$key,2,$opts);openssl_pkcs12_export($x509,$pfx,$key,$password);f2(is_string($pfx),'PFX');
$inspector=new A1CertificateInspector();$m=$inspector->inspect($pfx,$password,'test-only.pfx',$taxId);f2($m['tax_id']===$taxId&&$m['operational']&&strlen($m['sha256'])===64,'metadata/hash/assinatura');f2(in_array(($m['code']??''),['CERTIFICATE_VALID','CERTIFICATE_EXPIRING_SOON'],true)&&($m['diagnostic']??'')!=='','diagnostico estruturado');
$expired=(new A1CertificateInspector(time()+10*86400))->inspect($pfx,$password,'test-only.p12',$taxId);f2($expired['status']==='EXPIRED','certificado expirado');
foreach([[$pfx,$password.'x','test.pfx',$taxId],['corrupt',$password,'test.p12',$taxId],[$pfx,$password,'test.exe',$taxId]] as $bad){try{$inspector->inspect(...$bad);throw new RuntimeException('entrada invalida aceita');}catch(Throwable $e){f2($e->getMessage()!=='entrada invalida aceita','fail closed');}}$mismatch=$inspector->inspect($pfx,$password,'test.pfx','99999999000199');f2($mismatch['status']==='INVALID_IDENTITY'&&!$mismatch['operational'],'mismatch armazenavel e inativo');
$certStorage=new PrivateCertificateStorage($tmp.'/certificates');$ref=$certStorage->store(14,7,'p12',$pfx);f2(!str_contains($ref,'..')&&$certStorage->read($ref)===$pfx,'storage privado');try{$certStorage->read('../public/a.pfx');throw new RuntimeException('traversal aceito');}catch(Throwable $e){f2($e->getMessage()!=='traversal aceito','traversal bloqueado');}
try{$certStorage->read('C:/public/a.pfx');throw new RuntimeException('absoluto aceito');}catch(Throwable $e){f2($e->getMessage()!=='absoluto aceito','path absoluto bloqueado');}
$vault=new LocalEncryptedSecretStorage($tmp.'/secrets',str_repeat('K',32));$secretRef=$vault->put('tenant-14/establishment-7',$password);$raw=file_get_contents($tmp.'/secrets/'.$secretRef);f2(!str_contains((string)$raw,$password)&&$vault->get($secretRef)===$password,'segredo cifrado');
$est=['tax_id'=>$taxId,'legal_name'=>'TEST','state_registration'=>'1','tax_regime_code'=>'3','street'=>'R','number'=>'1','district'=>'C','city_ibge_code'=>'3550308','city_name'=>'SP','state'=>'SP','postal_code'=>'01001000'];$cert=['status'=>'VALID','tax_id'=>$taxId,'valid_until'=>date('Y-m-d H:i:s',time()+86400)];$ready=(new FiscalReadiness())->evaluate($est,$cert,[['environment'=>2,'active'=>1,'model'=>'55','series'=>1]]);f2($ready['certificate_ready']&&$ready['status']==='TECHNICALLY_READY_OFFLINE'&&!$ready['homologation_ready']&&!$ready['production_ready'],'readiness');
$repoSource=file_get_contents(__DIR__.'/../src/Repositories/FiscalConfigurationRepository.php');$allocatorSource=file_get_contents(__DIR__.'/../src/Fiscal/FiscalNumberAllocator.php');$page=file_get_contents(__DIR__.'/../public/plataforma/empresa-fiscal-config.php');$migration=file_get_contents(__DIR__.'/../migrations/20260821_create_fiscal_credentials_and_series_audit.sql');f2(str_contains($repoSource,'environment!==2')&&str_contains($repoSource,'fiscal_series_audit')&&str_contains($repoSource,'fiscal_number_reservations'),'serie/auditoria/producao');f2(str_contains($allocatorSource,'FOR UPDATE')&&str_contains($allocatorSource,'tenant_id=? AND establishment_id=?'),'allocator concorrente e isolado');f2(str_contains($page,'requirePlatformUserCsrf')&&str_contains($page,'getSelectedTenantId')&&!str_contains($page,'$_POST[\'tenant_id\']'),'CSRF/IDOR');f2(!str_contains($migration,'password')&&!str_contains($migration,'DROP ')&&!str_contains($migration,'DELETE '),'migration segura');
$vault->delete($secretRef);$certStorage->delete($ref);@rmdir(dirname($tmp.'/secrets/'.$secretRef));@rmdir($tmp.'/secrets/tenant-14');@rmdir($tmp.'/secrets');@rmdir(dirname($tmp.'/certificates/'.$ref));@rmdir($tmp.'/certificates/tenant-14');@rmdir($tmp.'/certificates');@rmdir($tmp);unset($password,$pfx,$key,$csr,$x509);echo "Fiscal02CertificateAndSeries OK\n";
