<?php
declare(strict_types=1);

if(getenv('RUN_FISCAL_MARIADB_TESTS')!=='1'){echo "FiscalDanfePreviewWithoutCertificate SKIPPED\n";exit;}
require __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/../app/Repository.php';
require __DIR__.'/helpers/FiscalPipelineTestSupport.php';

use MiniErp\Fiscal\FiscalTaxRule;
use MiniErp\Fiscal\TaxRuleResolver;
use MiniErp\Repositories\{CompanyFiscalSettingsRepository,FiscalConfigurationRepository,FiscalOperationRepository,MariaDbTaxRuleRepository};
use MiniErp\Services\{CreateInternalFiscalDocumentService,FiscalDanfeException,FiscalDanfePreviewService};

[$server,$pdo,$database]=fiscal_test_db();
$tenant=990038;$actor=990038;$cache=sys_get_temp_dir().'/minierp-danfe-preview-'.bin2hex(random_bytes(4));
$remove=function(string $path)use(&$remove):void{if(!is_dir($path))return;foreach(new FilesystemIterator($path)as$file){$file->isDir()?$remove($file->getPathname()):unlink($file->getPathname());}rmdir($path);};
try{
 if(session_status()===PHP_SESSION_NONE)session_start();
 $_SESSION=['erp_user_id'=>$actor,'erp_tenant_id'=>$tenant,'user_id'=>$actor,'tenant_id'=>$tenant,'current_company_id'=>1];
 $pdo->prepare("INSERT INTO establishments(tenant_id,tax_id,legal_name,trade_name,state_registration,tax_regime_code,street,number,district,city_ibge_code,city_name,state,postal_code,country_code,country_name,status,fiscal_readiness) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$tenant,'12345678000195','EMITENTE PREVIEW TEST_ONLY','PREVIEW TEST_ONLY','123456789','1','Rua Emitente','100','Centro','4106902','Curitiba','PR','80000000','1058','BRASIL','ativo','READY']);
 $establishment=(int)$pdo->lastInsertId();$repo=new Repository($pdo,false);
 $repo->saveCliente(['nome'=>'CLIENTE PREVIEW TEST_ONLY','email'=>'preview@example.invalid','telefone'=>'41999999999','cpf_cnpj'=>'98765432000110','person_type'=>'PJ','state_registration_indicator'=>'9','logradouro'=>'Rua Cliente','numero'=>'200','bairro'=>'Centro','municipio'=>'Curitiba','codigo_ibge'=>'4106902','estado'=>'PR','cep'=>'80010000','country_code'=>'1058','country_name'=>'BRASIL','pessoa_fisica'=>'nao','tipo_pessoa'=>['cliente'],'status'=>'ativo']);$customer=(int)$pdo->lastInsertId();
 $repo->saveProduto(['nome'=>'NOTEBOOK PREVIEW TEST_ONLY','codigo'=>'PREVIEW-038','ncm'=>'84713012','merchandise_origin'=>'0','unidade'=>'UN','taxable_unit'=>'UN','conversion_factor'=>'1','gtin'=>'SEM GTIN','gtin_tributable'=>'SEM GTIN','cfop_padrao'=>'','categoria'=>'TEST_ONLY','preco'=>'100.00','estoque_atual'=>'0','status'=>'ativo']);$product=(int)$pdo->lastInsertId();
 foreach(['1102','2102','5102','6102']as$cfop)$pdo->prepare("INSERT INTO cfops(codigo,descricao,natureza,aplicacao,status) VALUES(?,?,'TEST_ONLY','TEST_ONLY','ativo')")->execute([$cfop,'CFOP TEST_ONLY '.$cfop]);
 (new CompanyFiscalSettingsRepository($pdo,$tenant))->saveCfops($establishment,['ENTRY_INTERNAL'=>'1102','ENTRY_INTERSTATE'=>'2102','EXIT_INTERNAL'=>'5102','EXIT_INTERSTATE'=>'6102'],$actor);
 $taxRepo=new MariaDbTaxRuleRepository($pdo,$tenant);$taxRepo->addVersion(new FiscalTaxRule(null,$tenant,'PREVIEW_038_55',1,100,new DateTimeImmutable('2026-01-01'),null,'TEST_ONLY','1','2026-08-24',['crt'=>'1','origin_state'=>'PR','destination_state'=>'PR','ncm'=>'84713012','product_origin'=>'0','direction'=>'EXIT','model'=>'55','cfop_hint'=>'5102'],'5102',['csosn'=>'102','orig'=>'0'],[],['cst'=>'49'],['cst'=>'49'],[],[],'ACTIVE','TEST_ONLY'));$taxRepo->addVersion(new FiscalTaxRule(null,$tenant,'PREVIEW_039_65',1,100,new DateTimeImmutable('2026-01-01'),null,'TEST_ONLY','1','2026-08-24',['crt'=>'1','origin_state'=>'PR','destination_state'=>'PR','ncm'=>'84713012','product_origin'=>'0','direction'=>'EXIT','model'=>'65','cfop_hint'=>'5102'],'5102',['csosn'=>'102','orig'=>'0'],[],['cst'=>'49'],['cst'=>'49'],[],[],'ACTIVE','TEST_ONLY'));
 (new CompanyFiscalSettingsRepository($pdo,$tenant))->saveGeneral($establishment,['environment'=>2,'primary_model'=>'65'],$actor);$loadedSettings=(new CompanyFiscalSettingsRepository($pdo,$tenant))->all($establishment);fiscal_assert($loadedSettings['general']['primary_model']==='65','company model round-trip');fiscal_assert((new \MiniErp\Services\FiscalPreviewModelResolver())->resolve(null,$loadedSettings['general']['primary_model'])==='65','company model fallback');
 (new FiscalConfigurationRepository($pdo,$tenant))->saveSeries($establishment,'55',37,41,2,true,$actor,'TEST_ONLY preview invariance');
 $operations=new FiscalOperationRepository($pdo,$tenant);$order=$operations->createOrder(['tipo'=>'saida','establishment_id'=>$establishment,'cliente_id'=>$customer,'codigo_interno'=>'PREVIEW-038','data_venda'=>'2026-08-24','operation_nature'=>'VENDA TEST_ONLY','fiscal_model'=>'55','purpose'=>'NORMAL','final_consumer'=>1,'presence_indicator'=>'1','payment_method'=>'01','freight_mode'=>'9'],[['produto_id'=>$product,'quantidade'=>'1','preco_unitario'=>'100.00']],$actor);
 $order65=$operations->createOrder(['tipo'=>'saida','establishment_id'=>$establishment,'cliente_id'=>$customer,'codigo_interno'=>'PREVIEW-039-65','data_venda'=>'2026-08-24','operation_nature'=>'VENDA TEST_ONLY','fiscal_model'=>'65','purpose'=>'NORMAL','final_consumer'=>1,'presence_indicator'=>'1','payment_method'=>'01','freight_mode'=>'9'],[['produto_id'=>$product,'quantidade'=>'1','preco_unitario'=>'100.00']],$actor);
 fiscal_assert($operations->order($order)['fiscal_model']==='55'&&$operations->order($order65)['fiscal_model']==='65','selected model persistence');
 $before=['series'=>(int)$pdo->query("SELECT next_number FROM fiscal_series WHERE tenant_id=$tenant AND establishment_id=$establishment AND model='55' AND series=37")->fetchColumn(),'reservations'=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn(),'documents'=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_documents WHERE tenant_id=$tenant")->fetchColumn(),'certificates'=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_certificates WHERE tenant_id=$tenant")->fetchColumn()];
 $service=new FiscalDanfePreviewService($pdo,$operations,new TaxRuleResolver($taxRepo),$cache);$results=[];for($i=0;$i<10;$i++)$results[]=$service->render($order);
 $results65=[];for($i=0;$i<10;$i++)$results65[]=$service->render($order65);$first65=$results65[0];$last65=$results65[9];fiscal_assert($first65['cache']==='MISS'&&$last65['cache']==='HIT','DANFC-e cache MISS/HIT');fiscal_assert($first65['model']==='65'&&$first65['renderer']==='NFePHP\\DA\\NFe\\Danfce'&&$first65['page_format']==='80mm','model 65 compact router');fiscal_assert(str_contains($first65['xml'],'<mod>65</mod>'),'XML model 65');fiscal_assert(str_starts_with($first65['bytes'],'%PDF')&&strlen($first65['bytes'])>4000,'valid model 65 PDF bytes='.strlen($first65['bytes']));
 fiscal_assert($first65['model_source']==='EXPLICIT','model 65 explicit source');
 $first=$results[0];$last=$results[9];fiscal_assert($first['cache']==='MISS'&&$last['cache']==='HIT','preview cache MISS/HIT');fiscal_assert(str_starts_with($first['bytes'],'%PDF')&&strlen($first['bytes'])>10000,'valid non-empty PDF');fiscal_assert($first['page_format']==='A4'&&$first['preview']===true,'A4 preview metadata');
 fiscal_assert($first['model_source']==='EXPLICIT','model 55 explicit source');
 $switchHashes=[];for($i=0;$i<20;$i++){$selected=$i%2===0?'55':'65';$operations->updateOrder($order,['cliente_id'=>$customer,'data_venda'=>'2026-08-24','operation_nature'=>'VENDA TEST_ONLY','fiscal_model'=>$selected,'purpose'=>'NORMAL','final_consumer'=>1,'presence_indicator'=>'1','payment_method'=>'01','freight_mode'=>'9'],[['produto_id'=>$product,'quantidade'=>'1','preco_unitario'=>'100.00']]);$switched=$service->render($order);fiscal_assert($switched['model']===$selected&&$switched['model_source']==='EXPLICIT','first preview after model switch '.$selected);fiscal_assert($selected==='55'?$switched['renderer']==='NFePHP\\DA\\NFe\\Danfe':$switched['renderer']==='NFePHP\\DA\\NFe\\Danfce','consumer final renderer '.$selected);$switchHashes[$selected]=$switched['sha256'];}fiscal_assert(count($switchHashes)===2&&$switchHashes['55']!==$switchHashes['65'],'same-order cache isolation');
 fiscal_assert($first['model']==='55'&&$first['renderer']==='NFePHP\\DA\\NFe\\Danfe'&&str_contains($first['xml'],'<mod>55</mod>'),'model 55 A4 router');fiscal_assert($first['sha256']!==$first65['sha256'],'models cannot share cached PDF');
 $mediaBox=static function(string$pdf):array{if(!preg_match('/\/MediaBox\s*\[\s*0\s+0\s+([0-9.]+)\s+([0-9.]+)\s*\]/',$pdf,$m))return[];return[(float)$m[1],(float)$m[2]];};$previewBox=$mediaBox($first['bytes']);$reference=(string)file_get_contents(__DIR__.'/../output/pdf/DANFE-TEST-ONLY-OFFLINE.pdf');$referenceBox=$mediaBox($reference);fiscal_assert(count($previewBox)===2&&abs($previewBox[0]-595)<2&&abs($previewBox[1]-842)<2,'preview must have A4 MediaBox');fiscal_assert(count($referenceBox)===2&&abs($previewBox[0]-$referenceBox[0])<1&&abs($previewBox[1]-$referenceBox[1])<1,'reference layout MediaBox equivalence');fiscal_assert(substr_count($first['bytes'],'/Type /Page')>=1&&substr_count($reference,'/Type /Page')>=1,'PDF must contain pages');
 foreach(['EMITENTE PREVIEW','CLIENTE PREVIEW','NOTEBOOK PREVIEW','84713012','5102','PRÉVIA DANFE','NÃO TRANSMITIDA À SEFAZ','SEM VALOR FISCAL']as$text)fiscal_assert(str_contains($first['xml'],$text),'XML missing '.$text.' names='.json_encode((preg_match_all('/<xNome>(.*?)<\/xNome>/u',$first['xml'],$matches)?$matches[1]:[]),JSON_UNESCAPED_UNICODE));
 fiscal_assert(!str_contains($first['xml'],'<Signature')&&!str_contains($first['xml'],'<protNFe'),'preview cannot be signed or protocolled');fiscal_assert($first['official_access_key']===null&&strlen($first['technical_key'])===44,'technical identity only');
 $after=['series'=>(int)$pdo->query("SELECT next_number FROM fiscal_series WHERE tenant_id=$tenant AND establishment_id=$establishment AND model='55' AND series=37")->fetchColumn(),'reservations'=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id=$tenant")->fetchColumn(),'documents'=>(int)$pdo->query("SELECT COUNT(*) FROM fiscal_documents WHERE tenant_id=$tenant")->fetchColumn()];fiscal_assert($before['series']===$after['series']&&$before['reservations']===$after['reservations']&&$before['documents']===$after['documents'],'preview mutated fiscal state');fiscal_assert($before['certificates']===0,'fixture must not have certificate');
 $idor=false;try{(new FiscalDanfePreviewService($pdo,new FiscalOperationRepository($pdo,$tenant+1),new TaxRuleResolver(new MariaDbTaxRuleRepository($pdo,$tenant+1)),$cache))->render($order);}catch(Throwable){$idor=true;}fiscal_assert($idor,'cross-tenant order must be rejected');
 $created=(new CreateInternalFiscalDocumentService($operations,new TaxRuleResolver($taxRepo)))->create($order,hash('sha256','PREVIEW-038-REAL'),$actor);$realBlocked=false;try{fiscal_pipeline_service($pdo,$tenant)->prepare($tenant,(int)$created['id'],$actor);}catch(Throwable$e){$realBlocked=str_contains(strtoupper($e->getMessage()),'CERTIFICATE')||str_contains(strtoupper($e->getMessage()),'CERTIFICADO');}fiscal_assert($realBlocked,'real pipeline must still require A1');
 echo json_encode(['previews_55'=>10,'previews_65'=>10,'model_55'=>['renderer'=>$first['renderer'],'bytes'=>strlen($first['bytes']),'format'=>$first['page_format'],'media_box'=>$previewBox,'xml_model'=>'55','reference_layout'=>'PASS'],'model_65'=>['renderer'=>$first65['renderer'],'bytes'=>strlen($first65['bytes']),'format'=>$first65['page_format'],'xml_model'=>'65'],'company_model_roundtrip'=>'65','cache_isolated'=>true,'series_before'=>$before['series'],'series_after'=>$after['series'],'reservations_before'=>$before['reservations'],'reservations_after'=>$after['reservations'],'documents_before'=>$before['documents'],'documents_after'=>$after['documents'],'certificate_count'=>0,'idor'=>'BLOCKED','real_pipeline'=>'BLOCKED_CERTIFICATE','official_access_key'=>null,'sefaz_calls'=>0],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),PHP_EOL;
}finally{$remove($cache);fiscal_drop_database($server,$database);}
