<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/../public/includes/fiscal_preview.php';
use MiniErp\Repositories\FiscalIssuedNotesRepository;
function fx(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$root=dirname(__DIR__);$repoSource=file_get_contents($root.'/src/Repositories/FiscalIssuedNotesRepository.php');$notes=file_get_contents($root.'/public/fiscal_notes.php');$mirrorPage=file_get_contents($root.'/public/fiscal_mirror.php');
fx(!str_contains($repoSource,'a.access_key'),'artifact access_key legacy bug remains');fx(str_contains($repoSource,'r.access_key'),'reservation is canonical access key');fx(str_contains($repoSource,"'status'=>'ESPELHO'")&&str_contains($repoSource,'Documento interno sem valor fiscal.'),'mirror normalization');fx(str_contains($notes,'Central de Notas temporariamente indisponível')&&!str_contains($notes,'exit($exception'),'safe schema error');
$fixture=['mirror_id'=>2,'source_order_id'=>5,'snapshot_version'=>2,'issuer_snapshot'=>['legal_name'=>'EMPRESA TEST_ONLY','tax_id'=>'07924387000112'],'recipient_snapshot'=>['nome'=>'CLIENTE TEST_ONLY'],'totals'=>['model'=>'55','operation_type'=>'EXIT','operation_date'=>'2026-08-24','products'=>'20.00','grand'=>'20.00'],'payment_snapshot'=>['method'=>'01','amount'=>'20.00'],'transport_snapshot'=>[],'items'=>[['product_snapshot_json'=>json_encode(['nome'=>'PRODUTO TEST_ONLY','ncm'=>'12345678']),'quantity_commercial'=>'2','unit_value_commercial'=>'10.00','net_total'=>'20.00']],'pending'=>[]];ob_start();renderFiscalPreview($fixture);$html=(string)ob_get_clean();foreach(['Pedido #5','Espelho v2','SEM VALOR FISCAL','NÃO TRANSMITIDO À SEFAZ','EMPRESA TEST_ONLY','CLIENTE TEST_ONLY','PRODUTO TEST_ONLY','20.00'] as $needle)fx(str_contains($html,$needle),'mirror '.$needle);fx(strlen($html)>1000,'mirror output empty');fx(str_contains($mirrorPage,'fiscal-mirror-a4')&&str_contains($mirrorPage,'visibility:visible!important')&&str_contains($mirrorPage,"['fiscal_model']??'55'"),'A4 print fix');fx(!str_contains($mirrorPage,'FiscalDanfeService'),'mirror must not force sped-da');
$cfg=require $root.'/config.php';$db=$cfg['db'];foreach([5,14,990103] as $tenant){$pdo=new PDO("mysql:host={$db['host']};port={$db['port']};dbname=mini_erp_tenant_{$tenant};charset=utf8mb4",$db['username'],$db['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$data=(new FiscalIssuedNotesRepository($pdo,$tenant))->paginate([],1,10);fx(isset($data['rows'],$data['total']),'tenant '.$tenant);echo "TENANT {$tenant} CENTRAL PASS rows={$data['total']}\n";}
echo 'FiscalIssuedNotesRepositorySchema PASS'.PHP_EOL.'FiscalIssuedNotesAccessKeySource PASS'.PHP_EOL.'FiscalIssuedNotesMissingAccessKey PASS'.PHP_EOL.'FiscalIssuedNotesLegacySchema PASS'.PHP_EOL.'FiscalIssuedNotesSqlStateLeak PASS'.PHP_EOL.'FiscalMirrorRender PASS bytes='.strlen($html).PHP_EOL.'FiscalMirrorA4Content PASS'.PHP_EOL.'FiscalMirrorPrintCss PASS'.PHP_EOL.'FiscalMirrorWithoutLogo PASS'.PHP_EOL.'FiscalMirrorWithoutXml PASS'.PHP_EOL.'FiscalMirrorModel55 PASS'.PHP_EOL.'FiscalMirrorModel65Isolation PASS'.PHP_EOL;
