<?php
declare(strict_types=1);

if (getenv('RUN_ORDER_HTTP_TESTS') !== '1') { echo "OrderCrudHttp SKIPPED\n"; exit; }
require_once __DIR__ . '/../vendor/autoload.php';
use MiniErp\Repositories\FiscalOperationRepository;

function orderHttpAssert(bool $condition, string $label): void { if (!$condition) throw new RuntimeException($label); }
function orderHttpCpf(): string {
    $base = str_pad((string)random_int(100000000, 999999999), 9, '0', STR_PAD_LEFT);
    for ($position=9; $position<11; $position++) {
        $sum=0; for ($i=0; $i<$position; $i++) $sum+=(int)$base[$i]*($position+1-$i);
        $digit=11-($sum%11); $base.=$digit>=10?'0':(string)$digit;
    }
    return $base;
}
function orderHttp(string $url, string $sessionId, ?array $post = null, bool $multipart=false): array {
    $curl = curl_init($url);
    curl_setopt_array($curl, [CURLOPT_RETURNTRANSFER=>true, CURLOPT_HEADER=>true, CURLOPT_FOLLOWLOCATION=>false, CURLOPT_COOKIE=>'PHPSESSID='.$sessionId.'; erp_fiscal_csrf='.($GLOBALS['orderHttpCsrf']??''), CURLOPT_TIMEOUT=>20]);
    if ($post !== null) curl_setopt_array($curl, [CURLOPT_POST=>true, CURLOPT_POSTFIELDS=>$multipart?$post:http_build_query($post)]);
    $raw = (string)curl_exec($curl); $status = (int)curl_getinfo($curl, CURLINFO_RESPONSE_CODE); $headerSize = (int)curl_getinfo($curl, CURLINFO_HEADER_SIZE);
    if (curl_errno($curl)) throw new RuntimeException('HTTP transport: '.curl_error($curl));
    curl_close($curl); return ['status'=>$status, 'headers'=>substr($raw,0,$headerSize), 'body'=>substr($raw,$headerSize)];
}

$tenantId=14; $userId=9; $csrf=bin2hex(random_bytes(32)); $masterCsrf=bin2hex(random_bytes(32)); $GLOBALS['orderHttpCsrf']=$csrf; $sessionId='ordercrud'.bin2hex(random_bytes(10));
session_id($sessionId); session_start(); $_SESSION=['erp_user_id'=>$userId,'erp_tenant_id'=>$tenantId,'user_id'=>$userId,'tenant_id'=>$tenantId,'current_company_id'=>$tenantId,'erp_fiscal_csrf'=>$csrf,'erp_master_data_csrf'=>$masterCsrf]; session_write_close();
$config=require __DIR__.'/../config.php'; $db=$config['db'];
$pdo=new PDO("mysql:host={$db['host']};port={$db['port']};dbname=mini_erp_tenant_{$tenantId};charset=utf8mb4",$db['username'],$db['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$customer=$pdo->query('SELECT id FROM clientes ORDER BY id LIMIT 1')->fetchColumn(); $product=$pdo->query("SELECT id,preco FROM produtos ORDER BY id DESC LIMIT 1")->fetch();$cfop=$pdo->query("SELECT id,descricao FROM cfops WHERE status='ativo' AND LEFT(codigo,1) IN ('5','6','7') ORDER BY id LIMIT 1")->fetch();
orderHttpAssert((int)$customer>0&&is_array($product)&&is_array($cfop),'TEST_ONLY fixtures');
$code='TEST_ONLY_HTTP_'.bin2hex(random_bytes(5)); $base='http://127.0.0.1/MiniRP/mini-erp-web/public/'; $orderId=0; $driverId=0; $success=false;
try {
    $driverCpf=orderHttpCpf(); $driverName='MOTORISTA TEST_ONLY PROMPT 066';
    $driverSave=orderHttp($base.'master_data_action.php',$sessionId,['csrf'=>$masterCsrf,'entity'=>'person','source_type'=>'motorista','operation'=>'save','id'=>'','nome'=>$driverName,'cpf'=>$driverCpf,'cnh'=>'CNH066'.random_int(1000,9999),'categoria_cnh'=>'D','vencimento_cnh'=>'2030-12-31','telefone'=>'','status'=>'ativo']);
    $driverJson=json_decode($driverSave['body'],true);orderHttpAssert($driverSave['status']===200&&($driverJson['success']??false),'OrderDriverMasterDataHttpTest status='.$driverSave['status'].' body='.$driverSave['body']);
    $driverQuery=$pdo->prepare('SELECT id FROM motoristas WHERE cpf=? AND nome=?');$driverQuery->execute([$driverCpf,$driverName]);$driverId=(int)$driverQuery->fetchColumn();orderHttpAssert($driverId>0,'OrderDriverMasterDataPersistenceTest');
    $newOrderPage=orderHttp($base.'?page=pedidos&tab=saida',$sessionId);orderHttpAssert($newOrderPage['status']===200&&str_contains($newOrderPage['body'],'value="'.$driverId.'"')&&str_contains($newOrderPage['body'],$driverName),'OrderDriverSelectorRefreshTest');
    orderHttpAssert(substr_count($newOrderPage['body'],'data-order-action="save"')===1&&substr_count($newOrderPage['body'],'name="action" value="save_fiscal_order"')===1,'OrderActionBarNoDuplicateButtonsTest');
    foreach(['Gravar','Nota','Financeiro','Imprimir Pedido','Nova'] as $actionLabel)orderHttpAssert(str_contains($newOrderPage['body'],'>'.$actionLabel.'<'),'OrderActionBarUiTest '.$actionLabel);
    orderHttpAssert(!str_contains($newOrderPage['body'],'>Importar XML<')&&!str_contains($newOrderPage['body'],'>Concluir pedido<')&&!str_contains($newOrderPage['body'],'>Salvar prévia interna<'),'OrderActionImportXmlEntryOnlyTest saída / redundant actions');
    $entryOrderPage=orderHttp($base.'?page=pedidos&tab=entrada',$sessionId);orderHttpAssert($entryOrderPage['status']===200&&str_contains($entryOrderPage['body'],'>Importar XML<'),'OrderActionImportXmlEntryOnlyTest entrada');
    orderHttpAssert(str_contains($newOrderPage['body'],'Financeiro será integrado ao módulo de contas e estoque.')&&preg_match('/<button class="order-routine" type="button" disabled[^>]+Financeiro/', $newOrderPage['body'])===1,'OrderActionFinanceDisabledTest');
    orderHttpAssert(str_contains($newOrderPage['body'],"window.open('','_blank')")&&str_contains($newOrderPage['body'],'Gerando prévia...'),'OrderActionPrintNewTabContractTest');
    orderHttpAssert(str_contains($newOrderPage['body'],'Existem alterações não salvas. Deseja iniciar um novo pedido?'),'OrderActionNewDirtyStateTest');
    $payload=['action'=>'save_fiscal_order','csrf_token'=>$csrf,'tipo'=>'saida','order_id'=>'0','establishment_id'=>'5','cliente_id'=>(string)$customer,'transportadora_id'=>'','vendedor_id'=>'','fornecedor_id'=>'','motorista_id'=>'','fiscal_model'=>'55','cfop_id'=>(string)$cfop['id'],'operation_nature'=>'POST_NAO_CONFIAVEL','purpose'=>'NORMAL','presence_indicator'=>'1','data_venda'=>date('Y-m-d'),'codigo_interno'=>$code,'payment_method'=>'01','itens'=>[['produto_id'=>(string)$product['id'],'quantidade'=>'2','preco_unitario'=>(string)$product['preco'],'desconto'=>'0']]];
    $entryCfop=(int)$pdo->query("SELECT id FROM cfops WHERE status='ativo' AND LEFT(codigo,1) IN ('1','2','3') ORDER BY id LIMIT 1")->fetchColumn();if($entryCfop>0){$invalidNature=$payload;$invalidNature['cfop_id']=(string)$entryCfop;$invalidNature['codigo_interno']=$code.'_INVALID_CFOP';orderHttp($base.'?page=pedidos&tab=saida',$sessionId,$invalidNature);$invalidNatureQuery=$pdo->prepare('SELECT COUNT(*) FROM fiscal_orders WHERE tenant_id=? AND internal_code=?');$invalidNatureQuery->execute([$tenantId,$invalidNature['codigo_interno']]);orderHttpAssert((int)$invalidNatureQuery->fetchColumn()===0,'OrderNatureInvalidPostTest');}
    $save=orderHttp($base.'?page=pedidos&tab=saida',$sessionId,$payload);
    orderHttpAssert($save['status']===302&&str_contains($save['headers'],'tab=emitidos')&&str_contains($save['headers'],'highlight_order='),'OrderSaveRedirectIssuedOrdersTest status='.$save['status'].' headers='.preg_replace('/\s+/',' ',$save['headers']));
    $query=$pdo->prepare('SELECT * FROM fiscal_orders WHERE tenant_id=? AND internal_code=?'); $query->execute([$tenantId,$code]); $order=$query->fetch();
    orderHttpAssert(is_array($order),'OrderCreatePersistenceTest'); $orderId=(int)$order['id'];
    orderHttpAssert((int)$order['person_id']===(int)$customer&&$order['fiscal_model']==='55'&&$order['operation_nature']===$cfop['descricao'],'OrderCreateCustomerTest / OrderNatureBackendValidationTest');
    $itemCount=$pdo->query('SELECT COUNT(*) FROM fiscal_order_items WHERE order_id='.$orderId)->fetchColumn(); orderHttpAssert((int)$itemCount===1,'OrderCreateItemsTest');
    $list=orderHttp($base.'?page=pedidos&tab=emitidos&io_q='.urlencode($code),$sessionId); orderHttpAssert($list['status']===200&&str_contains($list['body'],'<small>'.$code.'</small>'),'listing');
    $refresh=orderHttp($base.'?page=pedidos&tab=emitidos&io_q='.urlencode($code),$sessionId); orderHttpAssert($refresh['status']===200&&str_contains($refresh['body'],'<small>'.$code.'</small>'),'refresh listing');
    orderHttpAssert(substr_count($list['body'],'issued-orders.js?v=')===1&&str_contains($list['body'],'app.js?v='),'asset versioning / unique scripts');
    preg_match('/src="(assets\/issued-orders\.js\?v=\d+)"/',$list['body'],$assetMatch); orderHttpAssert(!empty($assetMatch[1])&&orderHttp($base.$assetMatch[1],$sessionId)['status']===200,'issued-orders asset real path');
    foreach(['app.js','style.css','issued-orders.css']as$requiredAsset){preg_match('/(?:src|href)="(assets\/'.preg_quote($requiredAsset,'/').'\?v=\d+)"/',$list['body'],$requiredMatch);orderHttpAssert(!empty($requiredMatch[1])&&orderHttp($base.$requiredMatch[1],$sessionId)['status']===200,'required asset 200 '.$requiredAsset);}
    $reopen=orderHttp($base.'?page=pedidos&tab=saida&order_id='.$orderId,$sessionId); orderHttpAssert($reopen['status']===200&&str_contains($reopen['body'],'value="'.$orderId.'"'),'reopen');
    $documentsBefore=(int)$pdo->query('SELECT COUNT(*) FROM fiscal_documents WHERE source_order_id='.$orderId)->fetchColumn();
    $danfeWithoutDocument=orderHttp($base.'fiscal_danfe_preview.php?order_id='.$orderId,$sessionId);orderHttpAssert($documentsBefore===0&&$danfeWithoutDocument['status']===200&&str_contains($danfeWithoutDocument['headers'],'application/pdf')&&str_starts_with($danfeWithoutDocument['body'],'%PDF'),'OrderDanfe55WithoutFiscalDocumentTest');
    $updatePayload=$payload;$updatePayload['order_id']=(string)$orderId;$updatePayload['fiscal_model']='65';$updatePayload['itens'][0]['quantidade']='3';
    $update=orderHttp($base.'?page=pedidos&tab=saida&order_id='.$orderId,$sessionId,$updatePayload);orderHttpAssert($update['status']===302&&str_contains($update['headers'],'highlight_order='.$orderId),'OrderUpdateRedirectTest');
    $updated=$pdo->query('SELECT fiscal_model FROM fiscal_orders WHERE id='.$orderId)->fetchColumn();$updatedQuantity=$pdo->query('SELECT quantity FROM fiscal_order_items WHERE order_id='.$orderId)->fetchColumn();$sameCodeCount=$pdo->query("SELECT COUNT(*) FROM fiscal_orders WHERE internal_code=".$pdo->quote($code))->fetchColumn();orderHttpAssert($updated==='65'&&(float)$updatedQuantity===3.0&&(int)$sameCodeCount===1,'OrderUpdateReadBackNoDuplicateTest');
    $danfceWithoutDocument=orderHttp($base.'fiscal_danfe_preview.php?order_id='.$orderId,$sessionId);$documentsAfterPreview=(int)$pdo->query('SELECT COUNT(*) FROM fiscal_documents WHERE source_order_id='.$orderId)->fetchColumn();orderHttpAssert($danfceWithoutDocument['status']===200&&str_contains($danfceWithoutDocument['headers'],'application/pdf')&&str_starts_with($danfceWithoutDocument['body'],'%PDF')&&$documentsAfterPreview===0,'OrderDanfce65WithoutFiscalDocumentReadOnlyTest');
    $restorePayload=$payload;$restorePayload['order_id']=(string)$orderId;$restore=orderHttp($base.'?page=pedidos&tab=saida&order_id='.$orderId,$sessionId,$restorePayload);orderHttpAssert($restore['status']===302,'OrderUpdateRestore55Test');
    $clone=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'clone','order_id'=>$orderId]); $cloneJson=json_decode($clone['body'],true); orderHttpAssert($clone['status']===200&&($cloneJson['success']??false),'clone regression');
    $cloneId=(int)($cloneJson['order_id']??0); orderHttpAssert($cloneId>0&&(int)$pdo->query('SELECT COUNT(*) FROM fiscal_order_items WHERE order_id='.$cloneId)->fetchColumn()===1,'clone read-back');
    $cloneDelete=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'delete','order_id'=>$cloneId]); orderHttpAssert($cloneDelete['status']===200,'clone cleanup through endpoint');
    $invalid=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>'invalid','order_action'=>'delete','order_id'=>$orderId]); orderHttpAssert($invalid['status']===403,'OrderDeleteCsrfTest');
    orderHttpAssert((int)$pdo->query('SELECT COUNT(*) FROM fiscal_orders WHERE id='.$orderId)->fetchColumn()===1,'invalid CSRF no write');
    $delete=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'delete','order_id'=>$orderId]); $deleteJson=json_decode($delete['body'],true);
    orderHttpAssert($delete['status']===200&&($deleteJson['success']??false),'OrderDeleteHttpTest');
    orderHttpAssert((int)$pdo->query('SELECT COUNT(*) FROM fiscal_orders WHERE id='.$orderId)->fetchColumn()===0&&(int)$pdo->query('SELECT COUNT(*) FROM fiscal_order_items WHERE order_id='.$orderId)->fetchColumn()===0,'OrderDeletePersistenceTest / items');
    $deletedList=orderHttp($base.'?page=pedidos&tab=emitidos&io_q='.urlencode($code),$sessionId);orderHttpAssert($deletedList['status']===200&&!str_contains($deletedList['body'],'<small>'.$code.'</small>'),'OrderDeleteDisappearsFromIssuedListTest');
    $again=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'delete','order_id'=>$orderId]); orderHttpAssert($again['status']===200&&(json_decode($again['body'],true)['success']??false),'OrderDeleteDoubleClickTest');
    $finalCode=$code.'_FINAL';$finalPayload=$payload;$finalPayload['codigo_interno']=$finalCode;$finalPayload['transportadora_id']='';$finalPayload['motorista_id']=(string)$driverId;$finalPayload['freight_mode']='0';$finalPayload['vehicle_plate']='ABC1D23';$finalPayload['vehicle_state']='SP';$finalPayload['vehicle_rntc']='TEST066';$finalPayload['volume_quantity']='2';$finalPayload['volume_species']='CAIXA';$finalPayload['volume_brand']='TEST_ONLY';$finalPayload['volume_numbering']='1-2';$finalPayload['gross_weight']='12,500';$finalPayload['net_weight']='11,800';
    $finalSave=orderHttp($base.'?page=pedidos&tab=saida',$sessionId,$finalPayload);orderHttpAssert($finalSave['status']===302&&str_contains($finalSave['headers'],'tab=emitidos'),'OrderFinalize create via form');
    $finalQuery=$pdo->prepare('SELECT id FROM fiscal_orders WHERE tenant_id=? AND internal_code=?');$finalQuery->execute([$tenantId,$finalCode]);$finalOrder=(int)$finalQuery->fetchColumn();orderHttpAssert($finalOrder>0,'OrderFinalize read-back');
    $transportRead=$pdo->query('SELECT * FROM fiscal_order_transport_details WHERE order_id='.$finalOrder)->fetch();$savedDriver=(int)$pdo->query('SELECT driver_id FROM fiscal_orders WHERE id='.$finalOrder)->fetchColumn();orderHttpAssert(is_array($transportRead)&&$savedDriver===$driverId&&(int)$transportRead['volume_quantity']===2&&(string)$transportRead['gross_weight']==='12.500'&&(string)$transportRead['net_weight']==='11.800','OrderDriverPersistenceTest / OrderVolumePersistenceTest / OrderWeightPersistenceTest');
    $finalReopen=orderHttp($base.'?page=pedidos&tab=saida&order_id='.$finalOrder,$sessionId);orderHttpAssert($finalReopen['status']===200&&preg_match('/<option value="'.$driverId.'" selected>/', $finalReopen['body'])===1,'OrderDriverReopenTest');
    $finalize=['fiscal_action'=>'finalize','csrf_token'=>$csrf,'tipo'=>'saida','order_id'=>(string)$finalOrder,'establishment_id'=>'5','cliente_id'=>(string)$customer,'transportadora_id'=>'','vendedor_id'=>'','fornecedor_id'=>'','motorista_id'=>(string)$driverId,'fiscal_model'=>'55','cfop_id'=>(string)$cfop['id'],'operation_nature'=>'POST_NAO_CONFIAVEL','purpose'=>'NORMAL','presence_indicator'=>'1','data_venda'=>date('Y-m-d'),'codigo_interno'=>$finalCode,'payment_method'=>'01','idempotency_key'=>hash('sha256',$finalCode),'freight_mode'=>'0','vehicle_plate'=>'ABC1D23','vehicle_state'=>'SP','vehicle_rntc'=>'TEST066','volume_quantity'=>'2','volume_species'=>'CAIXA','volume_brand'=>'TEST_ONLY','volume_numbering'=>'1-2','gross_weight'=>'12,500','net_weight'=>'11,800','itens[0][produto_id]'=>(string)$product['id'],'itens[0][quantidade]'=>'2','itens[0][preco_unitario]'=>(string)$product['preco'],'itens[0][desconto]'=>'0'];
    $finalResponse=orderHttp($base.'fiscal_action.php',$sessionId,$finalize,true);$finalJson=json_decode($finalResponse['body'],true);orderHttpAssert($finalResponse['status']===200&&($finalJson['success']??false),'OrderActionNoteTest');$finalDocument=(int)($finalJson['document_id']??0);orderHttpAssert($finalDocument>0&&str_contains((string)($finalJson['notes_url']??''),'page=fiscal_notes')&&str_contains((string)$finalJson['notes_url'],'highlight='.$finalDocument),'OrderActionNoteCentralRedirectTest');
    $snapshot=$pdo->prepare('SELECT recipient_snapshot_json,transport_snapshot_json,totals_json FROM fiscal_documents WHERE id=? AND tenant_id=?');$snapshot->execute([$finalDocument,$tenantId]);$snapshotRow=$snapshot->fetch();$transportSnapshot=is_array($snapshotRow)?json_decode($snapshotRow['transport_snapshot_json'],true):[];$totalsSnapshot=is_array($snapshotRow)?json_decode($snapshotRow['totals_json'],true):[];orderHttpAssert(is_array($snapshotRow)&&((json_decode($snapshotRow['recipient_snapshot_json'],true)['id']??0)==$customer)&&($transportSnapshot['driver']['id']??0)===$driverId&&($transportSnapshot['driver']['nome']??'')===$driverName&&($transportSnapshot['volume']['gross_weight']??'')==='12.500'&&($totalsSnapshot['operation_nature']??'')===$cfop['descricao'],'OrderFinalizeSnapshotTest / customer / driver / volume / validated nature');
    $finalList=orderHttp($base.'?page=pedidos&tab=emitidos&io_q='.urlencode($finalCode),$sessionId);orderHttpAssert($finalList['status']===200&&!str_contains($finalList['body'],'<small>'.$finalCode.'</small>'),'OrderWithDocumentMovesOutOfIssuedOrdersTest');
    $centralList=orderHttp($base.'?page=fiscal_notes&q='.urlencode($finalCode).'&highlight='.$finalDocument,$sessionId);orderHttpAssert($centralList['status']===200&&str_contains($centralList['body'],'Pedido #'.$finalOrder)&&str_contains($centralList['body'],'class="highlight"'),'OrderDocumentMovesToCentralNotesTest / OrderNoteHighlightTest');
    orderHttpAssert(str_contains($centralList['body'],'id="fiscal-center-action-state"')&&str_contains($centralList['body'],'Certificado A1 necessário para transmissão')&&str_contains((string)file_get_contents(__DIR__.'/../public/assets/fiscal-notes.js'),'Prévia DANFE')&&str_contains((string)file_get_contents(__DIR__.'/../public/assets/fiscal-notes.js'),'Emitir / Transmitir'),'FiscalCenterPreviewActionTest / FiscalCenterTransmitDisabledWithoutCertificateTest / FiscalCenterActionMenuStateTest');
    $centerPreview55=orderHttp($base.'fiscal_danfe_preview.php?document_id='.$finalDocument,$sessionId);orderHttpAssert($centerPreview55['status']===200&&str_contains($centerPreview55['headers'],'application/pdf')&&str_starts_with($centerPreview55['body'],'%PDF'),'FiscalCenterPreview55Test / FiscalCenterPreviewWithoutCertificateTest');
    $retryWithoutExplicitCsrf=orderHttp($base.'fiscal_action.php',$sessionId,['fiscal_action'=>'retry','document_id'=>(string)$finalDocument]);orderHttpAssert($retryWithoutExplicitCsrf['status']===422&&(json_decode($retryWithoutExplicitCsrf['body'],true)['error_code']??'')==='CSRF_INVALID','FiscalCenterActionMenuPermissionsTest / retry CSRF');
    $documentItems=(int)$pdo->query('SELECT COUNT(*) FROM fiscal_document_items WHERE fiscal_document_id='.$finalDocument)->fetchColumn();orderHttpAssert($documentItems===1,'OrderFinalize items snapshot');
    $againFinalize=orderHttp($base.'fiscal_action.php',$sessionId,$finalize,true);$againFinalizeJson=json_decode($againFinalize['body'],true);orderHttpAssert(($againFinalizeJson['document_id']??0)===$finalDocument,'OrderActionNoteIdempotencyTest');
    orderHttpAssert((int)$pdo->query('SELECT COUNT(*) FROM fiscal_number_reservations WHERE fiscal_document_id='.$finalDocument)->fetchColumn()===0,'finalize reserves no number');
    $danfe55=orderHttp($base.'fiscal_danfe_preview.php?order_id='.$finalOrder,$sessionId);orderHttpAssert($danfe55['status']===200&&str_contains($danfe55['headers'],'application/pdf')&&str_starts_with($danfe55['body'],'%PDF'),'OrderFinalizeDanfe55Test');
    $protected=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'delete','order_id'=>$finalOrder]);$protectedJson=json_decode($protected['body'],true);orderHttpAssert($protected['status']===422&&($protectedJson['error_code']??'')==='ORDER_HAS_FISCAL_DOCUMENT','finalized order deletion protected');
    $model65Payload=$finalPayload;$model65Payload['order_id']=(string)$finalOrder;$model65Payload['fiscal_model']='65';$model65Save=orderHttp($base.'?page=pedidos&tab=saida&order_id='.$finalOrder,$sessionId,$model65Payload);orderHttpAssert($model65Save['status']===302,'edit model 65');
    $danfce65=orderHttp($base.'fiscal_danfe_preview.php?order_id='.$finalOrder,$sessionId);orderHttpAssert($danfce65['status']===200&&str_contains($danfce65['headers'],'application/pdf')&&str_starts_with($danfce65['body'],'%PDF'),'OrderFinalizeDanfce65RegressionTest');
    $centerDanfce65=orderHttp($base.'fiscal_danfe_preview.php?document_id='.$finalDocument,$sessionId);orderHttpAssert($centerDanfce65['status']===200&&str_contains($centerDanfce65['headers'],'application/pdf')&&str_starts_with($centerDanfce65['body'],'%PDF'),'FiscalCenterPreview65Test');
    $repository=new FiscalOperationRepository($pdo,$tenantId); $fiscalHeader=$payload; $fiscalHeader['codigo_interno']=$code.'_FISCAL'; unset($fiscalHeader['action'],$fiscalHeader['csrf_token'],$fiscalHeader['itens']);
    $fiscalOrder=$repository->createOrder($fiscalHeader,$payload['itens'],$userId);
    $insert=$pdo->prepare("INSERT INTO fiscal_documents(tenant_id,source_order_id,document_version,idempotency_key,status,pending_json,issuer_snapshot_json,recipient_snapshot_json,payment_snapshot_json,transport_snapshot_json,totals_json,created_by) VALUES(?,?,1,?,'FISCAL_PENDING','[]','{}','{}','{}','{}','{}',?)"); $insert->execute([$tenantId,$fiscalOrder,hash('sha256',$code.'_FISCAL'),$userId]);
    $blocked=orderHttp($base.'issued_order_action.php',$sessionId,['csrf'=>$csrf,'order_action'=>'delete','order_id'=>$fiscalOrder]); $blockedJson=json_decode($blocked['body'],true);
    orderHttpAssert($blocked['status']===422&&($blockedJson['error_code']??'')==='ORDER_HAS_FISCAL_DOCUMENT'&&(int)$pdo->query('SELECT COUNT(*) FROM fiscal_orders WHERE id='.$fiscalOrder)->fetchColumn()===1,'OrderDeleteWithFiscalDocumentBlockedTest');
    $rollbackCode=$code.'_ROLLBACK'; $rollbackHeader=$fiscalHeader; $rollbackHeader['codigo_interno']=$rollbackCode;
    try{$repository->createOrder($rollbackHeader,[...$payload['itens'],['produto_id'=>999999999,'quantidade'=>'1','preco_unitario'=>'1']],$userId);throw new RuntimeException('invalid item accepted');}catch(RuntimeException $error){orderHttpAssert($error->getMessage()!=='invalid item accepted','OrderCreateTransactionRollbackTest');}
    $rollbackQuery=$pdo->prepare('SELECT COUNT(*) FROM fiscal_orders WHERE tenant_id=? AND internal_code=?');$rollbackQuery->execute([$tenantId,$rollbackCode]);orderHttpAssert((int)$rollbackQuery->fetchColumn()===0,'rollback left no header');
    $success=true;
} finally {
    $ids=$pdo->prepare("SELECT id FROM fiscal_orders WHERE tenant_id=? AND internal_code LIKE 'TEST_ONLY_HTTP_%'"); $ids->execute([$tenantId]); $testIds=array_map('intval',$ids->fetchAll(PDO::FETCH_COLUMN));
    foreach($testIds as$id){$pdo->prepare('DELETE FROM fiscal_document_items WHERE fiscal_document_id IN (SELECT id FROM fiscal_documents WHERE source_order_id=? AND tenant_id=?)')->execute([$id,$tenantId]);$pdo->prepare('DELETE FROM fiscal_documents WHERE source_order_id=? AND tenant_id=?')->execute([$id,$tenantId]);$pdo->prepare('DELETE FROM fiscal_order_items WHERE order_id=?')->execute([$id]);$pdo->prepare('DELETE FROM fiscal_orders WHERE id=? AND tenant_id=?')->execute([$id,$tenantId]);}
    if($driverId>0)$pdo->prepare('DELETE FROM motoristas WHERE id=?')->execute([$driverId]);
    session_id($sessionId); @session_start(); $_SESSION=[]; session_destroy();
}
if($success)echo "OrderCrudHttp OK created_deleted={$orderId} finalized=".($finalOrder??0)." (form POST, create, read-back, listing, reopen, finalize, DANFE, CSRF, delete, double click; cleanup)\n";
