<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/../app/Repository.php';require __DIR__.'/helpers/ExistingTenantFixture.php';
use MiniErp\Services\BrazilianDocumentValidator;use MiniErp\Services\PeoplePersistenceService;
function cpf50assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function cpf50(int$seed):string{$base=str_pad((string)$seed,9,'0',STR_PAD_LEFT);for($digit=9;$digit<11;$digit++){$sum=0;for($i=0;$i<$digit;$i++)$sum+=(int)$base[$i]*(($digit+1)-$i);$check=(10*$sum)%11;$base.=$check===10?'0':(string)$check;}return$base;}
$valid=[];for($i=1;$i<=100;$i++)$valid[]=cpf50($i);foreach($valid as$cpf)cpf50assert(BrazilianDocumentValidator::cpf($cpf),'PHP valid vector '.$cpf);$leading=$valid[0];cpf50assert($leading[0]==='0'&&BrazilianDocumentValidator::cpf($leading),'leading zero');cpf50assert(BrazilianDocumentValidator::normalizeCpf(substr($leading,0,3).'.'.substr($leading,3,3).'.'.substr($leading,6,3).'-'.substr($leading,9))===$leading,'masked normalization');foreach(['123','11111111111','12345678910','00000000000']as$invalid)cpf50assert(!BrazilianDocumentValidator::cpf($invalid),'invalid rejected '.$invalid);
$asset=realpath(__DIR__.'/../public/assets/cpf-validator.js');$nodeCode='require(process.argv[1]);const values=JSON.parse(Buffer.from(process.argv[2],"base64").toString());process.stdout.write(JSON.stringify(values.map(v=>globalThis.MiniErpCpfValidator.isValid(v))));';$command=['node','-e',$nodeCode,$asset,base64_encode(json_encode([...$valid,'123','11111111111','12345678910','00000000000'],JSON_THROW_ON_ERROR))];$pipes=[];$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($process))throw new RuntimeException('Node unavailable');$jsOut=stream_get_contents($pipes[1]);$jsError=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);cpf50assert($exit===0,'JS validator execution '.$jsError);$jsResults=json_decode($jsOut,true,flags:JSON_THROW_ON_ERROR);foreach($jsResults as$i=>$result)cpf50assert($result===($i<100),'JS/PHP parity index '.$i);
[$tenant]=existingTenantPair();$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$tenant['db']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);if(session_status()!==PHP_SESSION_ACTIVE)session_start();$_SESSION['erp_tenant_id']=$tenant['id'];$_SESSION['erp_user_id']=1;$_SESSION['tenant_id']=$tenant['id'];$_SESSION['user_id']=1;$repo=new Repository($pdo,false);$service=new PeoplePersistenceService($pdo,$repo,$tenant['id']);$cpf=$valid[50];$cpf2=$valid[51];$ids=[];$payload=['person_type'=>'PF','cpf_cnpj'=>$cpf,'nome'=>'PF CPF50 TEST_ONLY','status'=>'ativo','tipo_pessoa'=>['cliente'],'email'=>'cpf50@example.invalid','fone_principal'=>'41999990050','cep'=>'80010000','logradouro'=>'RUA CPF50','numero'=>'50','bairro'=>'CENTRO','municipio'=>'CURITIBA','uf'=>'PR','codigo_ibge'=>'4106902','state_registration_indicator'=>'9'];
try{$attempts=0;foreach(['12345678910','11111111111']as$bad)try{$service->saveClient(array_replace($payload,['cpf_cnpj'=>$bad]));cpf50assert(false,'invalid attempt accepted');}catch(InvalidArgumentException){$attempts++;}cpf50assert($attempts===2,'two recoverable errors');$created=$service->saveClient($payload);$id=$created['person_id'];$ids[]=$id;$read=(new Repository($pdo,false))->findCliente($id);cpf50assert($read&&$read['cpf_cnpj']===$cpf,'CREATE/read-back');$service->saveClient(array_replace($payload,['id'=>$id,'nome'=>'PF CPF50 UPDATED','cpf_cnpj'=>$cpf]));cpf50assert($repo->findCliente($id)['nome']==='PF CPF50 UPDATED','self CPF update');$service->saveClient(array_replace($payload,['id'=>$id,'cpf_cnpj'=>$cpf2,'nome'=>'PF CPF50 CHANGED']));cpf50assert($repo->findCliente($id)['cpf_cnpj']===$cpf2,'change valid CPF');$other=$service->saveClient(array_replace($payload,['cpf_cnpj'=>$cpf,'nome'=>'PF CPF50 OTHER','email'=>'cpf50-other@example.invalid']));$ids[]=$other['person_id'];try{$service->saveClient(array_replace($payload,['id'=>$id,'cpf_cnpj'=>$cpf]));cpf50assert(false,'duplicate CPF accepted');}catch(InvalidArgumentException){}echo "PeopleCpfBugfixTest OK parity=104 create/update/retry/leading-zero/duplicate\n";}finally{if($ids){$pdo->prepare('DELETE FROM clientes WHERE id IN ('.implode(',',array_fill(0,count($ids),'?')).')')->execute($ids);}}
