<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/../app/Repository.php';require __DIR__.'/helpers/ExistingTenantFixture.php';
use MiniErp\Repositories\MasterDataDirectoryRepository;use MiniErp\Services\PeoplePersistenceService;
function persistence49(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function cpf49(string$base):string{for($digit=9;$digit<11;$digit++){$sum=0;for($i=0;$i<$digit;$i++)$sum+=(int)$base[$i]*(($digit+1)-$i);$check=(10*$sum)%11;$base.=$check===10?'0':(string)$check;}return$base;}
function cnpj49(string$base):string{foreach([12,13]as$length){$sum=0;$weight=$length-7;for($i=0;$i<$length;$i++){$sum+=(int)$base[$i]*$weight--;if($weight<2)$weight=9;}$base.=(string)($sum%11<2?0:11-($sum%11));}return$base;}
[$tenant]=existingTenantPair();$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$tenant['db']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);if(session_status()!==PHP_SESSION_ACTIVE)session_start();$_SESSION['erp_tenant_id']=$tenant['id'];$_SESSION['erp_user_id']=1;$_SESSION['tenant_id']=$tenant['id'];$_SESSION['user_id']=1;$repository=new Repository($pdo,false);$service=new PeoplePersistenceService($pdo,$repository,$tenant['id']);$directory=new MasterDataDirectoryRepository($pdo,$tenant['id']);
$stamp=substr((string)hrtime(true),-8);$pfDoc=cpf49('731'.substr($stamp,0,6));$pjDoc=cnpj49('83'.substr($stamp,0,8).'01');$otherDoc=cpf49('642'.substr(strrev($stamp),0,6));$ids=[];
$base=['person_type'=>'PF','cpf_cnpj'=>$pfDoc,'nome'=>'PF CREATE TEST_ONLY '.$stamp,'nome_fantasia'=>'','status'=>'ativo','tipo_pessoa'=>['cliente'],'nome_contato'=>'CONTATO CREATE','email'=>'pf-'.$stamp.'@example.invalid','fone_principal'=>'41999990001','fone_2'=>'4133334444','fone_3'=>'41988887777','cep'=>'80010000','logradouro'=>'RUA CREATE TEST_ONLY','numero'=>'10','complemento'=>'SALA 1','bairro'=>'CENTRO','municipio'=>'CURITIBA','uf'=>'PR','codigo_ibge'=>'4106902','state_registration_indicator'=>'9','inscricao_estadual'=>'','im'=>'','suprama'=>'','limite_credito'=>'100.50','forma_pagamento'=>'PIX'];
try{
 $created=$service->saveClient($base);$id=$created['person_id'];$ids[]=$id;persistence49($created['created']&&$id>0,'CREATE');$read=$repository->findCliente($id);persistence49($read&&$read['nome']===$base['nome']&&$read['cpf_cnpj']===$pfDoc,'CREATE read-back');
 $update=$base+['id'=>$id];$update=array_replace($update,['person_type'=>'PJ','cpf_cnpj'=>$pjDoc,'nome'=>'PJ UPDATE TEST_ONLY '.$stamp,'nome_fantasia'=>'BRASILAPI TEST_ONLY','tipo_pessoa'=>['cliente','fornecedor'],'nome_contato'=>'CONTATO UPDATE','email'=>'pj-'.$stamp.'@example.invalid','fone_principal'=>'41999990002','fone_2'=>'4133335555','fone_3'=>'41988886666','cep'=>'01001000','logradouro'=>'PRACA BRASILAPI TEST_ONLY','numero'=>'49','complemento'=>'ANDAR 2','bairro'=>'SE','municipio'=>'SAO PAULO','uf'=>'SP','codigo_ibge'=>'3550308','state_registration_indicator'=>'1','inscricao_estadual'=>'110042490114','im'=>'IM49','suprama'=>'SUFRAMA49','limite_credito'=>'999.90','forma_pagamento'=>'BOLETO']);$saved=$service->saveClient($update);persistence49(!$saved['created']&&$saved['person_id']===$id,'UPDATE same person');
 $read=null;$repositoryReload=new Repository($pdo,false);$read=$repositoryReload->findCliente($id);foreach(['nome'=>'PJ UPDATE TEST_ONLY '.$stamp,'nome_fantasia'=>'BRASILAPI TEST_ONLY','email'=>'pj-'.$stamp.'@example.invalid','fone_principal'=>'41999990002','fone_2'=>'4133335555','fone_3'=>'41988886666','cep'=>'01001000','logradouro'=>'PRACA BRASILAPI TEST_ONLY','numero'=>'49','complemento'=>'ANDAR 2','bairro'=>'SE','municipio'=>'SAO PAULO','uf'=>'SP','codigo_ibge'=>'3550308','inscricao_estadual'=>'110042490114','im'=>'IM49','suprama'=>'SUFRAMA49','forma_pagamento'=>'BOLETO']as$field=>$expected)persistence49((string)$read[$field]===$expected,'read-back '.$field);persistence49((float)$read['limite_credito']===999.9,'financial read-back');persistence49((int)$read['role_customer']===1&&(int)$read['role_supplier']===1&&str_contains((string)$read['tipo_pessoa'],'fornecedor'),'multi-role');
 $before=(int)$pdo->query('SELECT COUNT(*) FROM clientes WHERE id='.(int)$id)->fetchColumn();for($i=1;$i<=10;$i++){$update['nome']='UPDATE '.$i.' TEST_ONLY '.$stamp;$update['numero']=(string)(49+$i);$service->saveClient($update);}$after=(int)$pdo->query('SELECT COUNT(*) FROM clientes WHERE id='.(int)$id)->fetchColumn();persistence49($before===1&&$after===1&&$repositoryReload->findCliente($id)['nome']==='UPDATE 10 TEST_ONLY '.$stamp,'10 updates without duplicate');
 $self=$service->saveClient($update);persistence49($self['person_id']===$id,'self document update');$other=$service->saveClient(array_replace($base,['cpf_cnpj'=>$otherDoc,'nome'=>'OTHER TEST_ONLY '.$stamp,'email'=>'other-'.$stamp.'@example.invalid']));$ids[]=$other['person_id'];try{$service->saveClient(array_replace($update,['cpf_cnpj'=>$otherDoc]));persistence49(false,'duplicate document accepted');}catch(InvalidArgumentException){}
 $update['tipo_pessoa']=['cliente'];$service->saveClient($update);$roles=$repositoryReload->findCliente($id);persistence49((int)$roles['role_customer']===1&&(int)$roles['role_supplier']===0,'remove supplier preserves customer');
 $nameBefore=$roles['nome'];try{$service->saveClient(array_replace($update,['nome'=>'MUST ROLLBACK','fone_principal'=>'123']));persistence49(false,'invalid update accepted');}catch(InvalidArgumentException){}persistence49($repositoryReload->findCliente($id)['nome']===$nameBefore,'rollback/no partial update');
 try{$service->saveClient(array_replace($update,['id'=>PHP_INT_MAX]));persistence49(false,'IDOR/nonexistent id accepted');}catch(RuntimeException$e){persistence49($e->getMessage()==='RECORD_NOT_FOUND','safe IDOR result');}
 $listed=$directory->people(['q'=>'UPDATE 10 TEST_ONLY '.$stamp],1,25);persistence49($listed['total']===1&&(int)$listed['rows'][0]['source_id']===$id,'list read-back');
 echo "PeoplePersistenceEndToEndTest OK tenant={$tenant['id']} create/update/multitab/read-back/list/10-updates/duplicate/self/rollback\n";
}finally{if($ids){$marks=implode(',',array_fill(0,count($ids),'?'));$pdo->prepare("DELETE FROM clientes WHERE id IN ($marks)")->execute($ids);}}
