<?php

declare(strict_types=1);

require_once __DIR__ . '/../src/Context/AuthenticatedPlatformAdmin.php';
require_once __DIR__ . '/../src/Contracts/PlatformAdminAuthorizerContract.php';
require_once __DIR__ . '/../src/Contracts/PlatformTenantRepositoryContract.php';
require_once __DIR__ . '/../src/Authorization/ConfiguredPlatformAdminAuthorizer.php';
require_once __DIR__ . '/../src/Services/PlatformTenantData.php';
require_once __DIR__ . '/../src/Services/CreatePlatformTenantService.php';
require_once __DIR__ . '/../src/Services/UpdatePlatformTenantService.php';

use MiniErp\Authorization\ConfiguredPlatformAdminAuthorizer;
use MiniErp\Context\AuthenticatedPlatformAdmin;
use MiniErp\Contracts\PlatformTenantRepositoryContract;
use MiniErp\Services\CreatePlatformTenantService;
use MiniErp\Services\PlatformTenantData;
use MiniErp\Services\UpdatePlatformTenantService;

function tenantAssert(bool $condition, string $message): void
{
    if (!$condition) {
        fwrite(STDERR, "ASSERTION FAILED: {$message}\n");
        exit(1);
    }
}

final class InMemoryPlatformTenantRepository implements PlatformTenantRepositoryContract
{
    private array $rows = [];
    private int $nextId = 1;

    public function slugExists(string $slug, ?int $exceptTenantId = null): bool
    {
        foreach ($this->rows as $id => $row) {
            if ($row['slug'] === $slug && $id !== $exceptTenantId) return true;
        }
        return false;
    }

    public function cnpjExists(string $cnpj, ?int $exceptTenantId = null): bool
    {
        foreach ($this->rows as $id => $row) {
            if ($row['cnpj'] === $cnpj && $id !== $exceptTenantId) return true;
        }
        return false;
    }

    public function create(array $data): array
    {
        $id = $this->nextId++;
        $this->rows[$id] = array_merge($data, [
            'tenant_id' => $id,
            'status' => 'cadastrada',
            'blocked' => 0,
            'db_name' => null,
        ]);
        return $this->rows[$id];
    }

    public function update(int $tenantId, array $data): array
    {
        $this->rows[$tenantId] = array_merge($this->rows[$tenantId], $data);
        return $this->rows[$tenantId];
    }

    public function findById(int $tenantId): ?array
    {
        return $this->rows[$tenantId] ?? null;
    }

    public function beginProvisioning(int $tenantId): bool
    {
        if (!isset($this->rows[$tenantId]) || $this->rows[$tenantId]['status'] !== 'cadastrada') return false;
        $this->rows[$tenantId]['status'] = 'provisionando';
        return true;
    }

    public function supportsSchemaVersion(): bool
    {
        return true;
    }

    public function completeProvisioning(int $tenantId, string $databaseName, string $schemaVersion): bool
    {
        if (!isset($this->rows[$tenantId]) || $this->rows[$tenantId]['status'] !== 'provisionando') return false;
        $this->rows[$tenantId]['status'] = 'ativa';
        $this->rows[$tenantId]['db_name'] = $databaseName;
        $this->rows[$tenantId]['schema_version'] = $schemaVersion;
        return true;
    }
}

$repository = new InMemoryPlatformTenantRepository();
$actor = new AuthenticatedPlatformAdmin(10, 'platform@example.test', 'Platform Admin');
$authorized = new ConfiguredPlatformAdminAuthorizer([10]);
$create = new CreatePlatformTenantService($repository, $authorized);
$update = new UpdatePlatformTenantService($repository, $authorized);

$_SESSION['tenant_id'] = 71;
$_SESSION['current_company_id'] = 81;

$created = $create->create($actor, PlatformTenantData::fromArray([
    'tenant_id' => 999,
    'company_id' => 999,
    'db_name' => 'mini_erp_tenant_999',
    'razao_social' => 'Empresa Árvore Ltda',
    'nome_fantasia' => 'Árvore Azul',
    'cnpj' => '12.345.678/0001-90',
    'slug' => '',
]));

tenantAssert($created['tenant_id'] === 1, 'tenant id is generated by persistence, not UI');
tenantAssert($created['slug'] === 'arvore-azul', 'slug is normalized in the backend');
tenantAssert($created['cnpj'] === '12345678000190', 'CNPJ is normalized in the backend');
tenantAssert($created['status'] === 'cadastrada', 'new tenant starts registered and awaiting provisioning');
tenantAssert($created['db_name'] === null, 'create service does not accept db_name from UI');
tenantAssert(!isset($created['company_id']), 'company_id is not introduced by the new flow');

$updated = $update->update($actor, 1, PlatformTenantData::fromArray([
    'tenant_id' => 500,
    'db_name' => 'forbidden',
    'status' => 'ativo',
    'blocked' => 1,
    'razao_social' => 'Empresa Arvore Atualizada Ltda',
    'nome_fantasia' => 'Arvore Atualizada',
    'cnpj' => '12.345.678/0001-90',
    'slug' => 'Arvore Atualizada',
]));

tenantAssert($updated['tenant_id'] === 1, 'update cannot alter tenant_id');
tenantAssert($updated['db_name'] === null, 'update cannot alter db_name');
tenantAssert($updated['status'] === 'cadastrada', 'update cannot alter lifecycle status');
tenantAssert($updated['blocked'] === 0, 'update cannot alter blocked state');
tenantAssert($updated['slug'] === 'arvore-atualizada', 'valid administrative edit is applied');

foreach ([
    ['razao_social' => '', 'nome_fantasia' => 'X', 'cnpj' => '12345678000190'],
    ['razao_social' => 'X', 'nome_fantasia' => 'X', 'cnpj' => '123'],
] as $invalidPayload) {
    try {
        PlatformTenantData::fromArray($invalidPayload);
        tenantAssert(false, 'invalid payload must fail');
    } catch (InvalidArgumentException) {
        // expected
    }
}

try {
    $create->create($actor, new PlatformTenantData('Outra Ltda', 'Outra', '12345678000190', 'outra'));
    tenantAssert(false, 'duplicate CNPJ must fail');
} catch (DomainException) {
    // expected
}

try {
    $create->create($actor, new PlatformTenantData('Outra Ltda', 'Outra', '98765432000199', 'arvore-atualizada'));
    tenantAssert(false, 'duplicate slug must fail');
} catch (DomainException) {
    // expected
}

try {
    $update->update($actor, 999, new PlatformTenantData('Missing Ltda', 'Missing', '98765432000199', 'missing'));
    tenantAssert(false, 'editing missing tenant must fail');
} catch (DomainException) {
    // expected
}

$unauthorizedCreate = new CreatePlatformTenantService($repository, new ConfiguredPlatformAdminAuthorizer([]));
try {
    $unauthorizedCreate->create($actor, new PlatformTenantData('Denied Ltda', 'Denied', '98765432000199', 'denied'));
    tenantAssert(false, 'missing PlatformAdmin authorization must fail');
} catch (DomainException) {
    // expected
}

tenantAssert($_SESSION['tenant_id'] === 71, 'tenant_id session remains unchanged');
tenantAssert($_SESSION['current_company_id'] === 81, 'current_company_id session remains unchanged');

echo "PlatformTenantServices OK\n";
