<?php
declare(strict_types=1);
if(getenv('RUN_FISCAL_MARIADB_TESTS')!=='1'){echo"SefazStatusServiceTest SKIPPED\n";exit;}
require __DIR__.'/../vendor/autoload.php';require __DIR__.'/helpers/FiscalPipelineTestSupport.php';
use MiniErp\Contracts\{OperationalCertificateLoaderContract,SefazStatusClientContract};use MiniErp\Repositories\FiscalConfigurationRepository;use MiniErp\Services\{SefazStatusResponseParser,SefazStatusService};
final class FakeStatusCertificate implements OperationalCertificateLoaderContract{public int$calls=0;public function __construct(private ?string$error=null){}public function load(int$establishmentId,string$expectedTaxId):array{$this->calls++;if($this->error)throw new RuntimeException($this->error);return['certificate'=>(object)['test'=>true],'certificate_id'=>99];}}
final class FakeStatusClient implements SefazStatusClientContract{public int$calls=0;public function __construct(private string|Throwable$response){}public function status(string$configJson,object$certificate,string$uf,int$timeoutSeconds):string{$this->calls++;$cfg=json_decode($configJson,true);fiscal_assert($cfg['tpAmb']===2&&$cfg['siglaUF']==='SP'&&$cfg['versao']==='4.00','Tools config');if($this->response instanceof Throwable)throw$this->response;return$this->response;}}
function statusXml(string$c,string$m):string{return'<?xml version="1.0"?><retConsStatServ xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>2</tpAmb><verAplic>TEST</verAplic><cStat>'.$c.'</cStat><xMotivo>'.$m.'</xMotivo><cUF>35</cUF><dhRecbto>2026-08-24T12:00:00-03:00</dhRecbto></retConsStatServ>';}
[$server,$pdo,$db]=fiscal_test_db();$tenant=928001;$est=['id'=>1,'tenant_id'=>$tenant,'tax_id'=>'12345678000195','legal_name'=>'SEFAZ TEST','state_registration'=>'123','tax_regime_code'=>'1','street'=>'Rua A','number'=>'1','district'=>'Centro','city_ibge_code'=>'3550308','city_name'=>'Sao Paulo','state'=>'SP','postal_code'=>'01001000'];
try{$pdo->exec("INSERT INTO fiscal_series(tenant_id,establishment_id,model,series,next_number,environment,emission_type,process_version,active)VALUES($tenant,1,'55',1,1,2,1,'TEST',1)");$repo=new FiscalConfigurationRepository($pdo,$tenant);
 foreach([['107','Servico em Operacao',true,null],['108','Paralisacao momentanea',false,'SEFAZ_SERVICE_UNAVAILABLE'],['109','Paralisacao sem previsao',false,'SEFAZ_SERVICE_UNAVAILABLE']]as[$code,$reason,$ok,$error]){$pdo->exec('DELETE FROM fiscal_certificate_audit');$client=new FakeStatusClient(statusXml($code,$reason));$result=(new SefazStatusService($repo,new FakeStatusCertificate(),$client,new SefazStatusResponseParser(),1))->execute($tenant,$est,2,7);fiscal_assert($result->success===$ok&&$result->cStat===$code&&$result->errorCode===$error,"fake $code");}
 foreach([[new RuntimeException('operation timed out'),'SEFAZ_TIMEOUT'],[new RuntimeException('SSL certificate problem'),'SEFAZ_TLS_ERROR'],[new RuntimeException('Could not resolve host'),'SEFAZ_DNS_ERROR'],['<invalid','SEFAZ_INVALID_RESPONSE']]as[$response,$expected]){$pdo->exec('DELETE FROM fiscal_certificate_audit');try{(new SefazStatusService($repo,new FakeStatusCertificate(),new FakeStatusClient($response),new SefazStatusResponseParser(),1))->execute($tenant,$est,2,7);throw new RuntimeException('expected '.$expected);}catch(RuntimeException$e){fiscal_assert($e->getMessage()===$expected,"fake $expected");}}
 $pdo->exec('DELETE FROM fiscal_certificate_audit');$noCert=new FakeStatusCertificate('CERTIFICATE_NOT_READY');$network=new FakeStatusClient(statusXml('107','OK'));try{(new SefazStatusService($repo,$noCert,$network))->execute($tenant,$est,2,7);throw new RuntimeException('no cert');}catch(RuntimeException$e){fiscal_assert($e->getMessage()==='SEFAZ_CERTIFICATE_ERROR'&&$network->calls===0,'no certificate = no network');}
 foreach([['CERTIFICATE_EXPIRED','SEFAZ_CERTIFICATE_EXPIRED'],['CERTIFICATE_IDENTITY_ERROR','SEFAZ_CERTIFICATE_IDENTITY_ERROR']]as[$source,$expected]){try{(new SefazStatusService($repo,new FakeStatusCertificate($source),$network))->execute($tenant,$est,2,7);throw new RuntimeException('cert guard');}catch(RuntimeException$e){fiscal_assert($e->getMessage()===$expected,'certificate guard');}}
 try{(new SefazStatusService($repo,new FakeStatusCertificate(),$network))->execute($tenant,$est,1,7);throw new RuntimeException('production');}catch(RuntimeException$e){fiscal_assert($e->getMessage()==='SEFAZ_PRODUCTION_BLOCKED','production blocked');}$badUf=$est;$badUf['state']='XX';try{(new SefazStatusService($repo,new FakeStatusCertificate(),$network))->execute($tenant,$badUf,2,7);throw new RuntimeException('uf');}catch(RuntimeException$e){fiscal_assert($e->getMessage()==='SEFAZ_INVALID_UF','invalid UF no network');}
 $pdo->exec('DELETE FROM fiscal_certificate_audit');$service=new SefazStatusService($repo,new FakeStatusCertificate(),new FakeStatusClient(statusXml('107','OK')),new SefazStatusResponseParser(),30);$service->execute($tenant,$est,2,7);try{$service->execute($tenant,$est,2,7);throw new RuntimeException('rate');}catch(RuntimeException$e){fiscal_assert($e->getMessage()==='SEFAZ_RATE_LIMITED','rate limit');}$actions=$pdo->query('SELECT GROUP_CONCAT(action ORDER BY id) FROM fiscal_certificate_audit')->fetchColumn();fiscal_assert(str_contains((string)$actions,'SEFAZ_STATUS_REQUESTED')&&str_contains((string)$actions,'SEFAZ_STATUS_OK'),'audit');echo"SefazStatusServiceTest OK 107/108/109/timeout/TLS/DNS/invalid/cert/production/UF/rate/audit\n";
}finally{fiscal_drop_database($server,$db);}
