<?php
declare(strict_types=1);
foreach(['Contracts/TaxRuleRepositoryContract.php','Fiscal/FiscalTaxContext.php','Fiscal/FiscalTaxRule.php','Fiscal/FiscalTaxResolution.php','Fiscal/InMemoryTaxRuleRepository.php','Fiscal/TaxRuleResolver.php','Fiscal/DecimalTaxCalculator.php','Services/PreviewTaxForItemService.php'] as $f)require_once __DIR__.'/../src/'.$f;
use MiniErp\Fiscal\{FiscalTaxContext,FiscalTaxRule,InMemoryTaxRuleRepository,TaxRuleResolver,DecimalTaxCalculator};use MiniErp\Services\PreviewTaxForItemService;
function ta(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}function ctx(array $x=[]):FiscalTaxContext{return new FiscalTaxContext($x['tenant']??14,1,$x['crt']??'3',$x['uf_o']??'PR',$x['uf_d']??'PR','PJ',$x['ie']??'1','1058',$x['ncm']??'TESTNCM',$x['cest']??'',$x['origin']??'0',$x['benefit']??'',$x['direction']??'EXIT',$x['model']??'55','NORMAL',$x['consumer']??false,$x['contributor']??true,'1',new DateTimeImmutable($x['date']??'2026-08-21'),'2.0000','10.00');}function rule(string $code,array $conditions,int $priority=10,string $from='2026-01-01',?string $to=null,int $tenant=14,array $ibs=[]):FiscalTaxRule{return new FiscalTaxRule(random_int(1,999999),$tenant,$code,1,$priority,new DateTimeImmutable($from),$to?new DateTimeImmutable($to):null,'TEST_ONLY SOURCE','v1','2026-01-01',$conditions,'5102',['cst'=>'00','rate'=>'10.00'],['cst'=>'99'],['cst'=>'99'],['cst'=>'99'],$ibs,[], 'ACTIVE','TEST_ONLY');}
$exact=rule('EXACT',['crt'=>'3','ncm'=>'TESTNCM','cest'=>'','tax_benefit_code'=>'','origin_state'=>'PR','destination_state'=>'PR','direction'=>'EXIT','model'=>'55','product_origin'=>'0','final_consumer'=>false,'icms_contributor'=>true]);$resolver=new TaxRuleResolver(new InMemoryTaxRuleRepository([$exact]));$res=$resolver->resolve(ctx());ta($res->ruleCode==='EXACT'&&$res->cfop==='5102','exact and CFOP');ta(in_array('crt',$res->matchedBy,true)&&str_contains($res->explanation,'EXACT'),'explainability');
try{(new TaxRuleResolver(new InMemoryTaxRuleRepository()))->resolve(ctx());throw new RuntimeException('no rule accepted');}catch(RuntimeException $e){ta(str_contains($e->getMessage(),'Não existe'),'fail closed no rule');}
$a=rule('A',['crt'=>'3'],10);$b=rule('B',['ncm'=>'TESTNCM'],10);try{(new TaxRuleResolver(new InMemoryTaxRuleRepository([$a,$b])))->resolve(ctx());throw new RuntimeException('conflict accepted');}catch(RuntimeException $e){ta(str_contains($e->getMessage(),'More than one'),'conflict');}
$priority=rule('PRIORITY',['crt'=>'3'],20);ta((new TaxRuleResolver(new InMemoryTaxRuleRepository([$a,$priority])))->resolve(ctx())->ruleCode==='PRIORITY','priority');$specific=rule('SPECIFIC',['crt'=>'3','ncm'=>'TESTNCM'],10);ta((new TaxRuleResolver(new InMemoryTaxRuleRepository([$a,$specific])))->resolve(ctx())->ruleCode==='SPECIFIC','specificity');
$expired=rule('EXPIRED',['crt'=>'3'],99,'2025-01-01','2025-12-31');ta((new TaxRuleResolver(new InMemoryTaxRuleRepository([$expired,$a])))->resolve(ctx())->ruleCode==='A','expired ignored');foreach([['crt'=>'1'],['uf_d'=>'SC'],['ncm'=>'OTHER'],['direction'=>'ENTRY'],['model'=>'65'],['origin'=>'1'],['consumer'=>true],['contributor'=>false],['cest'=>'999'],['benefit'=>'TEST']] as $change){try{(new TaxRuleResolver(new InMemoryTaxRuleRepository([$exact])))->resolve(ctx($change));throw new RuntimeException('condition accepted');}catch(RuntimeException $e){ta(str_contains($e->getMessage(),'Não existe'),'context mismatch');}}
$ibs=rule('IBS',['crt'=>'3'],30,'2026-01-01',null,14,['cst'=>'000','cClassTrib'=>'TEST_ONLY','rate'=>'1.00']);$preview=(new PreviewTaxForItemService(new TaxRuleResolver(new InMemoryTaxRuleRepository([$ibs])),new DecimalTaxCalculator()))->preview(ctx());ta($preview['resolution']->ibsCbs['cClassTrib']==='TEST_ONLY','IBS/CBS structure');ta($preview['calculation']['item_total']==='20.00'&&$preview['calculation']['taxes']['icms']['amount']==='2.00','decimal calculation');try{(new TaxRuleResolver(new InMemoryTaxRuleRepository([$ibs])))->resolve(ctx(['tenant'=>15]));throw new RuntimeException('cross tenant');}catch(RuntimeException $e){}echo "TaxEngine OK\n";
