<?php
declare(strict_types=1);namespace MiniErp\Services;use MiniErp\Repositories\CompanyFiscalSettingsRepository;use MiniErp\Contracts\SecretStorageContract;
final class CompanyFiscalSettingsService{
 private const CONTEXT=['ENTRY_INTERNAL'=>'1','ENTRY_INTERSTATE'=>'2','EXIT_INTERNAL'=>'5','EXIT_INTERSTATE'=>'6'];
 private const PIS_COFINS=['01','02','03','04','05','06','07','08','09','49','50','51','52','53','54','55','56','60','61','62','63','64','65','66','67','70','71','72','73','74','75','98','99'];private const IPI=['00','01','02','03','04','05','49','50','51','52','53','54','55','99'];
 public function __construct(private CompanyFiscalSettingsRepository$repo,private SecretStorageContract$secrets,private int$tenantId){}
 public function save(int$est,string$group,array$d,int$actor):void{match($group){'general'=>$this->general($est,$d,$actor),'cfop'=>$this->cfop($est,$d,$actor),'cfop_bootstrap'=>$this->bootstrapCfops($est,$actor),'legacy'=>$this->legacy($est,$d,$actor),'rtc'=>$this->rtc($est,$d,$actor),'icms'=>$this->icms($est,$d,$actor),'csc'=>$this->csc($est,$d,$actor),default=>throw new \InvalidArgumentException('Grupo fiscal inválido.')};}
 private function bootstrapCfops(int$e,int$a):void{$result=$this->repo->bootstrapCfopDefaults($e,$a);if($result['missing'])throw new \InvalidArgumentException('CFOP padrão '.implode(', ',$result['missing']).' ainda não cadastrado.');}
 private function general(int$e,array$d,int$a):void{$env=(int)($d['environment']??2);$model=(string)($d['primary_model']??'55');if($env!==2)throw new \InvalidArgumentException('Produção permanece bloqueada até production_ready.');if(!in_array($model,['55','65'],true))throw new \InvalidArgumentException('Modelo inválido.');$this->repo->saveGeneral($e,['environment'=>$env,'primary_model'=>$model,'deduct_icms_from_pis_cofins_base'=>($d['deduct_icms_from_pis_cofins_base']??'0')==='1'?1:0,'default_cst_csosn'=>$this->nullable($d,'default_cst_csosn'),'final_consumer_cst_csosn'=>$this->nullable($d,'final_consumer_cst_csosn'),'default_cbenef'=>$this->nullable($d,'default_cbenef'),'final_consumer_cbenef'=>$this->nullable($d,'final_consumer_cbenef'),'funrural_rate'=>$this->decimal($d,'funrural_rate'),'simple_credit_rate'=>$this->decimal($d,'simple_credit_rate')],$a);}
 private function cfop(int$e,array$d,int$a):void{$v=[];foreach(self::CONTEXT as$c=>$prefix){$x=preg_replace('/\D/','',(string)($d[$c]??''));if(!preg_match('/^'.$prefix.'\d{3}$/',$x))throw new \InvalidArgumentException("CFOP inválido para {$c}.");$v[$c]=$x;}$this->repo->saveCfops($e,$v,$a);}
 private function legacy(int$e,array$d,int$a):void{$out=['ipi_applicability'=>in_array(($d['ipi_applicability']??''),['APPLICABLE','NOT_APPLICABLE','PENDING'],true)?$d['ipi_applicability']:'PENDING','ipi_cenq'=>$this->nullable($d,'ipi_cenq')];foreach(['pis_output','pis_input','cofins_output','cofins_input']as$p){$c=$this->nullable($d,$p.'_cst');if($c!==null&&!in_array($c,self::PIS_COFINS,true))throw new \InvalidArgumentException("CST {$p} inválido.");$out[$p.'_cst']=$c;$out[$p.'_rate']=$this->decimal($d,$p.'_rate');}foreach(['ipi_output','ipi_input']as$p){$c=$this->nullable($d,$p.'_cst');if($c!==null&&!in_array($c,self::IPI,true))throw new \InvalidArgumentException("CST {$p} inválido.");$out[$p.'_cst']=$c;$out[$p.'_rate']=$this->decimal($d,$p.'_rate');}$this->repo->saveLegacy($e,$out,$a);}
 private function rtc(int$e,array$d,int$a):void{$scope=(string)($d['document_scope']??'ALL');if(!in_array($scope,['ALL','55','65'],true))throw new \InvalidArgumentException('Escopo de documento inválido.');$out=['document_scope'=>$scope,'ibs_cbs_cst'=>$this->nullable($d,'ibs_cbs_cst'),'cclass_trib'=>$this->nullable($d,'cclass_trib'),'is_enabled'=>($d['is_enabled']??'0')==='1'?1:0,'is_cst'=>$this->nullable($d,'is_cst'),'is_classification'=>$this->nullable($d,'is_classification'),'is_type'=>in_array(($d['is_type']??''),['NONE','PERCENT','SPECIFIC'],true)?$d['is_type']:'NONE','is_unit'=>$this->nullable($d,'is_unit')];foreach(['ibs_uf_rate','ibs_municipal_rate','cbs_rate','ibs_reduction_rate','cbs_reduction_rate','ibs_deferral_rate','cbs_deferral_rate','is_rate','is_specific_value']as$f)$out[$f]=$this->decimal($d,$f);$this->repo->saveRtc($e,$out,$a);}
 private function icms(int$e,array$d,int$a):void{$uf=strtoupper((string)($d['uf']??''));$ufs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];if(!in_array($uf,$ufs,true))throw new \InvalidArgumentException('UF inválida.');$from=(string)($d['valid_from']??'');$to=$this->nullable($d,'valid_to');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||($to!==null&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)))throw new \InvalidArgumentException('Vigência inválida.');$out=['uf'=>$uf,'valid_from'=>$from,'valid_to'=>$to,'active'=>1,'cst_csosn'=>$this->nullable($d,'cst_csosn')];foreach(['juridica_rate','final_consumer_rate','reduction_rate','deferral_rate','mva_rate','simple_mva_rate','st_rate','st_reduction_rate','internal_rate','fcp_rate']as$f)$out[$f]=$this->decimal($d,$f);$this->repo->saveIcms($e,$out,$a);}
 private function csc(int$e,array$d,int$a):void{$env=(int)($d['csc_environment']??0);$id=trim((string)($d['id_csc']??''));$token=trim((string)($d['csc_token']??''));if(!in_array($env,[1,2],true)||$id===''||$token==='')throw new \InvalidArgumentException('Ambiente, ID CSC e token são obrigatórios.');$ref=$this->secrets->put("tenant-{$this->tenantId}/establishment-{$e}/csc-{$env}",$token);try{$old=$this->repo->saveCsc($e,$env,$id,$ref,substr($token,-4),$a);if($old)$this->secrets->delete($old);}catch(\Throwable$x){$this->secrets->delete($ref);throw$x;}}
 private function decimal(array$d,string$k):?string{$v=trim(str_replace(',','.',(string)($d[$k]??'')));if($v==='')return null;if(!preg_match('/^-?\d{1,9}(?:\.\d{1,6})?$/',$v))throw new \InvalidArgumentException("{$k}: decimal inválido.");$negative=str_starts_with($v,'-');$unsigned=ltrim($v,'-');[$whole,$fraction]=array_pad(explode('.',$unsigned,2),2,'');$whole=ltrim($whole,'0');if($whole==='')$whole='0';return($negative?'-':'').$whole.'.'.str_pad($fraction,6,'0');}private function nullable(array$d,string$k):?string{$v=trim((string)($d[$k]??''));return$v===''?null:$v;}
}
