<?php
declare(strict_types=1);
namespace MiniErp\Services;
use MiniErp\Fiscal\{A1CertificateInspector,LocalEncryptedSecretStorage,OperationalCertificateProvider,PrivateCertificateStorage};use MiniErp\Repositories\FiscalConfigurationRepository;use RuntimeException;use Throwable;
final class EstablishmentFiscalConfigurationService {
 public function __construct(private FiscalConfigurationRepository$repo,private A1CertificateInspector$inspector,private PrivateCertificateStorage$certs,private LocalEncryptedSecretStorage$secrets,private int$tenantId){}
 public function upload(int$est,string$name,string$content,string$password,string$taxId,int$actor):array{$extension=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($extension,['pfx','p12'],true)||$content===''||strlen($content)>5242880)throw new RuntimeException('Arquivo PFX/P12 inválido ou maior que 5 MB.');if($password==='')throw new RuntimeException('Senha do certificado não informada.');$storage=$this->certs->store($this->tenantId,$est,$extension,$content);$secret=null;$persisted=false;try{$secret=$this->secrets->put("tenant-{$this->tenantId}/establishment-{$est}",$password);$storedContent=$this->certs->read($storage);$storedPassword=$this->secrets->get($secret);$m=$this->inspector->inspect($storedContent,$storedPassword,$name,$taxId);$id=$this->repo->storeCertificateCandidate($est,$m,$storage,$secret,$actor);$persisted=true;$provider=new OperationalCertificateProvider($this->inspector,$this->certs,$this->secrets,$this->repo);$readBack=$provider->verifyStored($est,$id,$taxId);if($readBack['operational'])$this->repo->activateStoredCertificate($est,$id,$actor);$m=array_merge($m,$readBack,['certificate_id'=>$id,'storage_reference'=>$storage,'secret_reference'=>$secret,'certificate_ready'=>(bool)$readBack['operational']]);if(!$readBack['operational'])throw new RuntimeException('Certificado armazenado com segurança, porém não ativado. '.$readBack['diagnostic']);}catch(Throwable$e){if(!$persisted){$this->certs->delete($storage);if($secret!==null)$this->secrets->delete($secret);}throw$e;}unset($m['certificate']);return$m;}
 public function test(int$est,string$taxId):array{$row=$this->repo->latestCertificate($est);if(!$row)throw new RuntimeException('Certificado não configurado.');return(new OperationalCertificateProvider($this->inspector,$this->certs,$this->secrets,$this->repo))->verifyStored($est,(int)$row['id'],$taxId);}
 public function deactivate(int$est,int$actor,string$reason):void{$this->repo->deactivateCertificate($est,$actor,$reason);}
}
