<?php
declare(strict_types=1);
namespace MiniErp\Services;
use DOMDocument;use NFePHP\DA\NFe\{Danfe,Danfce};
final class FiscalDocumentPreviewRenderer
{
 public function render(string$model,string$xml):array{$xmlModel=$this->xmlModel($xml);if($model!==$xmlModel)throw new FiscalDanfeException('FISCAL_DOCUMENT_MODEL_MISMATCH','O modelo resolvido diverge do XML da prévia.');try{if($model==='55'){$r=new Danfe($xml);$r->printParameters('P','A4',2,2);return['bytes'=>$r->render(),'renderer'=>Danfe::class,'format'=>'A4','orientation'=>'P'];}if($model==='65'){$r=new Danfce($this->withTechnicalSupplement($xml));$r->setPaperWidth(80);$r->setOffLineDoublePrint(false);return['bytes'=>$r->render(),'renderer'=>Danfce::class,'format'=>'80mm','orientation'=>'P'];}}catch(FiscalDanfeException$e){throw$e;}catch(\Throwable$e){throw new FiscalDanfeException('PREVIEW_RENDER_FAILED','Não foi possível renderizar a prévia fiscal.',$e);}throw new FiscalDanfeException('FISCAL_DOCUMENT_MODEL_UNSUPPORTED','Modelo fiscal não suportado para prévia.');}
 private function xmlModel(string$xml):string{$dom=new DOMDocument();if(!@$dom->loadXML($xml,LIBXML_NONET))throw new FiscalDanfeException('PREVIEW_XML_INVALID','XML técnico da prévia inválido.');$nodes=$dom->getElementsByTagName('mod');if($nodes->length!==1)throw new FiscalDanfeException('PREVIEW_XML_INVALID','XML técnico sem modelo fiscal inequívoco.');$model=trim((string)$nodes->item(0)?->textContent);if(!in_array($model,['55','65'],true))throw new FiscalDanfeException('FISCAL_DOCUMENT_MODEL_UNSUPPORTED','Modelo fiscal não suportado para prévia.');return$model;}
 /** Campos técnicos exigidos pelo renderer compacto; não representam consulta ou autoridade fiscal. */
 private function withTechnicalSupplement(string$xml):string{$dom=new DOMDocument('1.0','UTF-8');$dom->preserveWhiteSpace=false;$dom->loadXML($xml,LIBXML_NONET);if($dom->getElementsByTagName('infNFeSupl')->length===0){$nfe=$dom->getElementsByTagName('NFe')->item(0);$inf=$dom->getElementsByTagName('infNFe')->item(0);$id=$inf?->attributes?->getNamedItem('Id')?->nodeValue??'';$supplement=$dom->createElementNS('http://www.portalfiscal.inf.br/nfe','infNFeSupl');$supplement->appendChild($dom->createElementNS('http://www.portalfiscal.inf.br/nfe','qrCode','urn:minierp:preview:'.hash('sha256',$id)));$supplement->appendChild($dom->createElementNS('http://www.portalfiscal.inf.br/nfe','urlChave','PRÉVIA LOCAL - NÃO CONSULTAR SEFAZ'));$nfe?->appendChild($supplement);}return(string)$dom->saveXML();}
}
