<?php
declare(strict_types=1);
namespace MiniErp\Services;
use MiniErp\Contracts\{OperationalCertificateLoaderContract,SefazStatusClientContract};use MiniErp\Repositories\FiscalConfigurationRepository;use RuntimeException;use Throwable;
final class SefazStatusService{
 private const UFS=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
 public function __construct(private FiscalConfigurationRepository$config,private OperationalCertificateLoaderContract$certificates,private SefazStatusClientContract$client,private SefazStatusResponseParser$parser=new SefazStatusResponseParser(),private int$rateLimitSeconds=15,private int$timeoutSeconds=15){}
 public function execute(int$tenantId,array$establishment,int$environment,int$actorId):SefazStatusResult{
  if($tenantId<1||(int)($establishment['tenant_id']??0)!==$tenantId||(int)($establishment['id']??0)<1)throw new RuntimeException('SEFAZ_TENANT_CONTEXT_ERROR');if($environment!==2)throw new RuntimeException('SEFAZ_PRODUCTION_BLOCKED');
  foreach(['tax_id','legal_name','state_registration','tax_regime_code','street','number','district','city_ibge_code','city_name','state','postal_code']as$field)if(trim((string)($establishment[$field]??''))==='')throw new RuntimeException('SEFAZ_REGISTRATION_INCOMPLETE');
  $uf=strtoupper(trim((string)$establishment['state']));if(!in_array($uf,self::UFS,true))throw new RuntimeException('SEFAZ_INVALID_UF');$taxId=preg_replace('/\D/','',(string)$establishment['tax_id']);if(strlen($taxId)!==14)throw new RuntimeException('SEFAZ_REGISTRATION_INCOMPLETE');
  $seriesReady=false;foreach($this->config->series((int)$establishment['id'])as$series)if((string)$series['model']==='55'&&(int)$series['environment']===2&&(int)$series['active']===1)$seriesReady=true;if(!$seriesReady)throw new RuntimeException('SEFAZ_SERIES_55_NOT_READY');if($this->config->recentSefazRequestCount((int)$establishment['id'],$this->rateLimitSeconds)>0)throw new RuntimeException('SEFAZ_RATE_LIMITED');
  try{$loaded=$this->certificates->load((int)$establishment['id'],$taxId);}catch(Throwable$e){$m=strtoupper($e->getMessage());$code=str_contains($m,'EXPIRED')?'SEFAZ_CERTIFICATE_EXPIRED':(str_contains($m,'IDENTITY')?'SEFAZ_CERTIFICATE_IDENTITY_ERROR':'SEFAZ_CERTIFICATE_ERROR');throw new RuntimeException($code,0,$e);}
  $certificate=$loaded['certificate']??null;$certificateId=(int)($loaded['certificate_id']??0);if(!is_object($certificate)||$certificateId<1)throw new RuntimeException('SEFAZ_CERTIFICATE_ERROR');$details=['uf'=>$uf,'environment'=>2,'service'=>'NFeStatusServico4'];$this->config->auditSefazStatus((int)$establishment['id'],$certificateId,'SEFAZ_STATUS_REQUESTED',$actorId,$details);
  $configJson=json_encode(['atualizacao'=>date('Y-m-d H:i:s'),'tpAmb'=>2,'razaosocial'=>(string)$establishment['legal_name'],'siglaUF'=>$uf,'cnpj'=>$taxId,'schemes'=>'PL_009_V4','versao'=>'4.00'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$started=hrtime(true);
  try{$xml=$this->client->status($configJson,$certificate,$uf,$this->timeoutSeconds);$latency=(int)round((hrtime(true)-$started)/1e6);$parsed=$this->parser->parse($xml);if(($parsed['tpAmb']??'2')!=='2')throw new RuntimeException('SEFAZ_INVALID_RESPONSE');$success=(string)$parsed['cStat']==='107';$result=new SefazStatusResult($success,2,$uf,'NFeStatusServico4',(string)$parsed['cStat'],(string)$parsed['xMotivo'],$parsed['dhRecbto'],date(DATE_ATOM),$latency,'NFePHP_WEBSERVICES_TABLE',$success?null:'SEFAZ_SERVICE_UNAVAILABLE');$this->config->auditSefazStatus((int)$establishment['id'],$certificateId,'SEFAZ_STATUS_OK',$actorId,$result->toArray()+['transport_ok'=>true]);return$result;
  }catch(Throwable$e){$latency=(int)round((hrtime(true)-$started)/1e6);$code=$this->normalizeError($e);$this->config->auditSefazStatus((int)$establishment['id'],$certificateId,'SEFAZ_STATUS_FAILED',$actorId,$details+['error_code'=>$code,'latency_ms'=>$latency]);throw new RuntimeException($code,0,$e);}
 }
 private function normalizeError(Throwable$e):string{$m=strtoupper($e->getMessage());if(str_contains($m,'INVALID_RESPONSE'))return'SEFAZ_INVALID_RESPONSE';if(str_contains($m,'TIMED OUT')||str_contains($m,'TIMEOUT'))return'SEFAZ_TIMEOUT';if(str_contains($m,'RESOLVE HOST')||str_contains($m,'DNS'))return'SEFAZ_DNS_ERROR';if(str_contains($m,'SSL')||str_contains($m,'TLS')||str_contains($m,'CERTIFICATE'))return'SEFAZ_TLS_ERROR';return'SEFAZ_TRANSPORT_ERROR';}
}
