<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>minirp.ico</ApplicationIcon>
    <AssemblyName>MiniRP Servidores</AssemblyName>
    <RootNamespace>MiniRPServidores</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="minirp.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
