<?php
declare(strict_types=1);
use MiniErp\Adapters\{NfePhpSefazStatusClient,OperationalCertificateLoader};use MiniErp\Fiscal\{A1CertificateInspector,FiscalMasterKey,LocalEncryptedSecretStorage,OperationalCertificateProvider,PrivateCertificateStorage};use MiniErp\Infrastructure\TenantConnectionResolver;use MiniErp\Repositories\{FiscalConfigurationRepository,TenantEstablishmentRepository};use MiniErp\Services\{SefazStatusResponseParser,SefazStatusService};
require_once __DIR__.'/_tenant_users.php';header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
try{
 [$identity,,$contextService,$context]=requireTenantUserContext();$tenantId=$context->getSelectedTenantId();$pdo=(new TenantConnectionResolver(__DIR__.'/../../config.php'))->resolveAdministrative($context);$est=(new TenantEstablishmentRepository($pdo))->findPrimaryForTenant($tenantId);if(!$est)throw new RuntimeException('SEFAZ_REGISTRATION_INCOMPLETE');$repo=new FiscalConfigurationRepository($pdo,$tenantId);$provider=new OperationalCertificateProvider(new A1CertificateInspector(),new PrivateCertificateStorage(__DIR__.'/../../storage/fiscal/certificates'),new LocalEncryptedSecretStorage(__DIR__.'/../../storage/fiscal/secrets',FiscalMasterKey::resolve(__DIR__.'/../..')),$repo);$certificateReady=$provider->certificateReady((int)$est['id'],(string)$est['tax_id']);$last=$repo->latestSefazStatus((int)$est['id']);
 if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){echo json_encode(['success'=>true,'certificate_ready'=>$certificateReady,'environment'=>2,'uf'=>$est['state']??null,'last'=>$last?json_decode((string)($last['details_json']??'{}'),true):null,'last_action'=>$last['action']??null,'last_at'=>$last['created_at']??null],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
 requirePlatformUserCsrf();if((int)($_POST['environment']??0)!==2)throw new RuntimeException('SEFAZ_PRODUCTION_BLOCKED');$service=new SefazStatusService($repo,new OperationalCertificateLoader($provider),new NfePhpSefazStatusClient(),new SefazStatusResponseParser());$result=$service->execute($tenantId,$est,2,$identity->getUserId());echo json_encode(['success'=>true,'data'=>$result->toArray()],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
}catch(Throwable$e){$code=preg_match('/^SEFAZ_[A-Z0-9_]+$/',$e->getMessage())?$e->getMessage():'SEFAZ_STATUS_FAILED';http_response_code(in_array($code,['SEFAZ_PRODUCTION_BLOCKED','SEFAZ_RATE_LIMITED'],true)?429:422);$message=match($code){'SEFAZ_PRODUCTION_BLOCKED'=>'Produção bloqueada: somente homologação.','SEFAZ_RATE_LIMITED'=>'Aguarde antes de testar novamente.','SEFAZ_CERTIFICATE_ERROR'=>'Certificado operacional indisponível.','SEFAZ_CERTIFICATE_EXPIRED'=>'Certificado expirado.','SEFAZ_CERTIFICATE_IDENTITY_ERROR'=>'O certificado não pertence ao estabelecimento.','SEFAZ_TIMEOUT'=>'Tempo limite da comunicação excedido.','SEFAZ_TLS_ERROR'=>'Falha TLS na comunicação segura.','SEFAZ_DNS_ERROR'=>'Falha de resolução DNS.','SEFAZ_INVALID_RESPONSE'=>'Resposta SEFAZ inválida.',default=>'Não foi possível testar a comunicação SEFAZ.'};echo json_encode(['success'=>false,'error_code'=>$code,'error_message'=>$message],JSON_UNESCAPED_UNICODE);}
