<?php
declare(strict_types=1);
use MiniErp\Repositories\{PlatformAdminRepository,TenantAccessPolicyRepository};
require_once __DIR__.'/_context.php';require_once __DIR__.'/_layout.php';
[$main,,,$identity]=requireAuthorizedPlatformContext();$policies=new TenantAccessPolicyRepository($main);$audit=new PlatformAdminRepository($main);
$_SESSION['platform_audit_csrf']??=bin2hex(random_bytes(32));$message='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){try{if($identity->getRole()!=='SUPER_ADMIN')throw new RuntimeException('Somente SUPER_ADMIN pode alterar controles.');if(!hash_equals((string)$_SESSION['platform_audit_csrf'],(string)($_POST['csrf_token']??'')))throw new RuntimeException('Sessão expirada.');$tenantId=(int)($_POST['tenant_id']??0);$days=($_POST['days']??'')===''?null:(int)$_POST['days'];$policyId=$policies->apply($tenantId,(string)($_POST['access_mode']??''),!empty($_POST['can_issue_fiscal']),!empty($_POST['can_manage_users']),!empty($_POST['can_use_financial']),$days,(string)($_POST['reason']??''),$identity->getUserId());$audit->audit($identity->getUserId(),'TENANT_ACCESS_POLICY_CHANGED','tenant',(string)$tenantId,$_SERVER['REMOTE_ADDR']??null,['policy_id'=>$policyId,'mode'=>$_POST['access_mode']??'','days'=>$days]);$message='Controle da empresa atualizado com sucesso.';}catch(Throwable$e){$error=$e->getMessage();}}
$rows=$policies->listTenantsWithPolicies();$ruleMap=[];foreach($rows as&$row){$effective=$policies->effectiveForTenant((int)$row['tenant_id']);$row['access_mode']=$effective['access_mode'];$row['can_issue_fiscal']=$effective['can_issue_fiscal'];$row['can_manage_users']=$effective['can_manage_users'];$row['can_use_financial']=$effective['can_use_financial'];$ruleMap[(int)$row['tenant_id']]=$effective['rules'];}unset($row);$history=$policies->history(80);$esc=static fn(mixed$v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
renderPlatformStart($identity,'Auditoria e controles','Auditoria');
?>
<div class="page-title"><div><p class="eyebrow">Controle avançado</p><h1>Auditoria</h1><p class="muted">Defina acessos permanentes ou temporários por empresa.</p></div></div>
<?php if($message):?><p class="message success"><?=$esc($message)?></p><?php endif?><?php if($error):?><p class="message error"><?=$esc($error)?></p><?php endif?>
<section class="cards"><article class="stat-card"><span>Empresas monitoradas</span><strong><?=count($rows)?></strong></article><article class="stat-card"><span>Somente consulta</span><strong><?=count(array_filter($rows,fn($r)=>($r['access_mode']??'')==='READ_ONLY'))?></strong></article><article class="stat-card"><span>Emissão bloqueada</span><strong><?=count(array_filter($rows,fn($r)=>isset($r['can_issue_fiscal'])&&!(bool)$r['can_issue_fiscal']))?></strong></article><article class="stat-card"><span>Bloqueadas</span><strong><?=count(array_filter($rows,fn($r)=>($r['access_mode']??'')==='BLOCKED'))?></strong></article></section>
<section class="panel"><div class="panel-header"><div><h2>Controles por empresa</h2><span class="muted">A ausência de regra mantém acesso completo.</span></div></div><div class="table-wrap"><table class="audit-company-table"><thead><tr><th>Empresa</th><th>Modo</th><th>Nota fiscal</th><th>Usuários</th><th>Financeiro</th><th>Validade</th><th></th></tr></thead><tbody><?php foreach($rows as$r):$mode=$r['access_mode']??'FULL';?><tr><td data-label="Empresa"><strong><?=$esc($r['nome_fantasia']?:$r['razao_social'])?></strong><small>#<?=(int)$r['tenant_id']?></small></td><td data-label="Modo"><span class="badge <?=$mode==='BLOCKED'?'badge-blocked':($mode==='READ_ONLY'?'badge-pending':'badge-active')?>"><?=$esc(['FULL'=>'Completo','READ_ONLY'=>'Somente consulta','BLOCKED'=>'Bloqueado'][$mode]??'Completo')?></span></td><td data-label="Nota fiscal"><?=!isset($r['can_issue_fiscal'])||$r['can_issue_fiscal']?'Permitida':'Bloqueada'?></td><td data-label="Usuários"><?=!isset($r['can_manage_users'])||$r['can_manage_users']?'Permitido':'Bloqueado'?></td><td data-label="Financeiro"><?=!isset($r['can_use_financial'])||$r['can_use_financial']?'Permitido':'Bloqueado'?></td><td data-label="Validade"><?=$r['policy_id']?($r['expires_at']?$esc(date('d/m/Y H:i',strtotime($r['expires_at']))):'Permanente'):'Sem regra'?></td><td data-label="Ação"><button class="btn small" type="button" data-audit-open data-tenant='<?=json_encode(['id'=>(int)$r['tenant_id'],'name'=>$r['nome_fantasia']?:$r['razao_social'],'mode'=>$mode,'fiscal'=>!isset($r['can_issue_fiscal'])||!!$r['can_issue_fiscal'],'users'=>!isset($r['can_manage_users'])||!!$r['can_manage_users'],'financial'=>!isset($r['can_use_financial'])||!!$r['can_use_financial']],JSON_HEX_APOS|JSON_HEX_QUOT)?>'>Configurar</button></td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><div class="panel-header"><h2>Histórico recente</h2></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Empresa</th><th>Controle</th><th>Prazo</th><th>Responsável</th><th>Motivo</th></tr></thead><tbody><?php foreach($history as$h):?><tr><td><?=$esc(date('d/m/Y H:i',strtotime($h['created_at'])))?></td><td><?=$esc($h['nome_fantasia'])?></td><td><?=$esc($h['access_mode'])?></td><td><?=$h['expires_at']?$esc(date('d/m/Y',strtotime($h['expires_at']))):'Permanente'?></td><td><?=$esc($h['actor_name']??'Sistema')?></td><td><?=$esc($h['reason'])?></td></tr><?php endforeach?></tbody></table></div></section>
<div class="audit-modal" data-audit-modal hidden><div class="audit-modal__backdrop" data-audit-close></div><section class="audit-modal__surface" role="dialog" aria-modal="true"><header><div><small>Controle da empresa</small><h2 data-audit-title>Configurar acesso</h2></div><button type="button" data-audit-close>×</button></header><form method="post"><input type="hidden" name="csrf_token" value="<?=$esc($_SESSION['platform_audit_csrf'])?>"><input type="hidden" name="tenant_id"><nav class="audit-tabs"><button class="active" type="button" data-audit-tab="access">Acesso</button><button type="button" data-audit-tab="modules">Permissões</button><button type="button" data-audit-tab="period">Prazo e motivo</button></nav><div class="audit-modal__body"><div data-audit-panel="access"><label>Modo de acesso<select name="access_mode"><option value="FULL">Acesso completo</option><option value="READ_ONLY">Somente consulta</option><option value="BLOCKED">Bloquear empresa</option></select></label><p class="muted">Somente consulta permite visualizar os dados, mas impede alterações.</p></div><div data-audit-panel="modules" hidden><div class="audit-switches"><label><input type="checkbox" name="can_issue_fiscal" value="1"><span><strong>Emitir notas fiscais</strong><small>Preparar, emitir e transmitir documentos fiscais.</small></span></label><label><input type="checkbox" name="can_manage_users" value="1"><span><strong>Gerenciar usuários</strong><small>Criar, editar e remover acessos da empresa.</small></span></label><label><input type="checkbox" name="can_use_financial" value="1"><span><strong>Usar financeiro</strong><small>Acesso às rotinas financeiras.</small></span></label></div></div><div data-audit-panel="period" hidden><label>Validade<select name="days"><option value="">Permanente</option><option value="5">5 dias</option><option value="10">10 dias</option><option value="15">15 dias</option><option value="30">30 dias</option></select></label><label>Motivo<textarea name="reason" rows="4" maxlength="500" required placeholder="Explique o motivo deste controle"></textarea></label></div></div><footer><button class="btn secondary" type="button" data-audit-close>Cancelar</button><button class="btn" type="submit">Aplicar controle</button></footer></form></section></div>
<script>window.AUDIT_TENANT_RULES=<?=json_encode($ruleMap,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="/assets/platform-audit.js?v=5" defer></script>
<?php renderPlatformEnd();
