<?php
declare(strict_types=1);
use MiniErp\Platform\ImportPlanStorage;
use MiniErp\Platform\TabularImportReader;
use MiniErp\Platform\TenantCatalogImportService;
use MiniErp\Repositories\PlatformAdminRepository;
require_once __DIR__.'/_context.php';require_once __DIR__.'/_layout.php';
[$main,,,$identity]=requireAuthorizedPlatformContext();require_once __DIR__.'/../../vendor/autoload.php';
if(!in_array($identity->getRole(),['SUPER_ADMIN','GLOBAL_TECH'],true)){http_response_code(403);exit('Perfil sem permissão para importar cadastros.');}
$_SESSION['platform_catalog_import_csrf']??=bin2hex(random_bytes(32));$root=dirname(__DIR__,2);$storage=new ImportPlanStorage($root.'/storage/imports');$service=new TenantCatalogImportService();$result=null;$error='';
$tenantConnection=static function(int$id)use($main,$root):array{$s=$main->prepare('SELECT id AS tenant_id,nome_fantasia,razao_social,db_name,blocked FROM tenants WHERE id=? LIMIT 1');$s->execute([$id]);$tenant=$s->fetch(PDO::FETCH_ASSOC);if(!$tenant||!empty($tenant['blocked'])||!preg_match('/^mini_erp_tenant_[1-9]\d*$/',(string)$tenant['db_name']))throw new RuntimeException('Empresa ou banco dedicado inválido.');$cfg=require$root.'/config.php';$db=$cfg['db'];$pdo=new PDO("mysql:host={$db['host']};port={$db['port']};dbname={$tenant['db_name']};charset=utf8mb4",$db['username'],$db['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);return[$tenant,$pdo];};
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){try{$sentToken=(string)($_POST['csrf_token']??'');$catalogToken=(string)$_SESSION['platform_catalog_import_csrf'];$operationsToken=(string)($_SESSION['platform_operations_csrf']??'');if(!hash_equals($catalogToken,$sentToken)&&($operationsToken===''||!hash_equals($operationsToken,$sentToken)))throw new RuntimeException('Sessão expirada. Atualize a página.');$action=(string)($_POST['action']??'');
 if($action==='simulate'){$file=$_FILES['import_file']??[];if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file((string)($file['tmp_name']??'')))throw new RuntimeException('Selecione uma planilha válida.');$tenantId=(int)($_POST['tenant_id']??0);[$tenant,$pdo]=$tenantConnection($tenantId);$entity=(string)($_POST['entity']??'');$table=(new TabularImportReader())->read((string)$file['tmp_name'],(string)$file['name']);if($entity==='icms_uf'){$validFrom=trim((string)($_POST['valid_from']??''));$validTo=trim((string)($_POST['valid_to']??''));foreach($table['rows']as&$importRow){$importRow['data']['valid_from']=$validFrom;$importRow['data']['valid_to']=$validTo;}unset($importRow);}$result=$service->simulate($pdo,$tenantId,$entity,$table['rows'],basename((string)$file['name']));$result['plan_id']=$storage->create($identity->getUserId(),$result);$result['tenant_name']=$tenant['nome_fantasia']?:$tenant['razao_social'];(new PlatformAdminRepository($main))->audit($identity->getUserId(),'CATALOG_IMPORT_SIMULATED','tenant',(string)$tenantId,$_SERVER['REMOTE_ADDR']??null,['entity'=>$result['entity'],'filename'=>$result['filename'],'summary'=>$result['summary'],'write_performed'=>false]);}
 elseif($action==='execute'){$id=(string)($_POST['plan_id']??'');$plan=$storage->load($id,$identity->getUserId());$expected='IMPORTAR '.$plan['summary']['valid'].' REGISTROS NO TENANT '.$plan['tenant_id'];if(!hash_equals($expected,trim((string)($_POST['confirmation']??''))))throw new RuntimeException('Confirmação textual inválida.');$reason=trim((string)($_POST['reason']??''));if($reason==='')throw new RuntimeException('Informe o motivo da importação.');[, $pdo]=$tenantConnection((int)$plan['tenant_id']);$done=$service->execute($pdo,(int)$plan['tenant_id'],$plan);$storage->consume($id,$identity->getUserId());$result=['executed'=>true,'summary'=>$done,'tenant_id'=>$plan['tenant_id'],'entity'=>$plan['entity']];(new PlatformAdminRepository($main))->audit($identity->getUserId(),'CATALOG_IMPORT_EXECUTED','tenant',(string)$plan['tenant_id'],$_SERVER['REMOTE_ADDR']??null,['entity'=>$plan['entity'],'filename'=>$plan['filename'],'result'=>$done,'reason'=>$reason]);}
 else throw new RuntimeException('Ação inválida.');
}catch(Throwable$e){$error=$e->getMessage();}}
$tenants=$main->query("SELECT id AS tenant_id,nome_fantasia,razao_social FROM tenants WHERE blocked=0 AND status='ativo' ORDER BY nome_fantasia,razao_social,id")->fetchAll(PDO::FETCH_ASSOC);$esc=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');renderPlatformStart($identity,'Importar cadastros','Operações Multi-tenant');
?>
<div class="page-title"><div><p class="eyebrow">ASSISTENTE SEGURO</p><h1>Importar cadastros por planilha</h1><p>Envie CSV ou XLSX, revise a simulação e só então confirme a gravação.</p></div><a class="btn secondary" href="/plataforma/operacoes-multitenant.php">Voltar</a></div>
<?php if($error):?><p class="message warning" role="alert"><?=$esc($error)?></p><?php endif?>
<?php if($result&&isset($result['executed'])):?><section class="panel"><h2>Importação concluída</h2><p class="message success">Foram processados <?=(int)$result['summary']['processed']?> registros no tenant #<?=(int)$result['tenant_id']?>: <?=(int)$result['summary']['created']?> incluídos e <?=(int)$result['summary']['updated']?> atualizados.</p><a class="btn" href="/plataforma/catalogo-importar.php">Nova importação</a></section>
<?php elseif($result):$summary=$result['summary'];$phrase='IMPORTAR '.$summary['valid'].' REGISTROS NO TENANT '.$result['tenant_id'];?>
<section class="panel"><h2>Resultado da simulação</h2><p><strong><?=$esc($result['tenant_name'])?></strong> · <?=$esc($result['entity'])?> · <?=$esc($result['filename'])?></p><div class="operations-grid"><div><strong><?=(int)$summary['total']?></strong><small> linhas lidas</small></div><div><strong><?=(int)$summary['create']?></strong><small> inclusões</small></div><div><strong><?=(int)$summary['update']?></strong><small> atualizações</small></div><div><strong><?=(int)$summary['errors']?></strong><small> erros</small></div></div>
<?php if($result['issues']):?><div class="table-wrap"><table><thead><tr><th>Linha</th><th>Motivo do bloqueio</th></tr></thead><tbody><?php foreach($result['issues']as$issue):?><tr><td><?=(int)$issue['line']?></td><td><?=$esc($issue['message'])?></td></tr><?php endforeach?></tbody></table></div><?php endif?>
<?php if($summary['valid']>0):?><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=$esc($_SESSION['platform_catalog_import_csrf'])?>"><input type="hidden" name="action" value="execute"><input type="hidden" name="plan_id" value="<?=$esc($result['plan_id'])?>"><label>Confirmação textual<input name="confirmation" required autocomplete="off" placeholder="<?=$esc($phrase)?>"><small>Digite exatamente: <strong><?=$esc($phrase)?></strong></small></label><label>Motivo da importação<input name="reason" required maxlength="300" placeholder="Carga inicial recebida do cliente"></label><button class="btn" type="submit">Confirmar e importar</button></form><?php endif?></section>
<?php else:?>
<section class="panel"><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf_token" value="<?=$esc($_SESSION['platform_catalog_import_csrf'])?>"><input type="hidden" name="action" value="simulate"><label>Empresa / banco<select name="tenant_id" required><option value="">Selecione</option><?php foreach($tenants as$t):?><option value="<?=(int)$t['tenant_id']?>">#<?=(int)$t['tenant_id']?> · <?=$esc($t['nome_fantasia']?:$t['razao_social'])?></option><?php endforeach?></select></label><label>Cadastro a importar<select name="entity" required><option value="produtos">Produtos</option><option value="clientes">Clientes</option><option value="fornecedores">Fornecedores</option><option value="cfops">CFOPs</option><option value="impostos">Impostos relacionados por NCM/origem</option><option value="icms_uf">ICMS por UF de destino</option></select></label><label>Vigência inicial (ICMS por UF)<input type="date" name="valid_from"></label><label>Vigência final opcional<input type="date" name="valid_to"></label><label>Planilha CSV ou XLSX<input type="file" name="import_file" accept=".csv,.txt,.xlsx" required></label><button class="btn" type="submit">Ler e simular</button></form><p class="muted">A primeira linha deve conter os títulos. CSV aceita vírgula, ponto e vírgula ou tabulação. No XLSX será lida a primeira guia. Limite: 10 MB e 20.000 linhas.</p></section>
<section class="panel"><h2>Como os registros são identificados</h2><div class="table-wrap"><table><thead><tr><th>Cadastro</th><th>Chave segura</th><th>Obrigatórios</th></tr></thead><tbody><tr><td>Produtos</td><td>Código/SKU</td><td>Código e nome</td></tr><tr><td>Clientes e fornecedores</td><td>CPF/CNPJ</td><td>Documento válido e nome</td></tr><tr><td>CFOPs</td><td>Código CFOP</td><td>Código de 4 dígitos e descrição</td></tr><tr><td>Impostos</td><td>Código da regra + NCM + direção + modelo</td><td>NCM, CFOP, direção e modelo</td></tr><tr><td>ICMS por UF</td><td>UF + vigência inicial</td><td>UF, alíquotas e vigência</td></tr></tbody></table></div><p class="message warning">Uma regra tributária importada vira uma nova versão de produção e se aplica aos produtos com o mesmo NCM e origem. Revise com o contador antes de confirmar.</p></section>
<?php endif?>
<?php renderPlatformEnd();
