<?php
declare(strict_types=1);
use MiniErp\Infrastructure\TenantConnectionResolver; use MiniErp\Repositories\TenantEstablishmentRepository; use MiniErp\Services\EstablishmentData; use MiniErp\Services\EstablishmentService; use MiniErp\Services\FiscalReadiness; use MiniErp\Services\FlashFormState;
require_once __DIR__.'/_tenant_users.php'; require_once __DIR__.'/../includes/establishment_form.php'; [$identity,$tenant,,$administrativeContext]=requireTenantUserContext(); $tenantId=$administrativeContext->getSelectedTenantId();
require_once __DIR__.'/../../src/Contracts/EstablishmentRepositoryContract.php'; require_once __DIR__.'/../../src/Infrastructure/TenantConnectionResolver.php'; require_once __DIR__.'/../../src/Repositories/TenantEstablishmentRepository.php'; require_once __DIR__.'/../../src/Services/EstablishmentData.php'; require_once __DIR__.'/../../src/Services/EstablishmentService.php'; require_once __DIR__.'/../../src/Services/FiscalReadiness.php';
$error='';$schemaAvailable=false;$establishment=null;$state=FlashFormState::consume($_SESSION);if($state)$error=(string)(reset($state['errors'])?:'Revise os campos.');
try{$tenantConnection=(new TenantConnectionResolver(__DIR__.'/../../config.php'))->resolveAdministrative($administrativeContext);$repository=new TenantEstablishmentRepository($tenantConnection);$service=new EstablishmentService($repository);$schemaAvailable=$repository->schemaAvailable();$establishment=$service->find($tenantId);if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){requirePlatformUserCsrf();$establishment=$service->save($tenantId,new EstablishmentData($_POST));header('Location: /plataforma/empresa-fiscal.php?id='.$tenantId.'&saved=1');exit;}}catch(DomainException|InvalidArgumentException $exception){if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){FlashFormState::store($_SESSION,'save_establishment',$_POST,['_form'=>$exception->getMessage()]);header('Location: /plataforma/empresa-fiscal.php?id='.$tenantId);exit;}$error=$exception->getMessage();}catch(Throwable){$error='Não foi possível acessar o cadastro fiscal no banco dedicado.';}
$formData=array_merge($establishment??$tenant,$state['old_input']??[]);$readiness=(new FiscalReadiness())->evaluate($establishment);$groups=$readiness['groups'];$label=static fn(bool $ok):string=>$ok?'OK':'Pendente';renderPlatformStart($identity,'Cadastro fiscal','Empresas → '.($tenant['nome_fantasia']??'').' → Fiscal');?>
<nav class="company-tabs" aria-label="Áreas da empresa"><a href="/plataforma/empresa.php?id=<?= $tenantId ?>">Geral</a><a class="active" href="/plataforma/empresa-fiscal.php?id=<?= $tenantId ?>">Fiscal</a><a href="/plataforma/empresa-fiscal-config.php?id=<?= $tenantId ?>#certificate">Certificado Digital</a><a href="/plataforma/empresa-fiscal-config.php?id=<?= $tenantId ?>#series">NF-e / NFC-e</a><a href="/plataforma/empresa-usuarios.php?id=<?= $tenantId ?>">Usuários</a><a href="/plataforma/empresa.php?id=<?= $tenantId ?>#ambiente">Ambiente</a></nav>
<div class="page-title"><div><p class="eyebrow">Tenant #<?= $tenantId ?> · estabelecimento MATRIZ</p><h1>Cadastro fiscal do emitente</h1><p class="muted">Fonte canônica no banco dedicado. Os dados do Control-Plane servem somente ao bootstrap inicial.</p></div></div>
<?php if(isset($_GET['saved'])):?><p class="message success">Cadastro fiscal salvo no tenant selecionado.</p><?php endif;?><?php if($error!==''):?><p class="message error" role="alert"><?= platformEscape($error) ?></p><?php endif;?>
<section class="panel"><h2>Prontidão</h2><div class="status-list"><div class="status-item"><span>Cadastro</span><strong><?= $label($groups['registration_complete']) ?></strong></div><div class="status-item"><span>Identidade fiscal</span><strong><?= $label($groups['tax_identity_complete']) ?></strong></div><div class="status-item"><span>Endereço</span><strong><?= $label($groups['address_complete']) ?></strong></div><div class="status-item"><span>Contato</span><strong><?= $label($groups['contact_complete']) ?></strong></div><div class="status-item"><span>Certificado</span><strong>Pendente</strong></div><div class="status-item"><span>Configuração NF-e</span><strong>Pendente</strong></div><div class="status-item"><span>Configuração NFC-e</span><strong>Pendente</strong></div><div class="status-item"><span>Homologação</span><strong>Não realizada</strong></div><div class="status-item"><span>Produção</span><strong>Bloqueada</strong></div></div><p class="message warning">Fiscal Readiness: <strong><?= platformEscape($readiness['status']) ?></strong>. Cadastro completo não autoriza emissão.</p></section>
<section class="panel onboarding-note"><h2>Dados do emitente</h2><?php if(!$schemaAvailable):?><p class="message error">Migration FISCAL-01 ainda não aplicada neste tenant. Faça backup e aplique-a manualmente; esta tela não altera schema.</p><?php else:?><?php renderEstablishmentForm($formData,(string)$_SESSION['platform_user_csrf']);?><?php endif;?></section><p><a href="/plataforma/empresa.php?id=<?= $tenantId ?>">← Voltar para a empresa</a></p><?php renderPlatformEnd();?>
