<?php
declare(strict_types=1);
use MiniErp\Infrastructure\TenantConnectionResolver;use MiniErp\Repositories\{FiscalConfigurationRepository,TenantEstablishmentRepository};
require_once __DIR__.'/_tenant_users.php';require_once __DIR__.'/../../vendor/autoload.php';[$identity,$tenant,,$context]=requireTenantUserContext();$tenantId=$context->getSelectedTenantId();$pdo=(new TenantConnectionResolver(__DIR__.'/../../config.php'))->resolveAdministrative($context);$est=(new TenantEstablishmentRepository($pdo))->findPrimaryForTenant($tenantId);$certificate=$est?(new FiscalConfigurationRepository($pdo,$tenantId))->latestCertificate((int)$est['id']):null;renderPlatformStart($identity,'Certificado Digital','Empresas → '.($tenant['nome_fantasia']??'').' → Fiscal');$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<div class="page-title"><div><p class="eyebrow">Certificado A1 da empresa</p><h1>Certificado Digital</h1><p class="muted">O arquivo fica instalado no storage privado e é reutilizado na assinatura de XML.</p></div></div>
<div class="dashboard-grid">
 <section class="panel"><h2>Certificado instalado</h2><?php if(!$certificate):?><p class="message error">Nenhum certificado instalado nesta empresa.</p><?php else:?><p class="message <?=$certificate['active']?'success':'warning'?>"><?=$certificate['active']?'Certificado pronto para emitir NF-e.':'Certificado armazenado, mas não ativo.'?></p><div class="status-list"><div class="status-item"><span>Status</span><strong><?=$e($certificate['status'])?></strong></div><div class="status-item"><span>Nome da empresa</span><strong><?=$e($certificate['subject'])?></strong></div><div class="status-item"><span>CNPJ encontrado</span><strong><?=$e($certificate['tax_id']?:'NOT_FOUND')?></strong></div><div class="status-item"><span>Validade</span><strong><?=$e($certificate['valid_until'])?></strong></div><div class="status-item"><span>Tipo</span><strong>A1</strong></div><div class="status-item"><span>Emissor ICP-Brasil</span><strong><?=$e($certificate['issuer'])?></strong></div><div class="status-item"><span>Número de série</span><strong><?=$e($certificate['serial_number'])?></strong></div><div class="status-item"><span>Fingerprint SHA256</span><strong><?=$e($certificate['fingerprint_sha256'])?></strong></div><div class="status-item"><span>Arquivo</span><strong>Armazenado com segurança</strong></div></div><?php endif;?><div class="form-actions"><?php if($certificate):?><a class="btn btn-secondary" href="/plataforma/certificado-download.php?id=<?=$tenantId?>&amp;token=<?=rawurlencode((string)$_SESSION['platform_user_csrf'])?>" download>Baixar certificado</a><?php endif;?><button class="btn btn-secondary" data-certificate-action="test">Testar Certificado</button><button class="btn btn-danger" data-certificate-action="remove">Remover Certificado</button></div></section>
 <section class="panel"><h2>Instalar novo certificado</h2><p><strong>Empresa:</strong> <?=$e($tenant['nome_fantasia']??'—')?><br><strong>Estabelecimento:</strong> <?=$e($est['legal_name']??'—')?><br><strong>CNPJ esperado:</strong> <?=$e($est['tax_id']??'—')?></p><form enctype="multipart/form-data" data-certificate-form data-tenant="<?=$tenantId?>"><input type="hidden" name="csrf_token" value="<?=$e($_SESSION['platform_user_csrf'])?>"><input type="hidden" name="action" value="validate"><label>Arquivo PFX/P12<input type="file" name="certificate" accept=".pfx,.p12" required></label><label>Senha<input type="password" name="password" required autocomplete="new-password"></label><progress data-certificate-progress hidden></progress><div class="form-actions"><button class="btn" type="submit">Validar e instalar</button><button class="btn btn-secondary" type="reset">Cancelar</button></div></form><pre data-certificate-diagnostic class="message">Aguardando validação.</pre></section>
</div><script src="/assets/certificate-install.js"></script><?php renderPlatformEnd(); ?>
