<?php
declare(strict_types=1);
use MiniErp\Services\PlatformTenantUserData;
require_once __DIR__ . '/_tenant_users.php';
require_once __DIR__ . '/../../src/Services/PlatformTenantUserData.php';
[$identity,$tenant,$service,$administrativeContext]=requireTenantUserContext();$tenantId=$administrativeContext->getSelectedTenantId();$values=['nome'=>'','email'=>'','role'=>'user','status'=>'ativo'];$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){foreach(array_keys($values) as $field)if(isset($_POST[$field])&&is_scalar($_POST[$field]))$values[$field]=(string)$_POST[$field];try{requirePlatformUserCsrf();$service->create($administrativeContext,PlatformTenantUserData::fromArray($_POST),(string)($_POST['senha']??''),(string)($_POST['confirmar_senha']??''));header('Location: /plataforma/empresa-usuarios.php?id='.$tenantId.'&created=1');exit;}catch(DomainException|InvalidArgumentException $exception){$error=$exception->getMessage();}}
renderPlatformStart($identity,'Novo usuário','Empresas → '.($tenant['nome_fantasia']??'').' → Usuários → Novo');?>
<section class="panel"><p class="eyebrow">Tenant #<?= $tenantId ?></p><h1>Novo usuário</h1><p class="muted">O vínculo com <?= platformEscape($tenant['nome_fantasia']) ?> é determinado pelo servidor.</p><?php if($error!==''):?><p class="message error" role="alert"><?= platformEscape($error) ?></p><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?= platformEscape($_SESSION['platform_user_csrf']) ?>"><div class="detail-grid"><label class="detail">Nome<input name="nome" maxlength="150" required value="<?= platformEscape($values['nome']) ?>"></label><label class="detail">E-mail<input type="email" name="email" maxlength="150" required value="<?= platformEscape($values['email']) ?>"></label><label class="detail">Senha inicial<input type="password" name="senha" minlength="8" required autocomplete="new-password"></label><label class="detail">Confirmar senha<input type="password" name="confirmar_senha" minlength="8" required autocomplete="new-password"></label><label class="detail">Perfil<select name="role"><option value="user"<?= $values['role']==='user'?' selected':'' ?>>Usuário</option><option value="admin"<?= $values['role']==='admin'?' selected':'' ?>>Administrador da empresa</option></select></label><label class="detail">Status<select name="status"><option value="ativo"<?= $values['status']==='ativo'?' selected':'' ?>>Ativo</option><option value="inativo"<?= $values['status']==='inativo'?' selected':'' ?>>Inativo</option></select></label></div><div class="form-actions"><button class="btn" type="submit">Criar usuário</button><a class="btn secondary" href="/plataforma/empresa-usuarios.php?id=<?= $tenantId ?>">Cancelar</a></div></form></section><?php renderPlatformEnd(); ?>
