<?php
declare(strict_types=1);
use MiniErp\Context\AdministrativeContext; use MiniErp\Context\SelectedTenant; use MiniErp\Infrastructure\TenantConnectionResolver; use MiniErp\Repositories\PlatformTenantRepository; use MiniErp\Repositories\TenantEstablishmentRepository; use MiniErp\Services\EstablishmentFiscalCompleteness; use MiniErp\Services\PlatformTenantLifecycle;
require_once __DIR__ . '/_context.php'; require_once __DIR__ . '/_layout.php'; [$connection, , $authorizer, $identity] = requireAuthorizedPlatformContext();
require_once __DIR__ . '/../../src/Contracts/PlatformTenantRepositoryContract.php'; require_once __DIR__ . '/../../src/Repositories/PlatformTenantRepository.php'; require_once __DIR__ . '/../../src/Services/PlatformTenantLifecycle.php';
require_once __DIR__ . '/../../src/Services/EstablishmentData.php'; require_once __DIR__ . '/../../src/Services/EstablishmentFiscalCompleteness.php';
$tenantId=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0; $tenant=(new PlatformTenantRepository($connection))->findById($tenantId); if($tenant===null){http_response_code(404);echo 'Empresa não encontrada.';exit;}
$lifecycle=new PlatformTenantLifecycle(); $state=$lifecycle->interpret((string)$tenant['status'],!empty($tenant['blocked'])); $actions=$lifecycle->actions((string)$tenant['status'],$tenant['db_name']??null,!empty($tenant['blocked']));
$hasDatabase=trim((string)($tenant['db_name']??''))!==''; $establishment=null; $fiscalAvailable=false;
if($hasDatabase&&$authorizer->isAuthorized($identity)){ require_once __DIR__ . '/../../src/Context/SelectedTenant.php'; require_once __DIR__ . '/../../src/Context/AdministrativeContext.php'; require_once __DIR__ . '/../../src/Infrastructure/TenantConnectionResolver.php'; require_once __DIR__ . '/../../src/Contracts/EstablishmentRepositoryContract.php'; require_once __DIR__ . '/../../src/Repositories/TenantEstablishmentRepository.php'; require_once __DIR__ . '/../../src/Services/EstablishmentData.php'; require_once __DIR__ . '/../../src/Services/EstablishmentFiscalCompleteness.php'; try{$context=new AdministrativeContext($identity->getUserId(),new SelectedTenant($identity->getUserId(),$tenantId,true));$fiscalRepository=new TenantEstablishmentRepository((new TenantConnectionResolver(__DIR__.'/../../config.php'))->resolveAdministrative($context));$fiscalAvailable=$fiscalRepository->schemaAvailable();$establishment=$fiscalRepository->findPrimaryForTenant($tenantId);}catch(Throwable){$fiscalAvailable=false;} }
$complete=(new EstablishmentFiscalCompleteness())->evaluate($establishment); $businessComplete=trim((string)$tenant['razao_social'])!==''&&trim((string)$tenant['nome_fantasia'])!==''&&trim((string)$tenant['cnpj'])!==''&&trim((string)$tenant['slug'])!=='';
$certificate=null;$fiscalSeries=[];if($establishment&&$hasDatabase){require_once __DIR__.'/../../src/Repositories/FiscalConfigurationRepository.php';try{$configPdo=(new TenantConnectionResolver(__DIR__.'/../../config.php'))->resolveAdministrative($context);$configRepo=new \MiniErp\Repositories\FiscalConfigurationRepository($configPdo,$tenantId);$certificate=$configRepo->certificate((int)$establishment['id']);$fiscalSeries=$configRepo->series((int)$establishment['id']);}catch(Throwable){$certificate=null;$fiscalSeries=[];}}$certDays=$certificate?(int)floor((strtotime($certificate['valid_until'])-time())/86400):null;$nfeSeries=array_values(array_filter($fiscalSeries,static fn(array $s):bool=>$s['model']==='55'&&!empty($s['active'])));$nfceSeries=array_values(array_filter($fiscalSeries,static fn(array $s):bool=>$s['model']==='65'&&!empty($s['active'])));
$status=static fn(bool $ok):string=>$ok?'<strong class="status-ok">Completo</strong>':'<strong class="status-pending">Pendente</strong>'; renderPlatformStart($identity,'Empresa','Empresas → '.($tenant['nome_fantasia']??'')); ?>
<?php $_SESSION['platform_erp_access_csrf'] ??= bin2hex(random_bytes(32)); $erpAccessHref='/plataforma/empresa-acao.php?id='.$tenantId.'&amp;action=erp&amp;csrf_token='.rawurlencode((string)$_SESSION['platform_erp_access_csrf']); ?>
<div class="page-title"><div><p class="eyebrow">Onboarding da empresa</p><h1><?= platformEscape($tenant['nome_fantasia']) ?></h1><p class="muted">Tenant #<?= $tenantId ?> · lifecycle <?= platformEscape($state) ?> · readiness fiscal independente</p><p><strong>Banco:</strong> <?=platformEscape($tenant['db_name']??'Não provisionado')?> · <strong>Schema:</strong> <?=($tenant['schema_version']??null)==='v1'?'ATUALIZADO':'PENDENTE / histórico'?></p></div><?php if($actions['erp']):?><a class="btn" href="<?= $erpAccessHref ?>">Acessar ERP</a><?php endif;?></div>
<?php if(isset($_GET['created'])):?><p class="message success">Cadastro empresarial criado. Próxima etapa: provisionar o banco dedicado.</p><?php endif;?><?php if(isset($_GET['provisioned'])):?><p class="message success">Banco dedicado criado. Próxima etapa: completar o cadastro fiscal.</p><?php endif;?>
<?php if(isset($_GET['updated'])):?><p class="message success">Dados gerais atualizados no Control-Plane.</p><?php endif;?>
<nav class="company-tabs" aria-label="Áreas da empresa"><a class="active" href="/plataforma/empresa.php?id=<?= $tenantId ?>">Geral</a><a href="/plataforma/empresa-fiscal-central.php?id=<?= $tenantId ?>">Central Fiscal</a><?php if($fiscalAvailable):?><a href="/plataforma/empresa-fiscal.php?id=<?= $tenantId ?>">Fiscal</a><a href="/plataforma/empresa-fiscal-config.php?id=<?= $tenantId ?>#certificate">Certificado Digital</a><a href="/plataforma/empresa-fiscal-config.php?id=<?= $tenantId ?>#series">NF-e / NFC-e</a><?php else:?><span class="disabled">Fiscal</span><span class="disabled">Certificado Digital</span><span class="disabled">NF-e / NFC-e</span><?php endif;?><?php if($actions['users']):?><a href="/plataforma/empresa-usuarios.php?id=<?= $tenantId ?>">Usuários</a><?php else:?><span class="disabled">Usuários</span><?php endif;?><a href="/plataforma/empresa-database.php?id=<?=$tenantId?>">Banco de Dados</a><a href="#ambiente">Ambiente</a></nav>
<section class="panel"><h2>Status fiscal</h2><div class="status-list"><div class="status-item"><span>Dados fiscais</span><?= $status($complete['emit_ready']) ?></div><div class="status-item"><span>Certificado</span><strong><?= $certificate?'Válido · '.$certDays.' dias':'Não configurado' ?></strong></div><div class="status-item"><span>NF-e</span><strong><?= $nfeSeries?'Série '.$nfeSeries[0]['series'].' · Homologação':'Pendente' ?></strong></div><div class="status-item"><span>NFC-e</span><strong><?= $nfceSeries?'Série '.$nfceSeries[0]['series'].' · Homologação · CSC pendente':'Pendente · CSC não configurado' ?></strong></div><div class="status-item"><span>Homologação</span><strong>Não validada</strong></div><div class="status-item"><span>Produção fiscal</span><strong class="status-pending">Bloqueada</strong></div></div></section>
<section class="panel onboarding-note"><div class="panel-header"><h2>Geral</h2><?php if($actions['edit']):?><a class="btn secondary" href="/plataforma/empresa-editar.php?id=<?= $tenantId ?>">Editar dados gerais</a><?php endif;?></div><div class="detail-grid"><div class="detail"><small>Razão social</small><strong><?= platformEscape($tenant['razao_social']) ?></strong></div><div class="detail"><small>Nome fantasia</small><strong><?= platformEscape($tenant['nome_fantasia']) ?></strong></div><div class="detail"><small>CNPJ administrativo</small><strong><?= platformEscape($tenant['cnpj']) ?></strong></div><div class="detail"><small>Slug</small><strong><?= platformEscape($tenant['slug']) ?></strong></div><div class="detail"><small>Tenant ID — somente leitura</small><strong>#<?= $tenantId ?></strong></div><div class="detail"><small>Lifecycle — ação própria</small><strong><?= platformEscape($state) ?></strong></div><div class="detail"><small>Bloqueio — ação própria</small><strong><?= !empty($tenant['blocked'])?'Bloqueada':'Não bloqueada' ?></strong></div><div class="detail"><small>Criado / atualizado</small><strong><?= platformEscape(($tenant['created_at']??'—').' / '.($tenant['updated_at']??'—')) ?></strong></div></div></section>
<section class="panel onboarding-note" id="ambiente"><h2>Próxima ação</h2><?php if(!$hasDatabase):?><p>O cadastro fiscal ainda não pode ser persistido. Provisione o banco dedicado primeiro.</p><?php if($actions['provision']):?><a class="btn" href="/plataforma/empresa-provisionar.php?id=<?= $tenantId ?>">2. Provisionar banco dedicado</a><?php endif;?><?php elseif(!$complete['emit_ready']):?><p>O ambiente existe. Complete identificação fiscal, inscrições e endereço do estabelecimento.</p><a class="btn" href="/plataforma/empresa-fiscal.php?id=<?= $tenantId ?>">3. Completar dados fiscais</a><?php else:?><p>Cadastro empresarial e origem de dados de <code>emit/enderEmit</code> completos. Readiness geral continua <strong>INCOMPLETE</strong> até certificado e configuração fiscal futura.</p><a class="btn secondary" href="/plataforma/empresa-fiscal.php?id=<?= $tenantId ?>">Revisar cadastro fiscal</a><?php endif;?></section>
<section class="panel onboarding-note"><h2>Recursos futuros</h2><p><strong>Certificado Digital:</strong> não configurado. Configuração disponível na FISCAL-02.</p><p><strong>NFC-e:</strong> não configurada. Nenhum campo CSC existe nesta tela.</p></section><?php renderPlatformEnd(); ?>
