<?php

declare(strict_types=1);

require_once __DIR__ . '/_context.php';
require_once __DIR__ . '/../../src/Services/PlatformTenantLifecycle.php';
[, , , $identity, $service] = requireAuthorizedPlatformContext();
$query=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$limit=max(1,min(100,(int)($_GET['limit']??20)));$statusFilter=(string)($_GET['status']??'');$result=$service->searchTenants($identity,$query,$page,$limit,$statusFilter);$tenants=$result['items'];$total=(int)$result['total'];$from=$total?($page-1)*$limit+1:0;$to=min($total,$page*$limit);
$lifecycle = new \MiniErp\Services\PlatformTenantLifecycle();
if (empty($_SESSION['platform_logout_csrf'])) $_SESSION['platform_logout_csrf'] = bin2hex(random_bytes(32));

$metrics = ['total' => count($tenants), 'active' => 0, 'pending' => 0, 'blocked' => 0];
foreach ($tenants as $item) {
    $state = $lifecycle->interpret((string) ($item['status'] ?? ''), !empty($item['blocked']));
    if ($state === 'ativa') $metrics['active']++;
    if ($state === 'cadastrada') $metrics['pending']++;
    if (in_array($state, ['parcialmente_bloqueada', 'bloqueada'], true)) $metrics['blocked']++;
}
$escape = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$statusLabel = static fn (string $state): string => match ($state) { 'cadastrada' => 'Cadastrada', 'provisionando' => 'Provisionando', 'ativa' => 'Ativa', 'parcialmente_bloqueada' => 'Bloqueio parcial', 'bloqueada' => 'Bloqueada', 'arquivada' => 'Arquivada', default => 'Estado desconhecido' };
$statusClass = static fn (string $state): string => match ($state) { 'cadastrada' => 'badge-pending', 'provisionando' => 'badge-running', 'ativa' => 'badge-active', 'parcialmente_bloqueada', 'bloqueada' => 'badge-blocked', 'arquivada' => 'badge-archived', default => 'badge-unknown' };
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel da Plataforma — Mini ERP</title><link rel="icon" type="image/png" sizes="32x32" href="/assets/images/Favicon-v2/favicon-32x32.png"><link rel="apple-touch-icon" href="/assets/images/Favicon-v2/apple-touch-icon.png"><link rel="stylesheet" href="/assets/platform.css"><link rel="stylesheet" href="/assets/app-ui.css"><link rel="stylesheet" href="/assets/app-feedback.css"><link rel="stylesheet" href="/assets/company-modal.css"><link rel="stylesheet" href="/assets/company-modal-navigation.css"><link rel="stylesheet" href="/assets/company-modal-shell.css"><script src="/assets/app-ui.js" defer></script><script src="/assets/app-feedback.js" defer></script><script src="/assets/company-modal.js" defer></script><script src="/assets/company-modal-navigation.js" defer></script></head><body><div class="platform-shell">
<aside class="platform-sidebar"><div class="platform-brand"><span class="brand-mark">MR</span><div><strong>Mini ERP</strong><small>Control-Plane</small></div></div><nav class="platform-nav" aria-label="Administração da Plataforma"><a href="/plataforma/">Dashboard</a><a class="active" href="/plataforma/">Empresas</a><a href="/plataforma/tecnicos.php">Técnicos globais</a><span class="disabled">Auditoria <small>Em breve</small></span><span class="disabled">Configurações <small>Em breve</small></span></nav></aside>
<div class="platform-main"><header class="platform-header"><div class="header-copy"><strong>Painel da Plataforma</strong><small>Administração da Plataforma · ambiente local</small></div><div class="admin-info"><div><strong><?= $escape($identity->getName()) ?></strong><small>PlatformAdmin</small></div><form class="logout-form" method="post" action="/plataforma/logout.php"><input type="hidden" name="csrf_token" value="<?= $escape($_SESSION['platform_logout_csrf']) ?>"><button class="btn ghost" type="submit">Sair</button></form></div></header>
<main class="content"><div class="page-title"><div><p class="eyebrow">Visão geral</p><h1>Empresas</h1><p class="muted">Cadastros, ambientes dedicados e lifecycle administrativo.</p></div><a class="btn" href="/plataforma/empresa-nova.php">+ Nova empresa</a></div>
<?php if (isset($_GET['created'])): ?><p class="message success">Empresa cadastrada e aguardando provisionamento.</p><?php endif; ?><?php if (isset($_GET['updated'])): ?><p class="message success">Dados administrativos atualizados.</p><?php endif; ?><?php if (isset($_GET['provisioned'])): ?><p class="message success">Ambiente dedicado provisionado e validado.</p><?php endif; ?>
<form method="get" class="panel form-grid"><label>Buscar empresa<input name="q" value="<?= $escape($query) ?>" placeholder="Razão social, fantasia, CNPJ, slug ou tenant ID"></label><label>Status<select name="status"><option value="">Todas</option><option value="ativa"<?= $statusFilter==='ativa'?' selected':'' ?>>Ativas</option><option value="cadastrada"<?= $statusFilter==='cadastrada'?' selected':'' ?>>Cadastradas</option><option value="bloqueada"<?= $statusFilter==='bloqueada'?' selected':'' ?>>Bloqueadas</option></select></label><input type="hidden" name="limit" value="<?= $limit ?>"><button class="btn">Buscar</button><span>Exibindo <?= $from ?>–<?= $to ?> de <?= $total ?> empresas.</span></form>
<section class="cards" aria-label="Resumo"><article class="stat-card"><span>Empresas nesta página</span><strong><?= $metrics['total'] ?></strong></article><article class="stat-card"><span>Empresas ativas</span><strong><?= $metrics['active'] ?></strong></article><article class="stat-card"><span>Aguardando provisionamento</span><strong><?= $metrics['pending'] ?></strong></article><article class="stat-card"><span>Empresas bloqueadas</span><strong><?= $metrics['blocked'] ?></strong></article></section>
<section class="panel"><div class="panel-header"><div><h2>Empresas da plataforma</h2><span class="muted">A disponibilidade das ações segue o lifecycle.</span></div></div><div class="table-wrap"><table><thead><tr><th>Empresa</th><th>CNPJ</th><th>Tenant</th><th>Slug</th><th>Status</th><th>Ambiente</th><th>Ações</th></tr></thead><tbody>
<?php foreach ($tenants as $tenant): $state = $lifecycle->interpret((string) ($tenant['status'] ?? ''), !empty($tenant['blocked'])); $actions = $lifecycle->actions((string) ($tenant['status'] ?? ''), $tenant['db_name'] ?? null, !empty($tenant['blocked'])); $tenantId = (int) ($tenant['tenant_id'] ?? 0); ?>
<tr data-company-row="<?= $tenantId ?>"><td class="company-name"><strong><?= $escape($tenant['nome_fantasia'] ?? '') ?></strong><small><?= $escape($tenant['razao_social'] ?? '') ?></small></td><td><?= $escape($tenant['cnpj'] ?? '') ?></td><td>#<?= $tenantId ?></td><td><?= $escape($tenant['slug'] ?? '') ?></td><td><span class="badge <?= $statusClass($state) ?>"><?= $statusLabel($state) ?></span></td><td class="environment"><?= trim((string) ($tenant['db_name'] ?? '')) !== '' ? 'Banco dedicado disponível' : 'Não provisionado' ?></td><td><div class="actions"><a class="btn small secondary" data-company-modal data-company-id="<?= $tenantId ?>" data-company-name="<?= $escape($tenant['nome_fantasia'] ?: $tenant['razao_social']) ?>" href="/plataforma/empresa.php?id=<?= $tenantId ?>">Editar</a><?php if ($actions['provision']): ?><a class="btn small" href="/plataforma/empresa-provisionar.php?id=<?= $tenantId ?>">Provisionar</a><?php else: ?><span class="btn small disabled" aria-disabled="true">Provisionar</span><?php endif; ?><?php if ($actions['users']): ?><a class="btn small ghost" href="/plataforma/empresa-acao.php?id=<?= $tenantId ?>&amp;action=usuarios">Usuários</a><?php else: ?><span class="btn small disabled" aria-disabled="true" title="Disponível após configuração">Usuários</span><?php endif; ?><?php if ($actions['erp']): ?><a class="btn small ghost" href="/login.php?empresa=<?= rawurlencode((string) ($tenant['slug'] ?? '')) ?>">Acessar ERP</a><?php else: ?><span class="btn small disabled" aria-disabled="true" title="Disponível após configuração">Acessar ERP</span><?php endif; ?></div></td></tr>
<?php endforeach; ?><?php if ($tenants === []): ?><tr><td colspan="7">Nenhuma empresa cadastrada.</td></tr><?php endif; ?></tbody></table></div><nav class="actions" aria-label="Paginação"><?php $pages=max(1,(int)ceil($total/$limit));$base='?q='.rawurlencode($query).'&status='.rawurlencode($statusFilter).'&limit='.$limit.'&page=';?><?php if($page>1):?><a class="btn secondary" href="<?=$base.($page-1)?>">Anterior</a><?php endif;?><span>Página <?=$page?> de <?=$pages?></span><?php if($page<$pages):?><a class="btn secondary" href="<?=$base.($page+1)?>">Próxima</a><?php endif;?></nav></section></main></div></div></body></html>
