<?php
declare(strict_types=1);
namespace MiniErp\Platform;
use RuntimeException;
final class TemplateSchemaInspector
{
 public function inspect(string $path):array{$sql=file_get_contents($path);if($sql===false)throw new RuntimeException('Template indisponivel.');$tables=[];preg_match_all('/CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+`?(\w+)`?\s*\((.*?)\)\s*ENGINE\s*=\s*(\w+)(?:\s+DEFAULT\s+CHARSET\s*=\s*(\w+))?(?:\s+COLLATE\s*=\s*([\w_]+))?\s*;/is',$sql,$all,PREG_SET_ORDER);foreach($all as $m){$table=['engine'=>$m[3],'collation'=>($m[5]??null),'columns'=>[],'indexes'=>[],'foreign_keys'=>[]];foreach($this->parts($m[2]) as $part){$part=trim($part);if(preg_match('/^(?:CONSTRAINT\s+`?(\w+)`?\s+)?FOREIGN\s+KEY/i',$part,$x)){$table['foreign_keys'][$x[1]?:'FK_'.count($table['foreign_keys'])]=[$part];continue;}if(preg_match('/^(PRIMARY\s+KEY|UNIQUE\s+(?:KEY|INDEX)|KEY|INDEX)\s*`?(\w*)`?/i',$part,$x)){$table['indexes'][str_starts_with(strtoupper($x[1]),'PRIMARY')?'PRIMARY':($x[2]?:'INDEX_'.count($table['indexes']))]=[$part];continue;}if(!preg_match('/^`?(\w+)`?\s+([a-z]+(?:\s*\([^)]*\))?(?:\s+UNSIGNED)?)(.*)$/is',$part,$x))continue;$r=strtoupper($x[3]);$primary=str_contains($r,'PRIMARY KEY');$table['columns'][$x[1]]=['COLUMN_TYPE'=>strtolower(preg_replace('/\s+/',' ',trim($x[2]))??trim($x[2])),'IS_NULLABLE'=>($primary||str_contains($r,'NOT NULL'))?'NO':'YES','COLUMN_DEFAULT'=>$this->default($x[3]),'COLUMN_KEY'=>$primary?'PRI':(str_contains($r,'UNIQUE')?'UNI':''),'EXTRA'=>$this->extra($r)];if($primary)$table['indexes']['PRIMARY']=[$part];if(str_contains($r,'UNIQUE'))$table['indexes'][$x[1]]=[$part];}$tables[$m[1]]=$table;}return ['database'=>'template-v1','tables'=>$tables];}
 private function parts(string $b):array{$o=[];$x='';$d=0;$q=null;for($i=0,$n=strlen($b);$i<$n;$i++){$c=$b[$i];if($q){$x.=$c;if($c===$q&&($i===0||$b[$i-1]!=='\\'))$q=null;continue;}if($c==='\''||$c==='"'){$q=$c;$x.=$c;continue;}if($c==='(')$d++;if($c===')')$d--;if($c===','&&$d===0){$o[]=$x;$x='';}else$x.=$c;}if(trim($x)!=='')$o[]=$x;return $o;}
 private function default(string $r):mixed{if(!preg_match('/\bDEFAULT\s+(NULL|CURRENT_TIMESTAMP|\'[^\']*\'|"[^"]*"|[^\s,]+)/i',$r,$m))return null;return strtoupper($m[1])==='NULL'?null:trim($m[1],"'\"");}
 private function extra(string $r):string{$parts=[];if(str_contains($r,'AUTO_INCREMENT'))$parts[]='auto_increment';if(preg_match('/ON\s+UPDATE\s+CURRENT_TIMESTAMP(?:\s*\(\s*\))?/i',$r))$parts[]='on update current_timestamp()';return implode(' ',$parts);}
}
