<?php
declare(strict_types=1);
namespace MiniErp\Platform;
use PDO;use RuntimeException;
final class TenantSchemaInspector {
 public function __construct(private PDO $server){}
 public function inspect(string $db):array{$this->assertDb($db);$tables=[];$s=$this->server->prepare('SELECT TABLE_NAME,ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_TYPE=\'BASE TABLE\' ORDER BY TABLE_NAME');$s->execute([$db]);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $t){$name=$t['TABLE_NAME'];$tables[$name]=['engine'=>$t['ENGINE'],'collation'=>$t['TABLE_COLLATION'],'columns'=>[],'indexes'=>[],'foreign_keys'=>[]];}$s=$this->server->prepare('SELECT TABLE_NAME,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,COLUMN_KEY,EXTRA,CHARACTER_SET_NAME,COLLATION_NAME,ORDINAL_POSITION FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME,ORDINAL_POSITION');$s->execute([$db]);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $c)$tables[$c['TABLE_NAME']]['columns'][$c['COLUMN_NAME']]=$c;$s=$this->server->prepare('SELECT TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME,SUB_PART,INDEX_TYPE FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX');$s->execute([$db]);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $i)$tables[$i['TABLE_NAME']]['indexes'][$i['INDEX_NAME']][]=$i;$s=$this->server->prepare('SELECT TABLE_NAME,CONSTRAINT_NAME,COLUMN_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME,ORDINAL_POSITION FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=? AND REFERENCED_TABLE_NAME IS NOT NULL ORDER BY TABLE_NAME,CONSTRAINT_NAME,ORDINAL_POSITION');$s->execute([$db]);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $f)$tables[$f['TABLE_NAME']]['foreign_keys'][$f['CONSTRAINT_NAME']][]=$f;return ['database'=>$db,'tables'=>$tables];}
 public function tableRows(string $db,string $table,int $page=1,int $limit=50):array{$schema=$this->inspect($db);if(!isset($schema['tables'][$table]))throw new RuntimeException('Tabela fora da whitelist do banco.');$limit=max(1,min(100,$limit));$page=max(1,$page);$pdo=$this->connection($db);$count=(int)$pdo->query("SELECT COUNT(*) FROM `{$table}`")->fetchColumn();$q=$pdo->query("SELECT * FROM `{$table}` LIMIT {$limit} OFFSET ".(($page-1)*$limit));$sensitive='/pass|senha|secret|token|private|pfx|certificate_content|payload/i';$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row)foreach($row as $key=>&$value)if(preg_match($sensitive,(string)$key))$value='[REDACTED]';return ['rows'=>$rows,'total'=>$count,'page'=>$page,'limit'=>$limit];}
 private function connection(string $db):PDO{$this->assertDb($db);$c=require __DIR__.'/../../config.php';$d=$c['db'];return new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',$d['host'],$d['port'],$db),$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}
 private function assertDb(string $db):void{if(!preg_match('/^mini_erp_tenant_[1-9][0-9]*$/',$db))throw new RuntimeException('Banco tenant invalido.');}
}
