<?php
declare(strict_types=1);
namespace MiniErp\Platform;

use PDO;
use RuntimeException;
use Throwable;

final class TenantCatalogImportService
{
    public const ENTITIES=['produtos','clientes','fornecedores','cfops','impostos','icms_uf'];

    public function simulate(PDO$pdo,int$tenantId,string$entity,array$inputRows,string$filename):array
    {
        if(!in_array($entity,self::ENTITIES,true))throw new RuntimeException('Tipo de cadastro inválido.');
        $valid=[];$issues=[];$keys=[];$creates=0;$updates=0;$profileReady=$entity!=='produtos'||$this->productProfileReady($pdo);
        foreach($inputRows as$input){$line=(int)($input['line']??0);try{$row=$this->normalize($entity,(array)($input['data']??[]));if($entity==='produtos'&&$this->hasProductTaxData($row['_product_taxes'])&&!$profileReady)throw new RuntimeException('O banco da empresa precisa da migration 20260902_extend_product_tax_profiles.sql para receber os impostos do produto.');$key=$this->key($entity,$row);if(isset($keys[$key]))throw new RuntimeException("Chave repetida na planilha; primeira ocorrência na linha {$keys[$key]}.");$keys[$key]=$line;$exists=$this->exists($pdo,$tenantId,$entity,$row);$row['_mode']=$exists?'update':'create';$row['_line']=$line;$valid[]=$row;$exists?$updates++:$creates++;}catch(Throwable$e){$issues[]=['line'=>$line,'message'=>$e->getMessage()];}}
        return['tenant_id'=>$tenantId,'entity'=>$entity,'filename'=>$filename,'valid_rows'=>$valid,'summary'=>['total'=>count($inputRows),'valid'=>count($valid),'create'=>$creates,'update'=>$updates,'errors'=>count($issues)],'issues'=>array_slice($issues,0,200)];
    }

    public function execute(PDO$pdo,int$tenantId,array$plan):array
    {
        $entity=(string)$plan['entity'];$rows=(array)$plan['valid_rows'];if(!$rows)throw new RuntimeException('O plano não possui linhas válidas.');$pdo->beginTransaction();$created=0;$updated=0;
        try{foreach($rows as$row){$mode=$row['_mode'];unset($row['_mode'],$row['_line']);$this->persist($pdo,$tenantId,$entity,$row,$mode);$mode==='create'?$created++:$updated++;}$pdo->commit();return['entity'=>$entity,'created'=>$created,'updated'=>$updated,'processed'=>count($rows)];}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    private function normalize(string$entity,array$raw):array
    {
        $aliases=$this->aliases($entity);$row=[];foreach($raw as$key=>$value){$canonical=$aliases[$key]??$key;if(!array_key_exists($canonical,$row)||$row[$canonical]==='')$row[$canonical]=trim((string)$value);}
        return match($entity){'produtos'=>$this->product($row),'clientes'=>$this->person($row,true),'fornecedores'=>$this->person($row,false),'cfops'=>$this->cfop($row),'impostos'=>$this->tax($row),'icms_uf'=>$this->icmsUf($row)};
    }

    private function product(array$r):array
    {
        $codigo=$this->required($r,'codigo','Código');$nome=$this->required($r,'nome','Nome/descrição');$ncm=$this->digits($r['ncm']??'');if($ncm!==''&&strlen($ncm)!==8)throw new RuntimeException('NCM deve possuir 8 dígitos.');$origem=trim($r['origem']??'');if($origem!==''&&!preg_match('/^[0-8]$/',$origem))throw new RuntimeException('Origem da mercadoria deve ser de 0 a 8.');$cfop=$this->digits($r['cfop_padrao']??'');if($cfop!==''&&strlen($cfop)!==4)throw new RuntimeException('CFOP padrão deve possuir 4 dígitos.');
        $taxes=['icms'=>$this->first($r,['csosn','sit_simples','sit']),'ipi'=>$this->first($r,['st_ipi']),'pis'=>$this->first($r,['pis_st']),'cofins'=>$this->first($r,['cofins_st']),'icms_cst'=>$this->first($r,['sit','cst_icms']),'icms_csosn'=>$this->first($r,['csosn','sit_simples']),'icms_consumer_cst'=>$this->first($r,['csosn_nfce','sit_consumidor']),'icms_rate'=>$this->nullableDecimal($this->first($r,['aliquota_icms','icms_perc'])),'pis_output_cst'=>$this->first($r,['pis_st']),'pis_output_rate'=>$this->nullableDecimal($this->first($r,['pis_perc'])),'pis_input_cst'=>$this->first($r,['pis_st_entrada']),'pis_input_rate'=>$this->nullableDecimal($this->first($r,['pis_perc_ent'])),'cofins_output_cst'=>$this->first($r,['cofins_st']),'cofins_output_rate'=>$this->nullableDecimal($this->first($r,['cofins_perc'])),'cofins_input_cst'=>$this->first($r,['cofins_st_entrada']),'cofins_input_rate'=>$this->nullableDecimal($this->first($r,['cofins_perc_ent'])),'ipi_output_cst'=>$this->first($r,['st_ipi']),'ipi_output_rate'=>$this->nullableDecimal($this->first($r,['ipi'])),'ipi_input_cst'=>$this->first($r,['st_ipi_entrada']),'source_document'=>'IMPORTAÇÃO PLANILHA DE PRODUTOS'];
        return['codigo'=>$codigo,'nome'=>$nome,'ncm'=>$ncm,'cest'=>$this->digits($r['cest']??''),'merchandise_origin'=>$origem,'tax_benefit_code'=>$this->first($r,['codigo_beneficio_fiscal','cbenef']),'unidade'=>strtoupper($r['unidade']??'UN'),'taxable_unit'=>strtoupper($this->first($r,['unidade_tributavel','unidade_trib','unidade'],'UN')),'conversion_factor'=>$this->decimal($this->first($r,['fator_conversao','quantidade_trib'],'1'),1),'gtin'=>$this->digits($this->first($r,['gtin','cean'])),'gtin_tributable'=>$this->digits($this->first($r,['gtin_tributavel','ceantrib']))?:'SEM GTIN','cfop_padrao'=>$cfop,'categoria'=>$this->first($r,['categoria','desc_categoria','grupo']),'cost_price'=>$this->decimal($this->first($r,['custo','preco_compra','preco_custo','custo_final','custo_medio_unit'],'0')),'preco'=>$this->decimal($this->first($r,['preco','preco_venda'],'0')),'estoque_atual'=>$this->decimal($r['estoque']??'0'),'minimum_stock'=>$this->decimal($r['estoque_minimo']??'0'),'status'=>$this->status($this->first($r,['status','ativo'],'ativo')),'_product_taxes'=>$taxes];
    }

    private function person(array$r,bool$customer):array
    {
        $doc=$this->digits($r['cpf_cnpj']??'');if(!in_array(strlen($doc),[11,14],true))throw new RuntimeException('CPF/CNPJ é obrigatório e deve possuir 11 ou 14 dígitos.');$name=$this->required($r,'nome','Nome/razão social');$uf=strtoupper($r['uf']??'');if($uf!==''&&!preg_match('/^[A-Z]{2}$/',$uf))throw new RuntimeException('UF deve possuir 2 letras.');$ibge=$this->digits($r['codigo_ibge']??'');if($ibge!==''&&strlen($ibge)!==7)throw new RuntimeException('Código IBGE deve possuir 7 dígitos.');
        $base=['cpf_cnpj'=>$doc,'nome'=>$name,'nome_fantasia'=>$r['nome_fantasia']??'','inscricao_estadual'=>$r['inscricao_estadual']??'','email'=>$r['email']??'','telefone'=>$r['telefone']??'','cep'=>$this->digits($r['cep']??''),'logradouro'=>$r['logradouro']??'','numero'=>$r['numero']??'','complemento'=>$r['complemento']??'','bairro'=>$r['bairro']??'','municipio'=>$r['municipio']??$r['cidade']??'','codigo_ibge'=>$ibge,'uf'=>$uf,'status'=>$this->status($r['status']??'ativo')];
        if($customer)$base+=['person_type'=>strlen($doc)===14?'PJ':'PF','state_registration_indicator'=>$r['indicador_ie']??(($r['inscricao_estadual']??'')!==''?'1':'9')];return$base;
    }

    private function cfop(array$r):array{$code=$this->digits($r['codigo']??$r['cfop']??'');if(strlen($code)!==4||!preg_match('/^[1-7]/',$code))throw new RuntimeException('CFOP deve possuir 4 dígitos e iniciar de 1 a 7.');return['codigo'=>$code,'descricao'=>$this->required($r,'descricao','Descrição'),'natureza'=>$r['natureza']??'','aplicacao'=>$r['aplicacao']??'','status'=>$this->status($r['status']??'ativo')];}
    private function tax(array$r):array
    {
        $code=$this->required($r,'codigo_regra','Código da regra');if(!preg_match('/^[A-Za-z0-9._-]{2,80}$/',$code))throw new RuntimeException('Código da regra possui formato inválido.');$ncm=$this->digits($r['ncm']??'');if(strlen($ncm)!==8)throw new RuntimeException('NCM com 8 dígitos é obrigatório para relacionar o imposto aos produtos.');$origin=$r['origem']??'';if($origin!==''&&!preg_match('/^[0-8]$/',$origin))throw new RuntimeException('Origem deve ser de 0 a 8.');$cfop=$this->digits($r['cfop']??'');if(strlen($cfop)!==4)throw new RuntimeException('CFOP com 4 dígitos é obrigatório.');$direction=strtoupper($r['direcao']??'EXIT');if(!in_array($direction,['ENTRY','EXIT'],true))throw new RuntimeException('Direção deve ser ENTRY ou EXIT.');$model=(string)($r['modelo']??'55');if(!in_array($model,['55','65'],true))throw new RuntimeException('Modelo deve ser 55 ou 65.');
        $from=$this->date($r['vigencia_inicio']??date('Y-m-d'));$to=trim($r['vigencia_fim']??'')===''?null:$this->date($r['vigencia_fim']);if($to&&$to<$from)throw new RuntimeException('Vigência final anterior à inicial.');
        return['rule_code'=>$code,'requested_version'=>(int)($r['versao']??1),'priority'=>(int)($r['prioridade']??0),'valid_from'=>$from,'valid_to'=>$to,'conditions'=>array_filter(['direction'=>$direction,'model'=>$model,'ncm'=>$ncm,'product_origin'=>$origin],fn($v)=>$v!==''),'cfop'=>$cfop,'icms'=>array_filter(['cst'=>$r['cst_icms_csosn']??$r['csosn']??$r['cst']??'','rate'=>$this->decimal($r['aliquota_icms']??'0')],fn($v)=>$v!==''),'pis'=>['cst'=>$r['cst_pis']??'','rate'=>$this->decimal($r['aliquota_pis']??'0')],'cofins'=>['cst'=>$r['cst_cofins']??'','rate'=>$this->decimal($r['aliquota_cofins']??'0')],'ipi'=>['cst'=>$r['cst_ipi']??'','rate'=>$this->decimal($r['aliquota_ipi']??'0')],'ibs_cbs'=>array_filter(['cst'=>$r['cst_ibs_cbs']??'','classification'=>$r['classificacao_tributaria']??''],fn($v)=>$v!==''),'status'=>strtoupper($r['status']??'ACTIVE')==='INACTIVE'?'INACTIVE':'ACTIVE'];
    }

    private function icmsUf(array$r):array
    {
        $uf=strtoupper($this->first($r,['uf','uf_destino']));$validUfs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];if(!in_array($uf,$validUfs,true))throw new RuntimeException($uf==='EX'?'EX representa exterior e não pode ser cadastrado como UF de ICMS.':'UF de destino inválida.');
        $from=$this->date($this->required($r,'valid_from','Vigência inicial'));$to=trim((string)($r['valid_to']??''))===''?null:$this->date($r['valid_to']);if($to&&$to<$from)throw new RuntimeException('Vigência final anterior à inicial.');
        return['uf'=>$uf,'valid_from'=>$from,'valid_to'=>$to,'juridica_rate'=>$this->nullableDecimal($this->first($r,['aliquota_interestadual','aliquota_cf','aliquota'])),'final_consumer_rate'=>$this->nullableDecimal($this->first($r,['aliquota_pf','aliquota'])),'reduction_rate'=>$this->nullableDecimal($r['aliquota_red']??''),'deferral_rate'=>$this->nullableDecimal($r['aliquota_dif']??''),'mva_rate'=>null,'simple_mva_rate'=>null,'st_rate'=>$this->nullableDecimal($r['aliquota_subst']??''),'st_reduction_rate'=>$this->nullableDecimal($r['aliquota_bcsubst']??''),'internal_rate'=>$this->nullableDecimal($r['aliquota_interna']??''),'fcp_rate'=>$this->nullableDecimal($r['aliquota_fcp']??''),'cst_csosn'=>trim((string)($r['cst_csosn']??''))?:null,'active'=>1];
    }

    private function persist(PDO$p,int$tenant,string$entity,array$r,string$mode):void
    {
        if($entity==='produtos'){$taxes=$r['_product_taxes'];unset($r['_product_taxes']);$sql="INSERT INTO produtos(codigo,nome,ncm,cest,merchandise_origin,tax_benefit_code,unidade,taxable_unit,conversion_factor,gtin,gtin_tributable,cfop_padrao,categoria,cost_price,preco,estoque_atual,minimum_stock,status) VALUES(:codigo,:nome,:ncm,:cest,:merchandise_origin,:tax_benefit_code,:unidade,:taxable_unit,:conversion_factor,:gtin,:gtin_tributable,:cfop_padrao,:categoria,:cost_price,:preco,:estoque_atual,:minimum_stock,:status) ON DUPLICATE KEY UPDATE nome=VALUES(nome),ncm=VALUES(ncm),cest=VALUES(cest),merchandise_origin=VALUES(merchandise_origin),tax_benefit_code=VALUES(tax_benefit_code),unidade=VALUES(unidade),taxable_unit=VALUES(taxable_unit),conversion_factor=VALUES(conversion_factor),gtin=VALUES(gtin),gtin_tributable=VALUES(gtin_tributable),cfop_padrao=VALUES(cfop_padrao),categoria=VALUES(categoria),cost_price=VALUES(cost_price),preco=VALUES(preco),estoque_atual=VALUES(estoque_atual),minimum_stock=VALUES(minimum_stock),status=VALUES(status)";$p->prepare($sql)->execute($r);if($this->hasProductTaxData($taxes)){$find=$p->prepare('SELECT id FROM produtos WHERE codigo=? LIMIT 1');$find->execute([$r['codigo']]);$productId=(int)$find->fetchColumn();$fields=array_keys($taxes);$insertFields=array_merge(['product_id'],$fields);$updates=implode(',',array_map(fn($f)=>"{$f}=VALUES({$f})",$fields));$save=$p->prepare('INSERT INTO product_taxes('.implode(',',$insertFields).') VALUES('.implode(',',array_fill(0,count($insertFields),'?')).') ON DUPLICATE KEY UPDATE '.$updates);$save->execute(array_merge([$productId],array_values($taxes)));}return;}
        if($entity==='clientes'){$fields=['nome','nome_fantasia','inscricao_estadual','email','telefone','cep','logradouro','numero','complemento','bairro','municipio','codigo_ibge','uf','status','person_type','state_registration_indicator'];$this->persistPerson($p,'clientes',$r,$fields,$mode);return;}
        if($entity==='fornecedores'){$fields=['nome','nome_fantasia','inscricao_estadual','email','telefone','cep','logradouro','numero','complemento','bairro','municipio','uf','status'];$this->persistPerson($p,'fornecedores',$r,$fields,$mode);return;}
        if($entity==='cfops'){$p->prepare("INSERT INTO cfops(codigo,descricao,natureza,aplicacao,status) VALUES(:codigo,:descricao,:natureza,:aplicacao,:status) ON DUPLICATE KEY UPDATE descricao=VALUES(descricao),natureza=VALUES(natureza),aplicacao=VALUES(aplicacao),status=VALUES(status)")->execute($r);return;}
        if($entity==='icms_uf'){$est=$p->prepare("SELECT id FROM establishments WHERE tenant_id=? AND is_primary=1 AND status='ativo' ORDER BY id LIMIT 1");$est->execute([$tenant]);$establishmentId=(int)$est->fetchColumn();if($establishmentId<1)throw new RuntimeException('A empresa precisa ter um estabelecimento fiscal principal antes de importar ICMS por UF.');$sql='INSERT INTO establishment_icms_defaults(tenant_id,establishment_id,uf,juridica_rate,final_consumer_rate,reduction_rate,deferral_rate,mva_rate,simple_mva_rate,st_rate,st_reduction_rate,internal_rate,fcp_rate,cst_csosn,valid_from,valid_to,active) VALUES(:tenant_id,:establishment_id,:uf,:juridica_rate,:final_consumer_rate,:reduction_rate,:deferral_rate,:mva_rate,:simple_mva_rate,:st_rate,:st_reduction_rate,:internal_rate,:fcp_rate,:cst_csosn,:valid_from,:valid_to,:active) ON DUPLICATE KEY UPDATE juridica_rate=VALUES(juridica_rate),final_consumer_rate=VALUES(final_consumer_rate),reduction_rate=VALUES(reduction_rate),deferral_rate=VALUES(deferral_rate),mva_rate=VALUES(mva_rate),simple_mva_rate=VALUES(simple_mva_rate),st_rate=VALUES(st_rate),st_reduction_rate=VALUES(st_reduction_rate),internal_rate=VALUES(internal_rate),fcp_rate=VALUES(fcp_rate),cst_csosn=VALUES(cst_csosn),valid_to=VALUES(valid_to),active=VALUES(active)';$p->prepare($sql)->execute(['tenant_id'=>$tenant,'establishment_id'=>$establishmentId]+$r);return;}
        $version=max(1,(int)$r['requested_version']);$q=$p->prepare('SELECT COALESCE(MAX(rule_version),0) FROM tax_rule_versions WHERE tenant_id=? AND rule_code=?');$q->execute([$tenant,$r['rule_code']]);$version=max($version,(int)$q->fetchColumn()+1);$stmt=$p->prepare('INSERT INTO tax_rule_versions(tenant_id,rule_code,rule_version,priority,valid_from,valid_to,source_document,source_version,source_date,conditions_json,cfop,icms_json,ipi_json,pis_json,cofins_json,ibs_cbs_json,selective_tax_json,status,fixture_kind) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$json=fn($v)=>json_encode($v,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$stmt->execute([$tenant,$r['rule_code'],$version,$r['priority'],$r['valid_from'],$r['valid_to'],'IMPORTAÇÃO PLANILHA','v'.$version,date('Y-m-d'),$json($r['conditions']),$r['cfop'],$json($r['icms']),$json($r['ipi']),$json($r['pis']),$json($r['cofins']),$json($r['ibs_cbs']),$json([]),$r['status'],'PRODUCTION']);
    }

    private function persistPerson(PDO$p,string$table,array$r,array$fields,string$mode):void
    {
        if($mode==='update'){$sets=implode(',',array_map(fn($field)=>"{$field}=:{$field}",$fields));$sql="UPDATE {$table} SET {$sets} WHERE cpf_cnpj=:cpf_cnpj ORDER BY id LIMIT 1";}
        else{$columns=array_merge(['cpf_cnpj'],$fields);$sql="INSERT INTO {$table}(".implode(',',$columns).') VALUES('.implode(',',array_map(fn($field)=>":{$field}",$columns)).')';}
        $params=['cpf_cnpj'=>$r['cpf_cnpj']];foreach($fields as$field)$params[$field]=$r[$field]??'';$p->prepare($sql)->execute($params);
    }
    private function exists(PDO$p,int$tenant,string$entity,array$r):bool{$query=match($entity){'produtos'=>['SELECT 1 FROM produtos WHERE codigo=? LIMIT 1',$r['codigo']],'clientes','fornecedores'=>["SELECT 1 FROM {$entity} WHERE cpf_cnpj=? LIMIT 1",$r['cpf_cnpj']],'cfops'=>['SELECT 1 FROM cfops WHERE codigo=? LIMIT 1',$r['codigo']],'icms_uf'=>['SELECT 1 FROM establishment_icms_defaults WHERE tenant_id=? AND uf=? AND valid_from=? LIMIT 1',[$tenant,$r['uf'],$r['valid_from']]],default=>['SELECT 1 FROM tax_rule_versions WHERE tenant_id=? AND rule_code=? LIMIT 1',[$tenant,$r['rule_code']]]};$s=$p->prepare($query[0]);$s->execute(is_array($query[1])?$query[1]:[$query[1]]);return(bool)$s->fetchColumn();}
    private function key(string$entity,array$r):string{return match($entity){'produtos'=>$r['codigo'],'clientes','fornecedores'=>$r['cpf_cnpj'],'cfops'=>$r['codigo'],'icms_uf'=>$r['uf'].'|'.$r['valid_from'],default=>$r['rule_code'].'|'.$r['conditions']['ncm'].'|'.$r['conditions']['direction'].'|'.$r['conditions']['model']};}
    private function aliases(string$entity):array
    {
        $aliases=['codigo_ncm'=>'ncm','sku'=>'codigo','code'=>'codigo','cbenef'=>'codigo_beneficio_fiscal','origem_mercadoria'=>'origem','unidade_comercial'=>'unidade','custo_unitario'=>'custo','preco_venda'=>'preco','estoque_atual'=>'estoque','documento'=>'cpf_cnpj','cnpj'=>'cpf_cnpj','cpf'=>'cpf_cnpj','razao_social'=>'nome','ie'=>'inscricao_estadual','cidade'=>'municipio','codigo_municipal'=>'codigo_ibge'];
        if($entity==='impostos')$aliases['sit']='cst';
        if($entity==='produtos'){$aliases['descricao']='nome';$aliases['cean']='gtin';$aliases['ceantrib']='gtin_tributavel';$aliases['unidade_trib']='unidade_tributavel';}
        if($entity==='cfops')$aliases['cfop']='codigo';elseif($entity==='produtos')$aliases['cfop']='cfop_padrao';
        return$aliases;
    }
    private function required(array$r,string$key,string$label):string{$v=trim((string)($r[$key]??''));if($v==='')throw new RuntimeException("{$label} é obrigatório.");return$v;}
    private function digits(string$v):string{return preg_replace('/\D+/','',$v)??'';}
    private function decimal(string$v,float$default=0):string{$v=trim($v);if($v==='')return(number_format($default,6,'.',''));$v=str_replace(['R$',' ','%'],'',$v);if(str_contains($v,',')&&str_contains($v,'.'))$v=str_replace('.','',$v);$v=str_replace(',','.',$v);if(!is_numeric($v))throw new RuntimeException("Valor numérico inválido: {$v}.");return number_format((float)$v,6,'.','');}
    private function nullableDecimal(string$v):?string{return trim($v)===''?null:$this->decimal($v);}
    private function date(string$v):string{$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v)?:\DateTimeImmutable::createFromFormat('!d/m/Y',$v);if(!$d)throw new RuntimeException("Data inválida: {$v}.");return$d->format('Y-m-d');}
    private function status(string$v):string{return in_array(strtolower(trim($v)),['inativo','inactive','n','0'],true)?'inativo':'ativo';}
    private function first(array$r,array$keys,string$default=''):string{foreach($keys as$key)if(isset($r[$key])&&trim((string)$r[$key])!=='')return trim((string)$r[$key]);return$default;}
    private function hasProductTaxData(array$taxes):bool{unset($taxes['source_document']);return(bool)array_filter($taxes,fn($v)=>$v!==''&&$v!==null);}
    private function productProfileReady(PDO$p):bool{try{$p->query('SELECT icms_cst FROM product_taxes WHERE 1=0');return true;}catch(Throwable){return false;}}
}
