<?php
declare(strict_types=1);
namespace MiniErp\Platform;
final class TenantSchemaComparator
{
 public function compare(array $expected,array $actual):array{$d=[];$e=$expected['tables'];$a=$actual['tables'];foreach(array_diff_key($e,$a) as $t=>$_)$d[]=['kind'=>'MISSING_TABLE','table'=>$t];foreach(array_diff_key($a,$e) as $t=>$_)$d[]=['kind'=>'EXTRA_TABLE','table'=>$t];foreach(array_intersect_key($e,$a) as $t=>$et){$at=$a[$t];if(strtolower((string)$et['engine'])!==strtolower((string)$at['engine']))$d[]=['kind'=>'TABLE_PROPERTY','table'=>$t,'property'=>'engine'];if(($et['collation']??null)!==null&&strtolower((string)$et['collation'])!==strtolower((string)$at['collation']))$d[]=['kind'=>'TABLE_PROPERTY','table'=>$t,'property'=>'collation'];foreach(array_diff_key($et['columns'],$at['columns']) as $c=>$_)$d[]=['kind'=>'MISSING_COLUMN','table'=>$t,'column'=>$c];foreach(array_diff_key($at['columns'],$et['columns']) as $c=>$_)$d[]=['kind'=>'EXTRA_COLUMN','table'=>$t,'column'=>$c];foreach(array_intersect_key($et['columns'],$at['columns']) as $c=>$ec){$ac=$at['columns'][$c];if($this->type($ec['COLUMN_TYPE'])!==$this->type($ac['COLUMN_TYPE']))$d[]=['kind'=>'COLUMN_PROPERTY','table'=>$t,'column'=>$c,'property'=>'type','expected'=>$ec['COLUMN_TYPE'],'actual'=>$ac['COLUMN_TYPE']];foreach(['IS_NULLABLE','EXTRA'] as $p)if(strtolower((string)$ec[$p])!==strtolower((string)$ac[$p]))$d[]=['kind'=>'COLUMN_PROPERTY','table'=>$t,'column'=>$c,'property'=>$p];if(!$this->sameDefault($ec['COLUMN_DEFAULT'],$ac['COLUMN_DEFAULT']))$d[]=['kind'=>'COLUMN_PROPERTY','table'=>$t,'column'=>$c,'property'=>'default'];}foreach(array_diff_key($et['indexes'],$at['indexes']) as $i=>$_)$d[]=['kind'=>'MISSING_INDEX','table'=>$t,'index'=>$i];foreach(array_diff_key($at['indexes'],$et['indexes']) as $i=>$_)if(!isset($at['foreign_keys'][$i]))$d[]=['kind'=>'EXTRA_INDEX','table'=>$t,'index'=>$i];foreach(array_diff_key($et['foreign_keys'],$at['foreign_keys']) as $f=>$_)$d[]=['kind'=>'MISSING_FK','table'=>$t,'foreign_key'=>$f];foreach(array_diff_key($at['foreign_keys'],$et['foreign_keys']) as $f=>$_)$d[]=['kind'=>'EXTRA_FK','table'=>$t,'foreign_key'=>$f];}return ['status'=>$d===[]?'CURRENT':'OUTDATED_OR_DRIFT','differences'=>$d,'count'=>count($d)];}
 private function type(string $v):string{$v=strtolower(trim(preg_replace('/\s+/',' ',$v)??$v));$v=preg_replace('/\b(tinyint|smallint|mediumint|int|bigint)\(\d+\)/','$1',$v)??$v;$v=preg_replace('/\b(?:bool|boolean)\b/','tinyint',$v)??$v;return $v==='json'?'longtext':$v;}
 private function sameDefault(mixed $a,mixed $b):bool{$a=$this->default($a);$b=$this->default($b);if($a===null||$b===null)return $a===null&&$b===null;if(is_numeric($a)&&is_numeric($b))return bccomp((string)$a,(string)$b,8)===0;return $a===$b;}
 private function default(mixed $value):?string{if($value===null)return null;$value=trim((string)$value);if(strcasecmp($value,'NULL')===0)return null;if(strlen($value)>=2&&(($value[0]==="'"&&$value[-1]==="'")||($value[0]==='"'&&$value[-1]==='"')))$value=substr($value,1,-1);$value=strtolower(trim($value));$value=preg_replace('/^current_timestamp\s*\(\s*\)$/','current_timestamp',$value)??$value;return preg_replace('/^\((.*)\)$/','$1',$value)??$value;}
}
