<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Fiscal\{A1CertificateInspector,FiscalMasterKey,LocalEncryptedSecretStorage,PrivateCertificateStorage};use MiniErp\Repositories\{FiscalConfigurationRepository,TenantEstablishmentRepository};use MiniErp\Services\{EstablishmentData,EstablishmentFiscalConfigurationService,EstablishmentService};
if(session_status()!==PHP_SESSION_ACTIVE)session_start();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$tenant=(int)($_SESSION['erp_tenant_id']??0);$user=(int)($_SESSION['erp_user_id']??0);$area=(string)($_POST['form_area']??'');
if($tenant<1||$user<1){http_response_code(401);exit(json_encode(['success'=>false,'message'=>'Sessão expirada.']));}
if(($_SERVER['HTTP_SEC_FETCH_SITE']??'same-origin')==='cross-site'){http_response_code(403);exit(json_encode(['success'=>false,'message'=>'Origem não permitida.']));}
try{$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$main=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['database']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
 if($area==='profile'){
  if(!hash_equals((string)($_SESSION['erp_company_csrf']??''),(string)($_POST['csrf']??'')))throw new RuntimeException('CSRF_INVALID');
  $name=mb_substr(trim((string)($_POST['nome_fantasia']??'')),0,150);$legal=mb_substr(trim((string)($_POST['razao_social']??'')),0,150);$cnpj=preg_replace('/\D/','',(string)($_POST['cnpj']??''));if($name===''||$legal===''||strlen((string)$cnpj)!==14)throw new InvalidArgumentException('Revise razão social, nome fantasia e CNPJ.');
  $q=$main->prepare('UPDATE tenants SET nome_fantasia=?,razao_social=?,cnpj=?,telefone=?,cep=?,logradouro=?,numero=?,complemento=?,bairro=?,municipio=?,uf=?,codigo_ibge=? WHERE id=?');$q->execute([$name,$legal,$cnpj,mb_substr(trim((string)($_POST['telefone']??'')),0,30),preg_replace('/\D/','',(string)($_POST['cep']??'')),mb_substr(trim((string)($_POST['logradouro']??'')),0,150),mb_substr(trim((string)($_POST['numero']??'')),0,20),mb_substr(trim((string)($_POST['complemento']??'')),0,100),mb_substr(trim((string)($_POST['bairro']??'')),0,100),mb_substr(trim((string)($_POST['municipio']??'')),0,100),strtoupper(mb_substr(trim((string)($_POST['uf']??'')),0,2)),preg_replace('/\D/','',(string)($_POST['codigo_ibge']??'')),$tenant]);if($q->rowCount()>1)throw new RuntimeException('UPDATE_SCOPE_INVALID');error_log('ERP_COMPANY_PROFILE_SAVED tenant='.$tenant.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Alterações salvas.','company'=>['name'=>$name,'legal_name'=>$legal,'cnpj'=>$cnpj]],JSON_UNESCAPED_UNICODE);exit;
 }
 if(in_array($area,['fiscal','certificate','series'],true)){
  if(!hash_equals((string)($_SESSION['erp_establishment_csrf']??''),(string)($_POST['csrf_token']??'')))throw new RuntimeException('CSRF_INVALID');$q=$main->prepare('SELECT db_name FROM tenants WHERE id=?');$q->execute([$tenant]);$db=(string)$q->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$db))throw new RuntimeException('TENANT_NOT_FOUND');$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$db};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$estRepo=new TenantEstablishmentRepository($pdo);
  if($area==='fiscal'){$saved=(new EstablishmentService($estRepo))->save($tenant,new EstablishmentData($_POST));error_log('ERP_COMPANY_FISCAL_SAVED tenant='.$tenant.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Cadastro fiscal salvo.','establishment_id'=>(int)$saved['id']],JSON_UNESCAPED_UNICODE);exit;}
  $est=$estRepo->findPrimaryForTenant($tenant);if(!$est)throw new RuntimeException('ESTABLISHMENT_REQUIRED');$configRepo=new FiscalConfigurationRepository($pdo,$tenant);
  if($area==='series'){$configRepo->saveSeries((int)$est['id'],(string)($_POST['model']??''),(int)($_POST['series']??-1),(int)($_POST['next_number']??0),2,($_POST['active']??'0')==='1',$user,mb_substr(trim((string)($_POST['reason']??'')),0,500));error_log('ERP_COMPANY_SERIES_SAVED tenant='.$tenant.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Série fiscal salva e auditada.'],JSON_UNESCAPED_UNICODE);exit;}
  $service=new EstablishmentFiscalConfigurationService($configRepo,new A1CertificateInspector(),new PrivateCertificateStorage(__DIR__.'/../storage/fiscal/certificates'),new LocalEncryptedSecretStorage(__DIR__.'/../storage/fiscal/secrets',FiscalMasterKey::resolve(__DIR__.'/..')),$tenant);$certificateAction=(string)($_POST['certificate_action']??'');$diagnostic=null;if($certificateAction==='upload'){$file=$_FILES['certificate']??[];if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file((string)($file['tmp_name']??'')))throw new InvalidArgumentException('Selecione um arquivo PFX/P12 válido.');$diagnostic=$service->upload((int)$est['id'],(string)$file['name'],(string)file_get_contents((string)$file['tmp_name']),(string)($_POST['password']??''),(string)$est['tax_id'],$user);$message=!empty($diagnostic['activated'])?'Certificado salvo, relido e ativado para uso fiscal.':'Certificado salvo e assinatura local aprovada. Ele permanece inativo porque a identidade fiscal não corresponde à empresa.';}elseif($certificateAction==='test'){$diagnostic=$service->test((int)$est['id'],(string)$est['tax_id']);$message=!empty($diagnostic['operational'])?'Certificado relido: assinatura e identidade fiscal aprovadas.':'Certificado relido e assinatura local aprovada, mas a identidade fiscal continua incompatível.';}elseif($certificateAction==='remove'){$service->deactivate((int)$est['id'],$user,'Desativação pelo painel ERP');$message='Certificado desativado.';}else throw new RuntimeException('INVALID_CERTIFICATE_ACTION');error_log('ERP_COMPANY_CERTIFICATE_ACTION tenant='.$tenant.' actor='.$user.' action='.$certificateAction);echo json_encode(['success'=>true,'message'=>$message,'certificate'=>$diagnostic?['id'=>(int)($diagnostic['certificate_id']??0),'stored'=>(bool)($diagnostic['stored']??true),'local_signature'=>(bool)($diagnostic['local_signature']??true),'operational'=>(bool)($diagnostic['operational']??false),'status'=>(string)($diagnostic['status']??''),'identity_status'=>(string)($diagnostic['identity_status']??'')]:null],JSON_UNESCAPED_UNICODE);exit;
 }
 throw new RuntimeException('INVALID_AREA');
}catch(Throwable$e){http_response_code(422);error_log('ERP_COMPANY_SAVE_FAILED tenant='.$tenant.' type='.get_class($e));$message=$e->getMessage()==='CSRF_INVALID'?'Sessão do formulário expirada. Recarregue a página.':($e instanceof InvalidArgumentException?$e->getMessage():'Não foi possível salvar. Os dados foram mantidos.');echo json_encode(['success'=>false,'message'=>$message],JSON_UNESCAPED_UNICODE);}
