<?php
declare(strict_types=1);
use MiniErp\Infrastructure\ControlPlaneConnectionFactory;
require_once __DIR__.'/../vendor/autoload.php';
if(session_status()!==PHP_SESSION_ACTIVE)session_start();header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: private, no-store');
$tenantId=(int)($_SESSION['erp_tenant_id']??$_SESSION['tenant_id']??0);$userId=(int)($_SESSION['erp_user_id']??$_SESSION['user_id']??$_SESSION['erp_global_admin_id']??0);if($tenantId<1||$userId<1){http_response_code(401);echo json_encode(['success'=>false,'message'=>'Sessão expirada.']);exit;}
try{$type=(string)($_GET['type']??'');$query=mb_substr(trim((string)($_GET['q']??'')),0,80);$main=(new ControlPlaneConnectionFactory(__DIR__.'/../config.php'))->create();
 if($type==='ncm'){$digits=preg_replace('/\D/','',$query);$like='%'.str_replace(['%','_'],['\\%','\\_'],$query).'%';$sql="SELECT e.code,e.description FROM platform_fiscal_catalog_entries e JOIN platform_fiscal_catalog_versions v ON v.id=e.version_id WHERE v.catalog_type='NCM' AND v.active=1 AND (e.code LIKE ? OR e.description LIKE ?) ORDER BY CASE WHEN e.code LIKE ? THEN 0 ELSE 1 END,e.code LIMIT 30";$s=$main->prepare($sql);$s->execute(['%'.$digits.'%',$like,($digits?:'~').'%']);$rows=$s->fetchAll(PDO::FETCH_ASSOC);}
 elseif($type==='cfop'){$tenant=$main->prepare('SELECT db_name FROM tenants WHERE id=? AND blocked=0 LIMIT 1');$tenant->execute([$tenantId]);$db=(string)$tenant->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$db))throw new RuntimeException('Empresa inválida.');$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$db};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$like='%'.str_replace(['%','_'],['\\%','\\_'],$query).'%';$s=$pdo->prepare("SELECT codigo AS code,descricao AS description,natureza,aplicacao FROM cfops WHERE status='ativo' AND (codigo LIKE ? OR descricao LIKE ?) ORDER BY codigo LIMIT 30");$s->execute([$like,$like]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);}
 else throw new RuntimeException('Catálogo inválido.');echo json_encode(['success'=>true,'rows'=>$rows],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
}catch(Throwable$e){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Catálogo fiscal indisponível. Solicite a atualização ao administrador.'],JSON_UNESCAPED_UNICODE);}
