<?php
declare(strict_types=1);
use MiniErp\Repositories\FiscalOperationRepository;
require_once __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/includes/fiscal_preview.php';
if(session_status()!==PHP_SESSION_ACTIVE)session_start();$tenantId=(int)($_SESSION['erp_tenant_id']??$_SESSION['tenant_id']??0);$userId=(int)($_SESSION['erp_user_id']??$_SESSION['user_id']??0);if($tenantId<1||$userId<1){http_response_code(401);exit('Sessão expirada.');}
try{
    $cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$main=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['database']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$query=$main->prepare('SELECT db_name FROM tenants WHERE id=?');$query->execute([$tenantId]);$db=(string)$query->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$db))throw new RuntimeException('Tenant inválido.');$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$db};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$mirrorId=filter_input(INPUT_GET,'mirror_id',FILTER_VALIDATE_INT)?:filter_var($_GET['mirror_id']??0,FILTER_VALIDATE_INT);$mirror=(new FiscalOperationRepository($pdo,$tenantId))->mirror((int)$mirrorId);$order=$mirror['snapshot'];
    $issuer=[];$issuerQuery=$pdo->prepare('SELECT * FROM establishments WHERE id=? AND tenant_id=? LIMIT 1');$issuerQuery->execute([(int)($order['establishment_id']??0),$tenantId]);$issuer=$issuerQuery->fetch()?:[];
    $recipient=[];$personTable=($order['operation_type']??'EXIT')==='ENTRY'?'fornecedores':'clientes';if(preg_match('/^(clientes|fornecedores)$/',$personTable)){$personQuery=$pdo->prepare("SELECT * FROM {$personTable} WHERE id=? LIMIT 1");$personQuery->execute([(int)($order['person_id']??0)]);$recipient=$personQuery->fetch()?:[];}
    $document=['mirror_id'=>(int)$mirror['id'],'source_order_id'=>(int)$mirror['source_order_id'],'snapshot_version'=>(int)$mirror['snapshot_version'],'issuer_snapshot'=>$issuer,'recipient_snapshot'=>$recipient,'payment_snapshot'=>['method'=>$order['payment_method']??'','amount'=>$order['grand_total']??''],'transport_snapshot'=>['freight_mode'=>$order['freight_mode']??'9'],'totals'=>['model'=>$order['fiscal_model']??'55','operation_type'=>$order['operation_type']??'EXIT','operation_nature'=>$order['operation_nature']??'','operation_date'=>$order['operation_date']??'','products'=>$order['products_total']??'','discount'=>$order['discount_amount']??'','freight'=>$order['freight_amount']??'','other'=>$order['other_amount']??'','grand'=>$order['grand_total']??'','notes'=>$order['notes']??''],'items'=>array_map(static fn(array $item):array=>['product_snapshot_json'=>json_encode($item,JSON_UNESCAPED_UNICODE),'quantity_commercial'=>$item['quantity']??'','unit_value_commercial'=>$item['unit_price']??'','net_total'=>$item['net_total']??''], $order['items']??[]),'pending'=>[]];
}catch(Throwable $exception){error_log('FISCAL_MIRROR_RENDER_FAILED tenant='.$tenantId.' code='.get_class($exception));http_response_code(404);exit('Espelho não encontrado.');}
header('Content-Type: text/html; charset=UTF-8');
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Espelho fiscal sem valor fiscal</title><link rel="stylesheet" href="/assets/style.css"><style>html,body{background:#fff!important;color:#111!important}body{padding:20px;margin:0}.fiscal-preview{display:block!important;visibility:visible!important;position:relative;background:#fff;padding:24px}.preview-watermark{position:absolute;inset:38% 0 auto;font-size:54px;opacity:.12;transform:rotate(-20deg);text-align:center}.preview-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.fiscal-preview table{width:100%}@media print{html,body,body *{visibility:visible!important}.fiscal-preview{display:block!important;position:static!important;margin:0!important}.preview-actions{display:none!important}}</style></head><body class="page-ready"><main id="fiscal-print-root" data-legacy-root="fiscal-mirror-a4"><?php renderFiscalPreview($document);?></main><?php if(($_GET['print']??'')==='1'):?><script>addEventListener('load',()=>window.print())</script><?php endif?></body></html>
