<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use MiniErp\Fiscal\TaxRuleResolver;use MiniErp\Repositories\{FiscalDocumentEventRepository,FiscalOperationRepository,MariaDbTaxRuleRepository};use MiniErp\Services\{CreateInternalFiscalDocumentService,FiscalLocalPipelineFactory,IssuedOrderManagementService};
if(session_status()!==PHP_SESSION_ACTIVE)session_start();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');$tenant=(int)($_SESSION['erp_tenant_id']??$_SESSION['tenant_id']??0);$user=(int)($_SESSION['erp_user_id']??$_SESSION['user_id']??0);$csrf=(string)($_POST['csrf']??'');if($tenant<1||$user<1){http_response_code(401);exit(json_encode(['success'=>false,'message'=>'Sessão expirada.']));}if($csrf===''||!hash_equals((string)($_SESSION['erp_fiscal_csrf']??''),$csrf)){http_response_code(403);exit(json_encode(['success'=>false,'message'=>'Sessão fiscal inválida.']));}if(($_SERVER['HTTP_SEC_FETCH_SITE']??'same-origin')==='cross-site'){http_response_code(403);exit(json_encode(['success'=>false,'message'=>'Origem não permitida.']));}$action=(string)($_POST['order_action']??'');$orderId=filter_input(INPUT_POST,'order_id',FILTER_VALIDATE_INT)?:0;$documentId=0;
if(empty($_SESSION['erp_global_admin_id'])){try{$policyMain=(new \MiniErp\Infrastructure\ControlPlaneConnectionFactory(__DIR__.'/../config.php'))->create();$policy=(new \MiniErp\Repositories\TenantAccessPolicyRepository($policyMain))->effectiveForTenant($tenant);if(($policy['access_mode']??'FULL')==='READ_ONLY'&&in_array($action,['clone','delete','issue'],true)){http_response_code(403);exit(json_encode(['success'=>false,'message'=>'Empresa em modo somente consulta.']));}if($action==='issue'&&empty($policy['can_issue_fiscal'])){http_response_code(403);exit(json_encode(['success'=>false,'message'=>'Emissão fiscal bloqueada pelo Painel da Plataforma.']));}}catch(Throwable$policyError){error_log('ISSUED_POLICY_READ_FAILED tenant='.$tenant.' type='.get_class($policyError));}}
try{$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$main=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['database']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$s=$main->prepare('SELECT db_name FROM tenants WHERE id=?');$s->execute([$tenant]);$db=(string)$s->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$db))throw new RuntimeException('TENANT_NOT_FOUND');$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$db};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$operations=new FiscalOperationRepository($pdo,$tenant);$management=new IssuedOrderManagementService($pdo,$operations);
 if($action==='preview'){$operations->order($orderId);error_log('FISCAL_PREVIEW_REQUESTED tenant='.$tenant.' order='.$orderId.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Prévia fiscal solicitada.','preview_url'=>'fiscal_danfe_preview.php?order_id='.$orderId],JSON_UNESCAPED_UNICODE);exit;}
 if($action==='clone'){$clone=$management->clone($orderId,$user);echo json_encode(['success'=>true,'message'=>'Pedido clonado com sucesso.','redirect'=>'?page=pedidos&tab=saida&order_id='.$clone,'order_id'=>$clone],JSON_UNESCAPED_UNICODE);exit;}
 if($action==='delete'){$deleted=$management->delete($orderId,$user);echo json_encode(['success'=>true,'message'=>$deleted?'Pedido excluído.':'Pedido já estava excluído.','redirect'=>'?page=pedidos&tab=emitidos'],JSON_UNESCAPED_UNICODE);exit;}
 if($action==='issue'){$operations->order($orderId);$token=strtolower(trim((string)($_POST['idempotency_key']??'')));if(!preg_match('/^[a-f0-9]{64}$/',$token))throw new RuntimeException('INVALID_IDEMPOTENCY_TOKEN');error_log('FISCAL_ISSUE_REQUESTED tenant='.$tenant.' order='.$orderId.' actor='.$user);$creator=new CreateInternalFiscalDocumentService($operations,new TaxRuleResolver(new MariaDbTaxRuleRepository($pdo,$tenant)));$document=$creator->create($orderId,$token,$user);$documentId=(int)$document['id'];$events=new FiscalDocumentEventRepository($pdo,$tenant);if(!$events->timeline($documentId))$events->append($documentId,'DOCUMENT_CREATED','PRECHECK',(string)$document['status'],(string)$document['status'],$document['pending']?implode('; ',$document['pending']):'Documento pronto para preparação local.',[],$user);if($document['status']!=='FISCAL_READY')throw new RuntimeException('FISCAL_PREFLIGHT_FAILED');FiscalLocalPipelineFactory::create($pdo,$tenant,dirname(__DIR__))->prepare($tenant,$documentId,$user);echo json_encode(['success'=>true,'message'=>'Preparação fiscal concluída. Transmissão SEFAZ ainda não executada.','redirect'=>'/?page=fiscal_notes&highlight='.$documentId.'&context=emit'],JSON_UNESCAPED_UNICODE);exit;}
 throw new RuntimeException('INVALID_ACTION');
}catch(Throwable$e){http_response_code(422);$raw=$e->getMessage();$messages=['ORDER_HAS_FISCAL_RESERVATION'=>'Este pedido possui numeração fiscal reservada e não pode ser excluído.','ORDER_HAS_FISCAL_DOCUMENT'=>'Este pedido possui documento fiscal e não pode ser excluído.','ORDER_HAS_DEPENDENCIES'=>'Este pedido possui dependências e não pode ser excluído.','ORDER_DELETE_CONCURRENT'=>'O pedido já foi processado por outra solicitação.','FISCAL_PREFLIGHT_FAILED'=>'A emissão foi bloqueada por pendências fiscais.','INVALID_ACTION'=>'Ação de pedido inválida.'];$code=array_key_exists($raw,$messages)?$raw:'ORDER_ACTION_FAILED';$message=$messages[$code]??'Não foi possível concluir a operação.';error_log('ISSUED_ORDER_ACTION_FAILED tenant='.$tenant.' order='.$orderId.' action='.$action.' stage=endpoint type='.get_class($e).' code='.$code);echo json_encode(['success'=>false,'message'=>$message,'error_code'=>$code,'redirect'=>$action==='issue'?'?page=fiscal_notes'.($documentId?'&highlight='.$documentId:'').'&context=error':null],JSON_UNESCAPED_UNICODE);}
