<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/../app/Database.php';require_once __DIR__.'/../app/Repository.php';
use MiniErp\Repositories\MasterDataDirectoryRepository;use MiniErp\Services\EmployeeAccessService;use MiniErp\Services\PeoplePersistenceService;
if(session_status()!==PHP_SESSION_ACTIVE)session_start();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$tenant=(int)($_SESSION['erp_tenant_id']??0);$actor=(int)($_SESSION['erp_user_id']??0);if($tenant<1||$actor<1){http_response_code(401);exit(json_encode(['success'=>false,'message'=>'Sessão expirada.']));}
try{
    $cfg=require __DIR__.'/../config.php';$dbCfg=$cfg['db'];$options=[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC];
    $main=new PDO("mysql:host={$dbCfg['host']};port={$dbCfg['port']};dbname={$dbCfg['database']};charset=utf8mb4",$dbCfg['username'],$dbCfg['password'],$options);
    $lookup=$main->prepare('SELECT db_name FROM tenants WHERE id=?');$lookup->execute([$tenant]);$dbName=(string)$lookup->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$dbName))throw new RuntimeException('TENANT_NOT_FOUND');
    $pdo=new PDO("mysql:host={$dbCfg['host']};port={$dbCfg['port']};dbname={$dbName};charset=utf8mb4",$dbCfg['username'],$dbCfg['password'],$options);$directory=new MasterDataDirectoryRepository($pdo,$tenant);$access=new EmployeeAccessService($main,$tenant,$actor);
    $documentExists=static function(string $document,int $exceptClientId=0)use($pdo):bool{$clean="UPPER(REPLACE(REPLACE(REPLACE(REPLACE(%s,'.',''),'/',''),'-',''),' ',''))";if($exceptClientId>0){$stmt=$pdo->prepare("SELECT id FROM clientes WHERE ".sprintf($clean,'cpf_cnpj')."=? AND id<>? LIMIT 1");$stmt->execute([$document,$exceptClientId]);return(bool)$stmt->fetchColumn();}$parts=[sprintf("SELECT id FROM clientes WHERE ".sprintf($clean,'cpf_cnpj')."=?"),sprintf("SELECT id FROM fornecedores WHERE ".sprintf($clean,'cpf_cnpj')."=?"),sprintf("SELECT id FROM transportadoras WHERE ".sprintf($clean,'cpf_cnpj')."=?"),sprintf("SELECT id FROM motoristas WHERE ".sprintf($clean,'cpf')."=?")];$stmt=$pdo->prepare(implode(' UNION ALL ',$parts).' LIMIT 1');$stmt->execute([$document,$document,$document,$document]);return(bool)$stmt->fetchColumn();};
    if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){
        if(($_GET['operation']??'')==='check_document'){$document=strtoupper(preg_replace('/[^A-Z0-9]/','',(string)($_GET['document']??''))??'');$exceptId=(int)($_GET['except_id']??0);if(!in_array(strlen($document),[11,14],true))throw new InvalidArgumentException('Informe um CPF ou CNPJ completo.');$exists=$documentExists($document,$exceptId);echo json_encode(['success'=>true,'available'=>!$exists,'message'=>$exists?'Este CPF/CNPJ já está cadastrado. Abra o cadastro existente ou informe outro documento.':'Documento disponível.'],JSON_UNESCAPED_UNICODE);exit;}
        $type=(string)($_GET['type']??'');$id=(int)($_GET['id']??0);if($id<1)throw new RuntimeException('RECORD_NOT_FOUND');$record=$directory->record($type,$id);$employeeAccess=$type==='cliente'?$access->findByEmail((string)($record['email']??'')):null;
        echo json_encode(['success'=>true,'record'=>$record,'employee_access'=>$employeeAccess],JSON_UNESCAPED_UNICODE);exit;
    }
    if(($_SERVER['HTTP_SEC_FETCH_SITE']??'same-origin')==='cross-site')throw new RuntimeException('ORIGIN_INVALID');if(!hash_equals((string)($_SESSION['erp_master_data_csrf']??''),(string)($_POST['csrf']??'')))throw new RuntimeException('CSRF_INVALID');
    // Keep the unified and legacy aliases canonical. Otherwise duplicate
    // validation could inspect a different CPF from the one being persisted.
    $documentFromAlias=(string)($_POST['document'] ?? ($_POST['cpf_cnpj'] ?? ''));
    $canonicalDocument=strtoupper(preg_replace('/[^A-Z0-9]/i','',$documentFromAlias)??'');
    if($documentFromAlias!==''||isset($_POST['document'])||isset($_POST['cpf_cnpj'])){$_POST['document']=$canonicalDocument;$_POST['cpf_cnpj']=$canonicalDocument;}
    if((isset($_POST['document_type'])||isset($_POST['document']))&&!isset($_POST['person_type'])){$_POST['person_type']=match(strtoupper((string)($_POST['document_type'] ?? ''))){'CPF'=>'PF','CNPJ'=>'PJ','FOREIGN'=>'FOREIGN',default=>$_POST['person_type'] ?? 'PF'};}
    $entity=(string)($_POST['entity']??'');$operation=(string)($_POST['operation']??'save');$source=(string)($_POST['source_type']??'');$id=(int)($_POST['id']??0);
    if(str_starts_with($operation,'employee_access_')){
        if($entity!=='person'||$source!=='cliente'||$id<1)throw new InvalidArgumentException('Salve primeiro a pessoa como funcionário.');$person=$directory->record('cliente',$id);$types=array_filter(array_map('trim',explode(',',(string)($person['tipo_pessoa']??''))));if(!in_array('funcionario',$types,true))throw new InvalidArgumentException('Marque e salve a pessoa como Funcionário antes de criar o login.');
        if($operation==='employee_access_create')$record=$access->create((string)$person['nome'],(string)$person['email'],(string)($_POST['access_password']??''),(string)($_POST['access_password_confirmation']??''));
        elseif($operation==='employee_access_password'){$access->resetPassword((int)($_POST['access_id']??0),(string)($_POST['access_password']??''),(string)($_POST['access_password_confirmation']??''));$record=$access->findByEmail((string)$person['email']);}
        elseif($operation==='employee_access_status'){$access->setStatus((int)($_POST['access_id']??0),(string)($_POST['access_status']??''));$record=$access->findByEmail((string)$person['email']);}
        else throw new InvalidArgumentException('Operação de acesso inválida.');
        error_log('EMPLOYEE_ACCESS_CHANGED tenant='.$tenant.' person='.$id.' actor='.$actor.' operation='.$operation);echo json_encode(['success'=>true,'message'=>'Acesso do funcionário atualizado.','employee_access'=>$record],JSON_UNESCAPED_UNICODE);exit;
    }
    $repo=new Repository($pdo,false);$peoplePersistence=new PeoplePersistenceService($pdo,$repo,$tenant);
    if($operation==='deactivate'){
        if($id<1)throw new RuntimeException('RECORD_NOT_FOUND');$type=$entity==='person'?$source:($entity==='product'?'produto':($entity==='cfop'?'cfop':''));$directory->record($type,$id);$tables=['cliente'=>'clientes','fornecedor'=>'fornecedores','motorista'=>'motoristas','transportadora'=>'transportadoras','produto'=>'produtos','cfop'=>'cfops'];$table=$tables[$type]??throw new RuntimeException('RECORD_TYPE_INVALID');$pdo->prepare("UPDATE {$table} SET status='inativo' WHERE id=?")->execute([$id]);echo json_encode(['success'=>true,'message'=>'Cadastro desativado.'],JSON_UNESCAPED_UNICODE);exit;
    }
    if($entity==='person'){
        $_POST['id']=$id?:null;if($source===''||$source==='cliente'){$document=$canonicalDocument;if($document!==''&&$documentExists($document,$id))throw new InvalidArgumentException('Este CPF/CNPJ já está cadastrado. Abra o cadastro existente ou informe outro documento.');$saved=$peoplePersistence->saveClient($_POST);$id=$saved['person_id'];$source='cliente';}elseif($source==='fornecedor')$repo->saveFornecedor($_POST);elseif($source==='motorista')$repo->saveMotorista($_POST);elseif($source==='transportadora')$repo->saveTransportadora($_POST);else throw new RuntimeException('RECORD_TYPE_INVALID');
    }elseif($entity==='product'){$_POST['id']=$id?:null;$repo->saveProduto($_POST);}elseif($entity==='cfop'){$_POST['id']=$id?:null;$repo->saveCfop($_POST);}else throw new RuntimeException('ENTITY_INVALID');
    error_log('MASTER_DATA_SAVED tenant='.$tenant.' entity='.$entity.' person_id='.$id.' actor='.$actor);$response=['success'=>true,'ok'=>true,'message'=>'Cadastro salvo com sucesso.','id'=>$id,'person_id'=>$id,'source_type'=>$source];if(isset($saved)){$response['created']=$saved['created'];$response['affected_rows']=$saved['affected_rows'];$response['updated_sections']=$saved['updated_sections'];$response['record']=$saved['record'];}echo json_encode($response,JSON_UNESCAPED_UNICODE);
}catch(Throwable $error){$validation=$error instanceof InvalidArgumentException||$error instanceof DomainException;$personType=strtoupper((string)($_POST['person_type'] ?? $_POST['document_type'] ?? ''));$personDocType=strtoupper((string)($_POST['document_type'] ?? ''));$duplicateDocument=preg_match('/(CPF|CNPJ).*já.*cadastrado|já.*cadastrado.*(CPF|CNPJ)/i',$error->getMessage())===1;$cpfInvalid=$validation&&($personType==='PF' || $personDocType==='CPF')&&!$duplicateDocument&&((str_contains($error->getMessage(),'CPF inválido')||str_contains($error->getMessage(),'Informe um CPF válido')||str_contains($error->getMessage(),'CPF deve')||str_contains($error->getMessage(),'11 dígitos')));http_response_code($validation?422:404);$safe=$cpfInvalid?'CPF inválido.':($duplicateDocument?'Este CPF/CNPJ já está cadastrado. Abra o cadastro existente ou informe outro documento.':($validation?$error->getMessage():(match($error->getMessage()){'CSRF_INVALID'=>'Sessão do formulário expirada.','RECORD_NOT_FOUND'=>'Cadastro não encontrado nesta empresa.',default=>'Não foi possível concluir. Os dados foram mantidos.'})));error_log('MASTER_DATA_ACTION_FAILED tenant='.$tenant.' type='.get_class($error).' code='.($cpfInvalid?'CPF_INVALID':$error->getMessage()));$response=['success'=>false,'ok'=>false,'message'=>$safe];if($cpfInvalid){$response['code']='CPF_INVALID';$response['fields']=['document'=>'CPF inválido.','cpf_cnpj'=>'CPF inválido.'];}elseif($duplicateDocument){$response['code']='DOCUMENT_DUPLICATE';$response['fields']=['document'=>'Este CPF/CNPJ já está cadastrado.','cpf_cnpj'=>'Este CPF/CNPJ já está cadastrado.'];}echo json_encode($response,JSON_UNESCAPED_UNICODE);}
