<?php
declare(strict_types=1);require __DIR__.'/../vendor/autoload.php';require_once __DIR__.'/../app/Database.php';require_once __DIR__.'/../app/Repository.php';
use MiniErp\Repositories\MasterDataDirectoryRepository;
if(session_status()!==PHP_SESSION_ACTIVE)session_start();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');$tenant=(int)($_SESSION['erp_tenant_id']??0);$user=(int)($_SESSION['erp_user_id']??0);if($tenant<1||$user<1){http_response_code(401);exit(json_encode(['success'=>false,'message'=>'Sessão expirada.']));}
try{$cfg=require __DIR__.'/../config.php';$d=$cfg['db'];$main=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['database']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$q=$main->prepare('SELECT db_name FROM tenants WHERE id=?');$q->execute([$tenant]);$db=(string)$q->fetchColumn();if(!preg_match('/^mini_erp_tenant_[1-9]\d*$/',$db))throw new RuntimeException('TENANT_NOT_FOUND');$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$db};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$directory=new MasterDataDirectoryRepository($pdo,$tenant);
 if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$type=(string)($_GET['type']??'');$id=(int)($_GET['id']??0);if($id<1)throw new RuntimeException('RECORD_NOT_FOUND');echo json_encode(['success'=>true,'record'=>$directory->record($type,$id)],JSON_UNESCAPED_UNICODE);exit;}
 if(($_SERVER['HTTP_SEC_FETCH_SITE']??'same-origin')==='cross-site')throw new RuntimeException('ORIGIN_INVALID');if(!hash_equals((string)($_SESSION['erp_master_data_csrf']??''),(string)($_POST['csrf']??'')))throw new RuntimeException('CSRF_INVALID');$entity=(string)($_POST['entity']??'');$operation=(string)($_POST['operation']??'save');$source=(string)($_POST['source_type']??'');$id=(int)($_POST['id']??0);$repo=new Repository($pdo,false);
 if($operation==='deactivate'){if($id<1)throw new RuntimeException('RECORD_NOT_FOUND');$type=$entity==='person'?$source:($entity==='product'?'produto':($entity==='cfop'?'cfop':''));$directory->record($type,$id);$tables=['cliente'=>'clientes','fornecedor'=>'fornecedores','motorista'=>'motoristas','transportadora'=>'transportadoras','produto'=>'produtos','cfop'=>'cfops'];$table=$tables[$type]??throw new RuntimeException('RECORD_TYPE_INVALID');$pdo->prepare("UPDATE {$table} SET status='inativo' WHERE id=?")->execute([$id]);error_log('MASTER_DATA_DEACTIVATED tenant='.$tenant.' entity='.$entity.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Cadastro desativado.'],JSON_UNESCAPED_UNICODE);exit;}
 if($entity==='person'){$_POST['id']=$id?:null;if($source===''||$source==='cliente'){$repo->saveCliente($_POST);}elseif($source==='fornecedor'){$repo->saveFornecedor($_POST);}elseif($source==='motorista'){$repo->saveMotorista($_POST);}elseif($source==='transportadora'){$repo->saveTransportadora($_POST);}else throw new RuntimeException('RECORD_TYPE_INVALID');}
 elseif($entity==='product'){$_POST['id']=$id?:null;$repo->saveProduto($_POST);}
 elseif($entity==='cfop'){$_POST['id']=$id?:null;$repo->saveCfop($_POST);}else throw new RuntimeException('ENTITY_INVALID');error_log('MASTER_DATA_SAVED tenant='.$tenant.' entity='.$entity.' actor='.$user);echo json_encode(['success'=>true,'message'=>'Cadastro salvo com sucesso.'],JSON_UNESCAPED_UNICODE);
}catch(Throwable$e){http_response_code($e instanceof InvalidArgumentException?422:404);$safe=$e instanceof InvalidArgumentException?$e->getMessage():(match($e->getMessage()){'CSRF_INVALID'=>'Sessão do formulário expirada.','RECORD_NOT_FOUND'=>'Cadastro não encontrado nesta empresa.',default=>'Não foi possível concluir. Os dados foram mantidos.'});error_log('MASTER_DATA_ACTION_FAILED tenant='.$tenant.' type='.get_class($e).' code='.$e->getMessage());echo json_encode(['success'=>false,'message'=>$safe],JSON_UNESCAPED_UNICODE);}
