<?php
declare(strict_types=1);
namespace MiniErp\Repositories;
use PDO;
final class CompanyFiscalSettingsRepository{
 public function __construct(private PDO $pdo,private int $tenantId){}
 public function all(int $est):array{return['general'=>$this->one('establishment_fiscal_settings',$est),'cfops'=>$this->keyed('establishment_cfop_defaults',$est,'operation_context'),'csc'=>$this->keyed('establishment_csc_credentials',$est,'environment'),'icms'=>$this->rows('establishment_icms_defaults',$est,'uf,valid_from DESC'),'legacy'=>$this->one('establishment_legacy_tax_defaults',$est),'rtc'=>$this->keyed('establishment_rtc_defaults',$est,'document_scope')];}
 public function cfops():array{return$this->pdo->query("SELECT codigo,descricao FROM cfops WHERE status='ativo' ORDER BY codigo")->fetchAll(PDO::FETCH_ASSOC);}
 public function classifications(string $type):array{$s=$this->pdo->prepare('SELECT c.code,c.description FROM fiscal_classifications c JOIN fiscal_reference_versions v ON v.id=c.reference_version_id WHERE c.classification_type=? AND (v.effective_to IS NULL OR v.effective_to>=CURRENT_DATE) ORDER BY c.code');$s->execute([$type]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function saveGeneral(int $est,array $d,int $actor):void{$before=$this->one('establishment_fiscal_settings',$est);$this->upsert('establishment_fiscal_settings',$est,$d);$this->audit($est,'GENERAL',$actor,$before,$d);}
 public function saveCfops(int $est,array $values,int $actor):void{$before=$this->keyed('establishment_cfop_defaults',$est,'operation_context');foreach($values as$context=>$cfop){$s=$this->pdo->prepare("SELECT COUNT(*) FROM cfops WHERE codigo=? AND status='ativo'");$s->execute([$cfop]);if(!(int)$s->fetchColumn())throw new \InvalidArgumentException("CFOP {$cfop} não está ativo no cadastro.");$this->upsert('establishment_cfop_defaults',$est,['operation_context'=>$context,'cfop'=>$cfop],['operation_context']);}$this->audit($est,'CFOP',$actor,$before,$values);}
 public function bootstrapCfopDefaults(int$est,int$actor):array{$defaults=['ENTRY_INTERNAL'=>'1102','ENTRY_INTERSTATE'=>'2102','EXIT_INTERNAL'=>'5102','EXIT_INTERSTATE'=>'6102'];$before=$this->keyed('establishment_cfop_defaults',$est,'operation_context');$applied=[];$missing=[];foreach($defaults as$context=>$cfop){if(isset($before[$context]))continue;$s=$this->pdo->prepare("SELECT COUNT(*) FROM cfops WHERE codigo=? AND status='ativo'");$s->execute([$cfop]);if(!(int)$s->fetchColumn()){$missing[]=$cfop;continue;}$this->upsert('establishment_cfop_defaults',$est,['operation_context'=>$context,'cfop'=>$cfop],['operation_context']);$applied[$context]=$cfop;}if($applied)$this->audit($est,'CFOP_BOOTSTRAP',$actor,$before,$applied);return['applied'=>$applied,'missing'=>$missing];}
 public function saveLegacy(int $est,array $d,int $actor):void{$before=$this->one('establishment_legacy_tax_defaults',$est);$this->upsert('establishment_legacy_tax_defaults',$est,$d);$this->audit($est,'PIS_COFINS_IPI',$actor,$before,$d);}
 public function saveRtc(int $est,array $d,int $actor):void{$before=$this->keyed('establishment_rtc_defaults',$est,'document_scope');$this->upsert('establishment_rtc_defaults',$est,$d,['document_scope']);$this->audit($est,'IBS_CBS_IS',$actor,$before,$d);}
 public function saveIcms(int $est,array $d,int $actor):void{$before=$this->rows('establishment_icms_defaults',$est,'uf,valid_from DESC');$this->upsert('establishment_icms_defaults',$est,$d,['uf','valid_from']);$this->audit($est,'ICMS_UF',$actor,$before,$d);}
 public function saveCsc(int $est,int $env,string $idCsc,string $reference,string $suffix,int $actor):?string{$old=$this->csc($est,$env);$this->upsert('establishment_csc_credentials',$est,['environment'=>$env,'id_csc'=>$idCsc,'secret_reference'=>$reference,'secret_suffix'=>$suffix,'active'=>1,'created_by'=>$actor],['environment']);$this->audit($est,'CSC_'.$env,$actor,$old?['id_csc'=>$old['id_csc'],'secret'=>'REDACTED']:[],['id_csc'=>$idCsc,'secret'=>'REDACTED']);return$old['secret_reference']??null;}
 public function csc(int $est,int $env):?array{$s=$this->pdo->prepare('SELECT * FROM establishment_csc_credentials WHERE tenant_id=? AND establishment_id=? AND environment=?');$s->execute([$this->tenantId,$est,$env]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 private function one(string$t,int$e):array{return$this->rows($t,$e)[0]??[];}private function rows(string$t,int$e,string$order='id'):array{$s=$this->pdo->prepare("SELECT * FROM {$t} WHERE tenant_id=? AND establishment_id=? ORDER BY {$order}");$s->execute([$this->tenantId,$e]);return$s->fetchAll(PDO::FETCH_ASSOC);}private function keyed(string$t,int$e,string$key):array{$out=[];foreach($this->rows($t,$e)as$r)$out[(string)$r[$key]]=$r;return$out;}
 private function upsert(string$table,int$est,array$data,array$keys=[]):void{$data=['tenant_id'=>$this->tenantId,'establishment_id'=>$est]+$data;$cols=array_keys($data);$updates=array_values(array_diff($cols,['tenant_id','establishment_id',...$keys]));$sql='INSERT INTO '.$table.' (`'.implode('`,`',$cols).'`) VALUES ('.implode(',',array_fill(0,count($cols),'?')).') ON DUPLICATE KEY UPDATE '.implode(',',array_map(fn($c)=>"`{$c}`=VALUES(`{$c}`)",$updates));$this->pdo->prepare($sql)->execute(array_values($data));}
 private function audit(int$est,string$group,int$actor,array$before,array$after):void{$s=$this->pdo->prepare('INSERT INTO establishment_fiscal_settings_audit(tenant_id,establishment_id,setting_group,actor_id,before_json,after_json) VALUES(?,?,?,?,?,?)');$s->execute([$this->tenantId,$est,$group,$actor,json_encode($before,JSON_UNESCAPED_UNICODE),json_encode($after,JSON_UNESCAPED_UNICODE)]);}
}
