<?php
declare(strict_types=1);
namespace MiniErp\Repositories;
use PDO;use RuntimeException;use Throwable;
final class FiscalConfigurationRepository {
 // Production guard regression marker: environment!==2 is rejected by saveSeries.
 public function __construct(private PDO $pdo,private int $tenantId){}
 public function certificate(int $est):?array{$s=$this->pdo->prepare('SELECT * FROM fiscal_certificates WHERE tenant_id=? AND establishment_id=? AND active=1 ORDER BY id DESC LIMIT 1');$s->execute([$this->tenantId,$est]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function certificateById(int $est,int $id):?array{$s=$this->pdo->prepare('SELECT * FROM fiscal_certificates WHERE id=? AND tenant_id=? AND establishment_id=?');$s->execute([$id,$this->tenantId,$est]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function latestCertificate(int $est):?array{$s=$this->pdo->prepare('SELECT * FROM fiscal_certificates WHERE tenant_id=? AND establishment_id=? ORDER BY id DESC LIMIT 1');$s->execute([$this->tenantId,$est]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function certificateHistory(int $est):array{$s=$this->pdo->prepare('SELECT * FROM fiscal_certificates WHERE tenant_id=? AND establishment_id=? ORDER BY id DESC');$s->execute([$this->tenantId,$est]);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public function activateCertificate(int $est,array $m,string $storage,string $secret,int $actor):int{$this->pdo->beginTransaction();try{$old=$this->certificate($est);if($old){$this->pdo->prepare("UPDATE fiscal_certificates SET active=0,status='DEACTIVATED',deactivated_by=?,deactivated_at=NOW() WHERE id=? AND tenant_id=? AND establishment_id=?")->execute([$actor,$old['id'],$this->tenantId,$est]);$this->auditCertificate($est,(int)$old['id'],'REPLACED',$actor,[]);}$s=$this->pdo->prepare('INSERT INTO fiscal_certificates(tenant_id,establishment_id,storage_reference,file_name,sha256,fingerprint_sha256,subject,issuer,serial_number,tax_id,valid_from,valid_until,status,secret_reference,uploaded_by,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)');$s->execute([$this->tenantId,$est,$storage,$m['file_name'],$m['sha256'],$m['fingerprint_sha256'],$m['subject'],$m['issuer'],$m['serial_number'],$m['tax_id'],$m['valid_from'],$m['valid_until'],$m['status'],$secret,$actor]);$id=(int)$this->pdo->lastInsertId();$this->auditCertificate($est,$id,$old?'REPLACE':'UPLOAD',$actor,['sha256'=>$m['sha256']]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function storeCertificateCandidate(int$est,array$m,string$storage,string$secret,int$actor):int{$s=$this->pdo->prepare('INSERT INTO fiscal_certificates(tenant_id,establishment_id,storage_reference,file_name,sha256,fingerprint_sha256,subject,issuer,serial_number,tax_id,valid_from,valid_until,status,secret_reference,uploaded_by,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)');$s->execute([$this->tenantId,$est,$storage,$m['file_name'],$m['sha256'],$m['fingerprint_sha256'],$m['subject'],$m['issuer'],$m['serial_number'],$m['tax_id']?:null,$m['valid_from'],$m['valid_until'],$m['status'],$secret,$actor]);$id=(int)$this->pdo->lastInsertId();$this->auditCertificate($est,$id,'UPLOAD',$actor,['sha256'=>$m['sha256'],'identity_status'=>$m['identity_status']??'NOT_FOUND','identity_source'=>$m['identity_source']??'UNKNOWN']);return$id;}
 public function activateStoredCertificate(int$est,int$id,int$actor):void{$this->pdo->beginTransaction();try{$old=$this->certificate($est);if($old&&(int)$old['id']!==$id){$this->pdo->prepare("UPDATE fiscal_certificates SET active=0,status='DEACTIVATED',deactivated_by=?,deactivated_at=NOW() WHERE id=? AND tenant_id=? AND establishment_id=?")->execute([$actor,$old['id'],$this->tenantId,$est]);$this->auditCertificate($est,(int)$old['id'],'REPLACED',$actor,[]);}$this->pdo->prepare("UPDATE fiscal_certificates SET active=1,status='VALID' WHERE id=? AND tenant_id=? AND establishment_id=?")->execute([$id,$this->tenantId,$est]);$this->auditCertificate($est,$id,'ACTIVATE',$actor,['read_back'=>'PASS','local_signature'=>'PASS']);$this->pdo->commit();}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 public function deactivateCertificate(int $est,int $actor,string $reason):void{if(trim($reason)==='')throw new RuntimeException('Motivo administrativo obrigatorio.');$this->pdo->beginTransaction();try{$row=$this->certificate($est);if(!$row)throw new RuntimeException('Certificado ativo nao encontrado.');$this->pdo->prepare("UPDATE fiscal_certificates SET active=0,status='DEACTIVATED',deactivated_by=?,deactivated_at=NOW() WHERE id=? AND tenant_id=? AND establishment_id=?")->execute([$actor,$row['id'],$this->tenantId,$est]);$this->auditCertificate($est,(int)$row['id'],'DEACTIVATE',$actor,['reason'=>$reason]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function series(int $est):array{$s=$this->pdo->prepare('SELECT s.*,(SELECT MAX(r.number) FROM fiscal_number_reservations r WHERE r.tenant_id=s.tenant_id AND r.establishment_id=s.establishment_id AND r.model=s.model AND r.series=s.series) last_reserved_number FROM fiscal_series s WHERE s.tenant_id=? AND s.establishment_id=? ORDER BY s.model,s.series');$s->execute([$this->tenantId,$est]);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public function seriesHistory(int $est):array{$s=$this->pdo->prepare('SELECT * FROM fiscal_series_audit WHERE tenant_id=? AND establishment_id=? ORDER BY id DESC');$s->execute([$this->tenantId,$est]);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public function auditSefazStatus(int$est,int$certificateId,string$action,int$actor,array$details):void{unset($details['pfx'],$details['password'],$details['private_key'],$details['master_key'],$details['certificate']);$this->auditCertificate($est,$certificateId,$action,$actor,$details);}
 public function latestSefazStatus(int$est):?array{$s=$this->pdo->prepare("SELECT * FROM fiscal_certificate_audit WHERE tenant_id=? AND establishment_id=? AND action IN('SEFAZ_STATUS_REQUESTED','SEFAZ_STATUS_OK','SEFAZ_STATUS_FAILED') ORDER BY id DESC LIMIT 1");$s->execute([$this->tenantId,$est]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function recentSefazRequestCount(int$est,int$seconds=15):int{$seconds=max(1,min(300,$seconds));$s=$this->pdo->prepare("SELECT COUNT(*) FROM fiscal_certificate_audit WHERE tenant_id=? AND establishment_id=? AND action='SEFAZ_STATUS_REQUESTED' AND created_at>=DATE_SUB(NOW(),INTERVAL $seconds SECOND)");$s->execute([$this->tenantId,$est]);return(int)$s->fetchColumn();}
 public function saveSeries(int $est,string $model,int $series,int $next,int $env,bool $active,int $user,string $reason):void{if(!in_array($model,['55','65'],true)||$series<0||$series>999||$next<1)throw new RuntimeException('Configuracao de serie invalida.');if($env!==2)throw new RuntimeException('Producao permanece bloqueada.');if(trim($reason)==='')throw new RuntimeException('Motivo administrativo obrigatorio.');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM fiscal_series WHERE tenant_id=? AND establishment_id=? AND model=? AND series=? FOR UPDATE');$s->execute([$this->tenantId,$est,$model,$series]);$old=$s->fetch(PDO::FETCH_ASSOC);$action='CREATE';if($old){$r=$this->pdo->prepare('SELECT COUNT(*) FROM fiscal_number_reservations WHERE tenant_id=? AND establishment_id=? AND model=? AND series=?');$r->execute([$this->tenantId,$est,$model,$series]);if((int)$r->fetchColumn()>0&&($next!==(int)$old['next_number']||$env!==(int)$old['environment']))throw new RuntimeException('Serie utilizada: contador e ambiente sao imutaveis.');$action=((int)$old['active']!==($active?1:0))?($active?'ACTIVATE':'DEACTIVATE'):'UPDATE';$this->pdo->prepare('UPDATE fiscal_series SET next_number=?,active=? WHERE id=?')->execute([$next,$active?1:0,$old['id']]);$id=(int)$old['id'];$oldNext=(int)$old['next_number'];}else{$this->pdo->prepare("INSERT INTO fiscal_series(tenant_id,establishment_id,model,series,next_number,environment,emission_type,process_version,active) VALUES(?,?,?,?,?,2,1,'MiniERP-FISCAL-02C',?)")->execute([$this->tenantId,$est,$model,$series,$next,$active?1:0]);$id=(int)$this->pdo->lastInsertId();$oldNext=null;}$after=['model'=>$model,'series'=>$series,'next_number'=>$next,'environment'=>2,'active'=>$active];$a=$this->pdo->prepare('INSERT INTO fiscal_series_audit(tenant_id,establishment_id,fiscal_series_id,action,model,series,old_next_number,new_next_number,changed_by,reason,before_json,after_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$a->execute([$this->tenantId,$est,$id,$action,$model,$series,$oldNext,$next,$user,$reason,json_encode($old?:null),json_encode($after)]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 private function auditCertificate(int $est,int $cert,string $action,int $actor,array $details):void{$s=$this->pdo->prepare('INSERT INTO fiscal_certificate_audit(tenant_id,establishment_id,certificate_id,action,actor_id,details_json) VALUES(?,?,?,?,?,?)');$s->execute([$this->tenantId,$est,$cert,$action,$actor,json_encode($details)]);}
}
