<?php
declare(strict_types=1);
namespace MiniErp\Repositories;
use PDO;use RuntimeException;

final class MasterDataDirectoryRepository
{
    private array $columns=[];
    public function __construct(private PDO $pdo,private int $tenantId){}
    public function people(array $filters,int $page,int $perPage):array
    {
        $page=max(1,$page);$perPage=in_array($perPage,[10,25,50,100],true)?$perPage:25;$parts=[];$params=[];
        $scope=function(string$table)use(&$params):string{if(!$this->column($table,'tenant_id'))return'';$params[]=$this->tenantId;return' WHERE tenant_id=?';};
        $clientRoles="CONCAT_WS(',',IF(role_customer=1,'cliente',NULL),IF(role_supplier=1,'fornecedor',NULL),IF(role_seller=1,'vendedor',NULL),IF(role_carrier=1,'transportadora',NULL))";
        $parts[]="SELECT CONCAT('cliente:',id) source_ref,'cliente' source_type,id source_id,nome legal_name,nome_fantasia trade_name,cpf_cnpj document,email,COALESCE(NULLIF(fone_principal,''),telefone) phone,COALESCE(NULLIF(municipio,''),cidade) city,uf state,status,{$clientRoles} roles FROM clientes".$scope('clientes');
        $parts[]="SELECT CONCAT('fornecedor:',id),'fornecedor',id,nome,nome_fantasia,cpf_cnpj,email,telefone,COALESCE(NULLIF(municipio,''),cidade),uf,status,'fornecedor' FROM fornecedores".$scope('fornecedores');
        $parts[]="SELECT CONCAT('motorista:',id),'motorista',id,nome,'',cpf,'',telefone,'','',status,'motorista' FROM motoristas".$scope('motoristas');
        $parts[]="SELECT CONCAT('transportadora:',id),'transportadora',id,nome,nome_fantasia,cpf_cnpj,email,telefone,COALESCE(NULLIF(municipio,''),cidade),uf,status,'transportadora' FROM transportadoras".$scope('transportadoras');
        $union=implode(' UNION ALL ',$parts);$grouped="SELECT CASE WHEN REPLACE(REPLACE(REPLACE(REPLACE(document,'.',''),'/',''),'-',''),' ','')<>'' THEN CONCAT('doc:',UPPER(REPLACE(REPLACE(REPLACE(REPLACE(document,'.',''),'/',''),'-',''),' ',''))) ELSE source_ref END identity_key,MAX(legal_name) legal_name,MAX(trade_name) trade_name,MAX(document) document,MAX(email) email,MAX(phone) phone,MAX(city) city,MAX(state) state,IF(SUM(status='ativo')>0,'ativo','inativo') status,GROUP_CONCAT(DISTINCT roles) roles,GROUP_CONCAT(source_ref) sources,MIN(source_type) source_type,MIN(source_id) source_id FROM ({$union}) person_union GROUP BY identity_key";
        $where=[];$outer=[];$q=trim((string)($filters['q']??''));if($q!==''){$where[]="CONVERT(CONCAT_WS(' ',legal_name,trade_name,document,email,phone,city,state) USING utf8mb4) COLLATE utf8mb4_general_ci LIKE CONVERT(? USING utf8mb4) COLLATE utf8mb4_general_ci";$outer[]='%'.$q.'%';}$status=(string)($filters['status']??'');if(in_array($status,['ativo','inativo'],true)){$where[]='status=?';$outer[]=$status;}$type=(string)($filters['type']??'');if(in_array($type,['cliente','fornecedor','vendedor','motorista','transportadora'],true)){$where[]='FIND_IN_SET(?,REPLACE(roles,", ",","))>0';$outer[]=$type;}$sql=' FROM ('.$grouped.') people'.($where?' WHERE '.implode(' AND ',$where):'');$allParams=[...$params,...$outer];$count=$this->pdo->prepare('SELECT COUNT(*)'.$sql);$count->execute($allParams);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$query=$this->pdo->prepare('SELECT *'.$sql.' ORDER BY legal_name LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$query->execute($allParams);return['rows'=>$query->fetchAll(PDO::FETCH_ASSOC),'total'=>$total,'page'=>$page,'pages'=>$pages,'per_page'=>$perPage];
    }
    public function products(array$filters,int$page,int$perPage):array{return$this->simplePage('produtos',['nome','codigo','categoria','ncm'],$filters,$page,$perPage,'id DESC');}
    public function cfops(array$filters,int$page,int$perPage):array{return$this->simplePage('cfops',['codigo','descricao','natureza','aplicacao'],$filters,$page,$perPage,'codigo');}
    public function record(string$type,int$id):array{$tables=['cliente'=>'clientes','fornecedor'=>'fornecedores','motorista'=>'motoristas','transportadora'=>'transportadoras','produto'=>'produtos','cfop'=>'cfops'];$table=$tables[$type]??throw new RuntimeException('RECORD_TYPE_INVALID');$sql="SELECT * FROM {$table} WHERE id=?";$params=[$id];if($this->column($table,'tenant_id')){$sql.=' AND tenant_id=?';$params[]=$this->tenantId;}$s=$this->pdo->prepare($sql.' LIMIT 1');$s->execute($params);return$s->fetch(PDO::FETCH_ASSOC)?:throw new RuntimeException('RECORD_NOT_FOUND');}
    private function simplePage(string$table,array$fields,array$f,int$page,int$perPage,string$order):array{$page=max(1,$page);$perPage=in_array($perPage,[10,25,50,100],true)?$perPage:25;$where=[];$params=[];if($this->column($table,'tenant_id')){$where[]='tenant_id=?';$params[]=$this->tenantId;}$q=trim((string)($f['q']??''));if($q!==''){$where[]='('.implode(' OR ',array_map(fn($x)=>$x.' LIKE ?',$fields)).')';foreach($fields as$_)$params[]='%'.$q.'%';}$status=(string)($f['status']??'');if(in_array($status,['ativo','inativo'],true)&&$this->column($table,'status')){$where[]='status=?';$params[]=$status;}$suffix=$where?' WHERE '.implode(' AND ',$where):'';$c=$this->pdo->prepare("SELECT COUNT(*) FROM {$table}{$suffix}");$c->execute($params);$total=(int)$c->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$s=$this->pdo->prepare("SELECT * FROM {$table}{$suffix} ORDER BY {$order} LIMIT {$perPage} OFFSET ".(($page-1)*$perPage));$s->execute($params);return['rows'=>$s->fetchAll(PDO::FETCH_ASSOC),'total'=>$total,'page'=>$page,'pages'=>$pages,'per_page'=>$perPage];}
    private function column(string$table,string$column):bool{$key=$table.'.'.$column;if(array_key_exists($key,$this->columns))return$this->columns[$key];$s=$this->pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$s->execute([$table,$column]);return$this->columns[$key]=(int)$s->fetchColumn()===1;}
}
