<?php
declare(strict_types=1);

namespace MiniErp\Repositories;

use PDO;
use RuntimeException;
use Throwable;

final class StockRepository
{
    public function __construct(private PDO $pdo,private int $tenantId){}

    public function products():array
    {
        return$this->productsPage([],1,10000)['rows'];
    }
    public function productsPage(array$filters,int$page=1,int$perPage=12):array
    {
        $page=max(1,$page);$perPage=max(6,min(100,$perPage));$where=[];$params=['lot_tenant'=>$this->tenantId];
        if($this->hasColumn('produtos','tenant_id')){$where[]='p.tenant_id=:product_tenant';$params['product_tenant']=$this->tenantId;}
        $q=trim((string)($filters['q']??''));if($q!==''){$where[]='(p.nome LIKE :product_q OR p.codigo LIKE :product_q)';$params['product_q']='%'.$q.'%';}
        $from=(string)($filters['from']??'');$to=(string)($filters['to']??'');if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)){$where[]='DATE(p.created_at)>=:product_from';$params['product_from']=$from;}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)){$where[]='DATE(p.created_at)<=:product_to';$params['product_to']=$to;}
        $whereSql=$where?implode(' AND ',$where):'1=1';$count=$this->pdo->prepare('SELECT COUNT(*) FROM produtos p WHERE '.$whereSql);$countParams=$params;unset($countParams['lot_tenant']);$count->execute($countParams);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;
        $sql="SELECT p.id,p.codigo,p.nome,p.unidade,p.estoque_atual,p.minimum_stock,p.stock_control_by_lot,p.created_at,COALESCE(SUM(CASE WHEN l.status='ACTIVE' THEN l.quantity_available ELSE 0 END),0) lot_balance,COUNT(l.id) lot_count,COALESCE(SUM(CASE WHEN l.blocked_sale=1 THEN 1 ELSE 0 END),0) blocked_lots FROM produtos p LEFT JOIN stock_lots l ON l.product_id=p.id AND l.tenant_id=:lot_tenant WHERE {$whereSql} GROUP BY p.id,p.codigo,p.nome,p.unidade,p.estoque_atual,p.minimum_stock,p.stock_control_by_lot,p.created_at ORDER BY p.created_at DESC,p.id DESC LIMIT {$perPage} OFFSET {$offset}";$s=$this->pdo->prepare($sql);$s->execute($params);return['rows'=>$s->fetchAll(PDO::FETCH_ASSOC),'total'=>$total,'page'=>$page,'pages'=>$pages,'per_page'=>$perPage];
    }
    public function locations():array{$s=$this->pdo->prepare('SELECT * FROM stock_locations WHERE tenant_id=? AND active=1 ORDER BY name');$s->execute([$this->tenantId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
    public function lots(int$productId=0):array{$sql='SELECT l.*,p.nome product_name,p.codigo product_code,p.unidade,loc.name location_name FROM stock_lots l JOIN produtos p ON p.id=l.product_id JOIN stock_locations loc ON loc.id=l.location_id WHERE l.tenant_id=?';$params=[$this->tenantId];if($productId>0){$sql.=' AND l.product_id=?';$params[]=$productId;}$sql.=' ORDER BY l.blocked_sale,l.expires_at IS NULL,l.expires_at,l.id DESC';$s=$this->pdo->prepare($sql);$s->execute($params);return$s->fetchAll(PDO::FETCH_ASSOC);}
    public function movements(int$limit=100):array{$limit=max(1,min(500,$limit));$s=$this->pdo->prepare("SELECT m.*,p.nome product_name,src.lot_code source_lot,dst.lot_code destination_lot FROM stock_movements m JOIN produtos p ON p.id=m.product_id LEFT JOIN stock_lots src ON src.id=m.source_lot_id LEFT JOIN stock_lots dst ON dst.id=m.destination_lot_id WHERE m.tenant_id=? ORDER BY m.id DESC LIMIT {$limit}");$s->execute([$this->tenantId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
    public function pendingLots():array{$s=$this->pdo->prepare("SELECT d.*,loc.name location_name,p.nome linked_product_name FROM stock_pending_lots d JOIN stock_locations loc ON loc.id=d.location_id LEFT JOIN produtos p ON p.id=d.linked_product_id WHERE d.tenant_id=? ORDER BY d.status='PENDING' DESC,d.id DESC");$s->execute([$this->tenantId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
    public function ensureMainLocation():int{$s=$this->pdo->prepare("INSERT INTO stock_locations(tenant_id,name,code,active) VALUES(?,'Estoque principal','PRINCIPAL',1) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),active=1");$s->execute([$this->tenantId]);return(int)$this->pdo->lastInsertId();}
    public function createLocation(string$name,string$code):int{$name=trim($name);$code=strtoupper(preg_replace('/[^A-Z0-9_-]/','',strtoupper(trim($code))));if($name===''||$code==='')throw new RuntimeException('Informe nome e código do local.');$s=$this->pdo->prepare('INSERT INTO stock_locations(tenant_id,name,code,active) VALUES(?,?,?,1)');$s->execute([$this->tenantId,mb_substr($name,0,120),mb_substr($code,0,40)]);return(int)$this->pdo->lastInsertId();}
    public function createLot(int$productId,int$locationId,string$code,string$quantity,?string$manufactured,?string$expires,string$reason,int$actor):int
    {
        $qty=$this->quantity($quantity);$code=trim($code);if($productId<1||$locationId<1||$code===''||bccomp($qty,'0',4)<0)throw new RuntimeException('Revise produto, local, lote e quantidade.');$reason=trim($reason)?:'Entrada inicial do lote';
        return$this->transaction(function()use($productId,$locationId,$code,$qty,$manufactured,$expires,$reason,$actor){$this->ownedProduct($productId);$this->ownedLocation($locationId);$s=$this->pdo->prepare('INSERT INTO stock_lots(tenant_id,product_id,location_id,lot_code,manufactured_at,expires_at,quantity_available) VALUES(?,?,?,?,?,?,?)');$s->execute([$this->tenantId,$productId,$locationId,mb_substr($code,0,100),$manufactured?:null,$expires?:null,$qty]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare('UPDATE produtos SET stock_control_by_lot=1 WHERE id=?')->execute([$productId]);$this->movement($productId,null,$id,'INITIAL',$qty,'0.0000',$qty,$reason,$actor);$this->syncProduct($productId);return$id;});
    }
    public function setBlocked(int$lotId,bool$blocked,string$reason,int$actor):void{$reason=trim($reason);if($blocked&&$reason==='')throw new RuntimeException('Informe o motivo do bloqueio.');$lot=$this->lotForUpdate($lotId);$this->pdo->prepare('UPDATE stock_lots SET blocked_sale=?,block_reason=? WHERE id=? AND tenant_id=?')->execute([$blocked?1:0,$blocked?mb_substr($reason,0,500):null,$lotId,$this->tenantId]);$this->movement((int)$lot['product_id'],$lotId,null,$blocked?'BLOCK':'UNBLOCK','0.0000',(string)$lot['quantity_available'],(string)$lot['quantity_available'],$blocked?$reason:'Lote liberado para venda',$actor);}
    public function receive(int$productId,int$locationId,string$code,string$quantity,string$reason,int$actor,?string$referenceType=null,?int$referenceId=null):int
    {
        $qty=$this->quantity($quantity);$code=trim($code);$reason=trim($reason);if($productId<1||$locationId<1||$code===''||bccomp($qty,'0',4)<=0)throw new RuntimeException('Informe produto, local, lote e uma quantidade maior que zero.');
        return$this->transaction(function()use($productId,$locationId,$code,$qty,$reason,$actor,$referenceType,$referenceId){$this->ownedProduct($productId);$this->ownedLocation($locationId);$find=$this->pdo->prepare('SELECT * FROM stock_lots WHERE tenant_id=? AND product_id=? AND location_id=? AND lot_code=? FOR UPDATE');$find->execute([$this->tenantId,$productId,$locationId,$code]);$lot=$find->fetch(PDO::FETCH_ASSOC);if($lot){$lotId=(int)$lot['id'];$before=$this->quantity($lot['quantity_available']);$after=bcadd($before,$qty,4);$this->pdo->prepare("UPDATE stock_lots SET quantity_available=?,status='ACTIVE' WHERE id=?")->execute([$after,$lotId]);}else{$this->pdo->prepare('INSERT INTO stock_lots(tenant_id,product_id,location_id,lot_code,quantity_available) VALUES(?,?,?,?,?)')->execute([$this->tenantId,$productId,$locationId,mb_substr($code,0,100),$qty]);$lotId=(int)$this->pdo->lastInsertId();$before='0.0000';$after=$qty;}$this->pdo->prepare('UPDATE produtos SET stock_control_by_lot=1 WHERE id=?')->execute([$productId]);$s=$this->pdo->prepare('INSERT INTO stock_movements(tenant_id,product_id,destination_lot_id,movement_type,quantity,balance_before,balance_after,reference_type,reference_id,reason,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$this->tenantId,$productId,$lotId,'ENTRY',$qty,$before,$after,$referenceType,$referenceId,$reason?:'Entrada manual de estoque',$actor]);$this->syncProduct($productId);return$lotId;});
    }
    public function receiveEntryOrder(int$orderId,array$items,int$actor):void
    {
        if($orderId<1||!$items)return;$check=$this->pdo->prepare("SELECT COUNT(*) FROM stock_movements WHERE tenant_id=? AND reference_type='ENTRY_ORDER' AND reference_id=?");$check->execute([$this->tenantId,$orderId]);if((int)$check->fetchColumn()>0)return;$location=$this->ensureMainLocation();foreach($items as$item){$productId=(int)($item['product_id']??$item['id']??0);$quantity=(string)($item['quantity']??'0');if($productId<1||bccomp($this->quantity($quantity),'0',4)<=0)continue;$this->receive($productId,$location,'ENTRADA-'.$orderId.'-'.$productId,$quantity,'Entrada automática vinculada ao pedido #'.$orderId,$actor,'ENTRY_ORDER',$orderId);}
    }
    public function createPendingLot(int$locationId,string$code,string$quantity,?string$manufactured,?string$expires,string$document,string$notes,int$actor):int
    {
        $qty=$this->quantity($quantity);$code=trim($code);if($locationId<1||$code===''||bccomp($qty,'0',4)<=0)throw new RuntimeException('Informe local, lote e quantidade recebida.');$this->ownedLocation($locationId);$s=$this->pdo->prepare('INSERT INTO stock_pending_lots(tenant_id,location_id,lot_code,quantity_received,manufactured_at,expires_at,source_document,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$this->tenantId,$locationId,mb_substr($code,0,100),$qty,$manufactured?:null,$expires?:null,mb_substr(trim($document),0,120)?:null,mb_substr(trim($notes),0,500)?:null,$actor]);return(int)$this->pdo->lastInsertId();
    }
    public function linkPendingLot(int$pendingId,int$productId,int$actor):int
    {
        return$this->transaction(function()use($pendingId,$productId,$actor){$s=$this->pdo->prepare("SELECT * FROM stock_pending_lots WHERE id=? AND tenant_id=? AND status='PENDING' FOR UPDATE");$s->execute([$pendingId,$this->tenantId]);$pending=$s->fetch(PDO::FETCH_ASSOC);if(!$pending)throw new RuntimeException('Lote pendente não encontrado ou já vinculado.');$lotId=$this->receive($productId,(int)$pending['location_id'],(string)$pending['lot_code'],(string)$pending['quantity_received'],'Vínculo de lote recebido'.($pending['source_document']?' — '.$pending['source_document']:''),$actor,'PENDING_LOT',$pendingId);$update=$this->pdo->prepare("UPDATE stock_pending_lots SET status='LINKED',linked_product_id=?,linked_lot_id=?,linked_at=NOW() WHERE id=? AND tenant_id=?");$update->execute([$productId,$lotId,$pendingId,$this->tenantId]);return$lotId;});
    }
    public function adjust(int$lotId,string$type,string$quantity,string$reason,int$actor):void
    {
        $type=strtoupper($type);if(!in_array($type,['LOSS','YIELD'],true))throw new RuntimeException('Tipo de ajuste inválido.');$qty=$this->quantity($quantity);if(bccomp($qty,'0',4)<=0||trim($reason)==='')throw new RuntimeException('Informe quantidade e motivo.');$this->transaction(function()use($lotId,$type,$qty,$reason,$actor){$lot=$this->lotForUpdate($lotId);$before=$this->quantity($lot['quantity_available']);$after=$type==='LOSS'?bcsub($before,$qty,4):bcadd($before,$qty,4);if(bccomp($after,'0',4)<0)throw new RuntimeException('A perda é maior que o saldo do lote.');$this->pdo->prepare('UPDATE stock_lots SET quantity_available=? WHERE id=? AND tenant_id=?')->execute([$after,$lotId,$this->tenantId]);$this->movement((int)$lot['product_id'],$lotId,$type==='YIELD'?$lotId:null,$type,$qty,$before,$after,trim($reason),$actor);$this->syncProduct((int)$lot['product_id']);});
    }
    public function transfer(int$sourceLotId,int$destinationLocationId,string$quantity,string$reason,int$actor):void
    {
        $qty=$this->quantity($quantity);if(bccomp($qty,'0',4)<=0||trim($reason)==='')throw new RuntimeException('Informe quantidade e motivo da transferência.');$this->transaction(function()use($sourceLotId,$destinationLocationId,$qty,$reason,$actor){$source=$this->lotForUpdate($sourceLotId);$this->ownedLocation($destinationLocationId);if((int)$source['location_id']===$destinationLocationId)throw new RuntimeException('Escolha outro local de destino.');$before=$this->quantity($source['quantity_available']);$after=bcsub($before,$qty,4);if(bccomp($after,'0',4)<0)throw new RuntimeException('Saldo insuficiente no lote de origem.');$this->pdo->prepare('UPDATE stock_lots SET quantity_available=? WHERE id=?')->execute([$after,$sourceLotId]);$find=$this->pdo->prepare('SELECT * FROM stock_lots WHERE tenant_id=? AND product_id=? AND location_id=? AND lot_code=? FOR UPDATE');$find->execute([$this->tenantId,$source['product_id'],$destinationLocationId,$source['lot_code']]);$destination=$find->fetch(PDO::FETCH_ASSOC);if($destination){$destId=(int)$destination['id'];$destAfter=bcadd($this->quantity($destination['quantity_available']),$qty,4);$this->pdo->prepare('UPDATE stock_lots SET quantity_available=? WHERE id=?')->execute([$destAfter,$destId]);}else{$this->pdo->prepare('INSERT INTO stock_lots(tenant_id,product_id,location_id,lot_code,manufactured_at,expires_at,quantity_available,blocked_sale,block_reason,status) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$this->tenantId,$source['product_id'],$destinationLocationId,$source['lot_code'],$source['manufactured_at'],$source['expires_at'],$qty,$source['blocked_sale'],$source['block_reason'],$source['status']]);$destId=(int)$this->pdo->lastInsertId();$destAfter=$qty;}$this->movement((int)$source['product_id'],$sourceLotId,$destId,'TRANSFER',$qty,$before,$after,trim($reason),$actor);$this->syncProduct((int)$source['product_id']);});
    }
    public function selectableLots():array{$s=$this->pdo->prepare("SELECT l.id,l.product_id,l.lot_code,l.quantity_available,l.expires_at,loc.name location_name FROM stock_lots l JOIN stock_locations loc ON loc.id=l.location_id WHERE l.tenant_id=? AND l.status='ACTIVE' AND l.blocked_sale=0 AND l.quantity_available>0 AND (l.expires_at IS NULL OR l.expires_at>=CURRENT_DATE) ORDER BY l.expires_at IS NULL,l.expires_at,l.id");$s->execute([$this->tenantId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
    private function movement(int$productId,?int$source,?int$destination,string$type,string$qty,?string$before,?string$after,string$reason,int$actor):void{$s=$this->pdo->prepare('INSERT INTO stock_movements(tenant_id,product_id,source_lot_id,destination_lot_id,movement_type,quantity,balance_before,balance_after,reason,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([$this->tenantId,$productId,$source,$destination,$type,$qty,$before,$after,mb_substr($reason,0,500),$actor]);}
    private function lotForUpdate(int$id):array{$s=$this->pdo->prepare('SELECT * FROM stock_lots WHERE id=? AND tenant_id=? FOR UPDATE');$s->execute([$id,$this->tenantId]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('Lote não encontrado.');return$row;}
    private function ownedProduct(int$id):void{$s=$this->pdo->prepare('SELECT 1 FROM produtos WHERE id=? LIMIT 1');$s->execute([$id]);if(!$s->fetchColumn())throw new RuntimeException('Produto não encontrado.');}
    private function ownedLocation(int$id):void{$s=$this->pdo->prepare('SELECT 1 FROM stock_locations WHERE id=? AND tenant_id=? AND active=1');$s->execute([$id,$this->tenantId]);if(!$s->fetchColumn())throw new RuntimeException('Local de estoque inválido.');}
    private function syncProduct(int$productId):void{$s=$this->pdo->prepare("SELECT COALESCE(SUM(quantity_available),0) FROM stock_lots WHERE tenant_id=? AND product_id=? AND status='ACTIVE'");$s->execute([$this->tenantId,$productId]);$this->pdo->prepare('UPDATE produtos SET estoque_atual=?,stock_control_by_lot=1 WHERE id=?')->execute([$s->fetchColumn(),$productId]);}
    private function quantity(mixed$value):string{$value=str_replace(',','.',trim((string)$value));if(!preg_match('/^\d+(\.\d{1,4})?$/',$value))throw new RuntimeException('Quantidade inválida.');return bcadd($value,'0',4);}
    private function hasColumn(string$table,string$column):bool{$s=$this->pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$s->execute([$table,$column]);return(int)$s->fetchColumn()===1;}
    private function transaction(callable$callback):mixed{$own=!$this->pdo->inTransaction();if($own)$this->pdo->beginTransaction();try{$result=$callback();if($own)$this->pdo->commit();return$result;}catch(Throwable$e){if($own&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
}
