<?php
declare(strict_types=1);
use MiniErp\Repositories\FinancialRepository;
$financialTenant=(int)($_SESSION['erp_tenant_id']??0);$financialRepo=new FinancialRepository(Database::getConnection(),$financialTenant);$financialTab=in_array((string)($_GET['financial_tab']??''),['receivable','payable'],true)?(string)$_GET['financial_tab']:(((string)($_GET['financial_type']??''))==='PAYABLE'?'payable':'receivable');$financialType=$financialTab==='payable'?'PAYABLE':'RECEIVABLE';$financialStatus=(string)($_GET['financial_status']??'');$financialAccounts=$financialRepo->accounts($financialType,$financialStatus);$financialSummary=$financialRepo->summary();$financialFlash=$_SESSION['financial_flash']??null;unset($_SESSION['financial_flash']);$fe=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$money=static fn(float$v):string=>'R$ '.number_format($v,2,',','.');
?>
<section class="page-header financial-heading"><div><p class="eyebrow">Gestão financeira</p><h2><?=$financialTab==='receivable'?'Contas a receber':'Contas a pagar'?></h2><p><?=$financialTab==='receivable'?'Recebimentos gerados pelas vendas a prazo e baixas dos clientes.':'Obrigações de entradas a prazo, fornecedores e despesas da empresa.'?></p></div><?php if($financialTab==='payable'):?><button class="btn" type="button" data-financial-expense>+ Nova conta a pagar</button><?php endif?></section>
<?php if($financialFlash):?><p class="message <?=$fe($financialFlash['type'])?>"><?=$fe($financialFlash['message'])?></p><?php endif?>
<div class="financial-kpis"><article class="receivable"><span>A receber</span><strong><?=$money($financialSummary['receivable'])?></strong></article><article class="payable"><span>A pagar</span><strong><?=$money($financialSummary['payable'])?></strong></article><article class="overdue"><span>Em atraso</span><strong><?=$money($financialSummary['overdue'])?></strong></article><article><span>Saldo projetado</span><strong><?=$money($financialSummary['receivable']-$financialSummary['payable'])?></strong></article></div>
<nav class="dashboard-tabs financial-tabs" aria-label="Seções do Financeiro"><a class="<?=$financialTab==='receivable'?'active':''?>" href="?page=financeiro&amp;financial_tab=receivable">Contas a receber</a><a class="<?=$financialTab==='payable'?'active':''?>" href="?page=financeiro&amp;financial_tab=payable">Contas a pagar</a></nav>
<form class="financial-filters"><input type="hidden" name="page" value="financeiro"><input type="hidden" name="financial_tab" value="<?=$fe($financialTab)?>"><label>Status<select name="financial_status"><option value="">Todos</option><option value="OPEN"<?=$financialStatus==='OPEN'?' selected':''?>>Em aberto</option><option value="PARTIAL"<?=$financialStatus==='PARTIAL'?' selected':''?>>Parcial</option><option value="OVERDUE"<?=$financialStatus==='OVERDUE'?' selected':''?>>Em atraso</option><option value="PAID"<?=$financialStatus==='PAID'?' selected':''?>>Quitada</option></select></label><button class="btn" type="submit">Filtrar</button><a class="btn secondary" href="?page=financeiro&amp;financial_tab=<?=$fe($financialTab)?>">Limpar</a></form>
<section class="panel financial-table"><div class="table-wrap"><table><thead><tr><th>Descrição</th><th><?=$financialTab==='receivable'?'Cliente':'Fornecedor / origem'?></th><th>Documento</th><th>Vencimento</th><th>Valor</th><th>Saldo</th><th>Status</th><th>Ação</th></tr></thead><tbody><?php foreach($financialAccounts as$a):$overdue=in_array($a['status'],['OPEN','PARTIAL'],true)&&$a['due_date']<date('Y-m-d');?><tr><td data-label="Descrição"><strong><?=$fe($a['description'])?></strong><small><?=$fe($a['category'])?></small></td><td data-label="<?=$financialTab==='receivable'?'Cliente':'Fornecedor / origem'?>"><?=$fe($a['person_name']?:($financialTab==='payable'?'Despesa interna':'Cliente não informado'))?></td><td data-label="Documento"><?=$fe($a['document_number']?:'—')?></td><td data-label="Vencimento"><?=$fe(date('d/m/Y',strtotime($a['due_date'])))?></td><td data-label="Valor"><?=$money((float)$a['original_amount'])?></td><td data-label="Saldo"><strong><?=$money((float)$a['balance'])?></strong></td><td data-label="Status"><span class="financial-status <?=$overdue?'overdue':strtolower($a['status'])?>"><?=$overdue?'Em atraso':['OPEN'=>'Em aberto','PARTIAL'=>'Parcial','PAID'=>'Quitada'][$a['status']]?></span></td><td data-label="Ação"><?php if($a['status']!=='PAID'):?><button class="btn small secondary" type="button" data-financial-settle data-id="<?=(int)$a['id']?>" data-balance="<?=$fe($a['balance'])?>">Dar baixa</button><?php else:?>—<?php endif?></td></tr><?php endforeach?><?php if(!$financialAccounts):?><tr><td colspan="8">Nenhuma <?=$financialTab==='receivable'?'conta a receber':'conta a pagar'?> encontrada.</td></tr><?php endif?></tbody></table></div></section>
<dialog class="app-modal financial-modal" data-financial-modal><div class="app-modal__surface"><header class="app-modal__header"><h2 data-financial-title>Nova despesa</h2><button type="button" data-financial-close>×</button></header><form action="/financial_action.php" method="post" class="app-modal__body"><input type="hidden" name="csrf_token" value="<?=$fe($_SESSION['erp_financial_csrf'])?>"><input type="hidden" name="return_tab" value="<?=$fe($financialTab)?>"><input type="hidden" name="financial_action" value="expense"><input type="hidden" name="account_id"><div class="financial-form" data-financial-fields></div><footer class="app-modal__footer"><button class="btn secondary" type="button" data-financial-close>Cancelar</button><button class="btn" type="submit">Salvar</button></footer></form></div></dialog>
<template id="financial-expense-fields"><label>Descrição<input name="description" required maxlength="255"></label><label>Categoria<input name="category" maxlength="80" placeholder="Ex.: aluguel, energia"></label><label>Documento<input name="document_number" maxlength="80"></label><label>Vencimento<input type="date" name="due_date" required></label><label>Valor<input type="number" name="amount" min="0.01" step="0.01" required></label><label>Forma prevista<input name="payment_method" maxlength="40"></label><label class="span-2">Observações<textarea name="notes" rows="3" maxlength="500"></textarea></label></template>
<template id="financial-settle-fields"><label>Valor da baixa<input type="number" name="amount" min="0.01" step="0.01" required></label><label>Forma de pagamento<input name="payment_method" maxlength="40"></label><label class="span-2">Observações<textarea name="notes" rows="3" maxlength="500"></textarea></label></template>
<script src="<?=$fe($assetUrl('financial.js'))?>"></script>
