<?php
use MiniErp\Repositories\MasterDataDirectoryRepository;
$directory = new MasterDataDirectoryRepository(Database::getConnection(), (int)($_SESSION['erp_tenant_id'] ?? $_SESSION['tenant_id'] ?? 0));
$mdFilters = ['q' => trim((string)($_GET['q'] ?? '')), 'status' => (string)($_GET['status'] ?? ''), 'type' => (string)($_GET['people_type'] ?? '')];
$mdPage = max(1, (int)($_GET['p'] ?? 1));
$mdPerPage = (int)($_GET['per_page'] ?? 25);
$mdData = match ($tab) {
    'produtos' => $directory->products($mdFilters, $mdPage, $mdPerPage),
    'cfops' => $directory->cfops($mdFilters, $mdPage, $mdPerPage),
    default => $directory->people($mdFilters, $mdPage, $mdPerPage),
};
$h = static fn($value): string => htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
$mdEntity = $tab === 'produtos' ? 'product' : ($tab === 'cfops' ? 'cfop' : 'person');
$mdTitle = $tab === 'produtos' ? 'Produtos' : ($tab === 'cfops' ? 'CFOPs' : 'Pessoas');
$pageUrl = static function (int $page) use ($tab): string {
    $query = array_merge($_GET, ['page' => 'cadastro', 'tab' => $tab, 'p' => $page]);
    return '?' . http_build_query($query);
};
?>
<link rel="stylesheet" href="/assets/master-data.css?v=1">
<section class="md-shell" data-master-data data-entity="<?= $h($mdEntity) ?>" data-csrf="<?= $h($_SESSION['erp_master_data_csrf']) ?>">
  <header class="md-heading"><div><span class="md-eyebrow">Cadastro</span><h2><?= $h($mdTitle) ?></h2><p>Consulte, edite e mantenha os dados operacionais em um só lugar.</p></div><button class="btn primary md-add" type="button">+ Adicionar</button></header>
  <nav class="md-tabs" aria-label="Cadastros"><a class="<?= $tab === 'pessoas' ? 'active' : '' ?>" href="?page=cadastro&tab=pessoas">Pessoas</a><a class="<?= $tab === 'produtos' ? 'active' : '' ?>" href="?page=cadastro&tab=produtos">Produtos</a><a class="<?= $tab === 'cfops' ? 'active' : '' ?>" href="?page=cadastro&tab=cfops">CFOPs</a></nav>
  <div class="md-card">
    <form class="md-filters" method="get"><input type="hidden" name="page" value="cadastro"><input type="hidden" name="tab" value="<?= $h($tab) ?>"><label>Pesquisar<input name="q" value="<?= $h($mdFilters['q']) ?>" placeholder="Nome, documento ou código"></label><?php if ($tab === 'pessoas'): ?><label>Tipo<select name="people_type"><option value="">Todos</option><?php foreach (['cliente'=>'Cliente','fornecedor'=>'Fornecedor','vendedor'=>'Vendedor','motorista'=>'Motorista','transportadora'=>'Transportadora'] as $value=>$label): ?><option value="<?= $value ?>" <?= $mdFilters['type']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><?php endif ?><label>Status<select name="status"><option value="">Todos</option><option value="ativo" <?= $mdFilters['status']==='ativo'?'selected':'' ?>>Ativos</option><option value="inativo" <?= $mdFilters['status']==='inativo'?'selected':'' ?>>Inativos</option></select></label><label>Exibir<select name="per_page"><?php foreach ([10,25,50,100] as $n): ?><option <?= $mdData['per_page']===$n?'selected':'' ?>><?= $n ?></option><?php endforeach ?></select></label><button class="btn secondary" type="submit">Filtrar</button></form>
    <div class="md-table-wrap"><table class="md-table"><thead><tr>
    <?php if ($tab === 'pessoas'): ?><th>Nome / Razão social</th><th>Nome fantasia</th><th>CPF/CNPJ</th><th>Vínculos</th><th>Cidade/UF</th>
    <?php elseif ($tab === 'produtos'): ?><th>Código</th><th>Produto</th><th>NCM</th><th>Unidade</th><th>Preço</th><th>Estoque</th>
    <?php else: ?><th>CFOP</th><th>Descrição</th><th>Natureza</th><th>Aplicação</th><?php endif ?><th>Status</th><th class="md-actions-col">Ações</th></tr></thead><tbody>
    <?php foreach ($mdData['rows'] as $row): $sourceType = $tab==='pessoas' ? (string)$row['source_type'] : ($tab==='produtos'?'produto':'cfop'); ?>
      <tr class="md-row" tabindex="0" data-id="<?= (int)$row['source_id'] ?>" data-type="<?= $h($sourceType) ?>">
      <?php if ($tab === 'pessoas'): ?><td><strong><?= $h($row['legal_name']) ?></strong><small><?= $h($row['email']) ?></small></td><td><?= $h($row['trade_name'] ?: '—') ?></td><td><?= $h($row['document'] ?: '—') ?></td><td class="md-badges"><?php foreach (array_filter(array_unique(explode(',', str_replace(', ', ',', (string)$row['roles'])))) as $role): ?><span><?= $h(ucfirst($role)) ?></span><?php endforeach ?></td><td><?= $h(trim(($row['city'] ?: '—').'/'.($row['state'] ?: '—'), '/')) ?></td>
      <?php elseif ($tab === 'produtos'): ?><td><?= $h($row['codigo'] ?? '') ?></td><td><strong><?= $h($row['nome'] ?? '') ?></strong><small><?= $h($row['categoria'] ?? '') ?></small></td><td><?= $h($row['ncm'] ?? '—') ?></td><td><?= $h($row['unidade'] ?? 'UN') ?></td><td>R$ <?= number_format((float)($row['preco'] ?? 0),2,',','.') ?></td><td><?= $h($row['estoque_atual'] ?? 0) ?></td>
      <?php else: ?><td><strong><?= $h($row['codigo'] ?? '') ?></strong></td><td><?= $h($row['descricao'] ?? '') ?></td><td><?= $h($row['natureza'] ?? '—') ?></td><td><?= $h($row['aplicacao'] ?? '—') ?></td><?php endif ?>
      <td><span class="md-status <?= ($row['status']??'ativo')==='ativo'?'active':'' ?>"><?= $h(ucfirst($row['status'] ?? 'ativo')) ?></span></td><td class="md-row-actions"><button type="button" class="md-edit" title="Editar">✎</button><button type="button" class="md-deactivate" title="Desativar">⊘</button></td></tr>
    <?php endforeach ?><?php if (!$mdData['rows']): ?><tr><td class="md-empty" colspan="9">Nenhum cadastro encontrado com estes filtros.</td></tr><?php endif ?></tbody></table></div>
    <footer class="md-pagination"><span>Mostrando <?= count($mdData['rows']) ?> de <?= $mdData['total'] ?> registros</span><div><?php if ($mdData['page']>1): ?><a href="<?= $h($pageUrl($mdData['page']-1)) ?>">Anterior</a><?php endif ?><b><?= $mdData['page'] ?> / <?= $mdData['pages'] ?></b><?php if ($mdData['page']<$mdData['pages']): ?><a href="<?= $h($pageUrl($mdData['page']+1)) ?>">Próximo</a><?php endif ?></div></footer>
  </div>
  <dialog class="md-modal" aria-labelledby="md-modal-title"><form class="md-form" method="dialog" novalidate><input type="hidden" name="entity" value="<?= $h($mdEntity) ?>"><input type="hidden" name="source_type"><input type="hidden" name="id"><header><div><small>Cadastro / <?= $h($mdTitle) ?></small><h3 id="md-modal-title">Novo cadastro</h3></div><button type="button" class="md-close" aria-label="Fechar">×</button></header><div class="md-alert" hidden></div>
  <?php if ($tab === 'pessoas'): ?>
    <div class="md-form-tabs"><button type="button" class="active" data-pane="general">Geral</button><button type="button" data-pane="address">Endereço</button><button type="button" data-pane="fiscal">Fiscal / Financeiro</button><button type="button" data-pane="contact">Contato</button><button type="button" data-pane="roles">Vínculos</button><button type="button" data-pane="transport">Motorista / Transporte</button></div>
    <div class="md-pane active" data-pane="general"><div class="md-grid"><label>Tipo fiscal<select name="person_type"><option value="PJ">Pessoa jurídica</option><option value="PF">Pessoa física</option><option value="FOREIGN">Estrangeira</option></select></label><label class="span-2">CPF/CNPJ<div class="md-lookup"><input name="cpf_cnpj"><button type="button" class="md-cnpj">Consultar CNPJ</button></div></label><label class="span-2">Nome / Razão social<input name="nome" required></label><label class="span-2">Nome fantasia<input name="nome_fantasia"></label><label>Status<select name="status"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></label></div></div>
    <div class="md-pane" data-pane="address"><div class="md-grid"><label>CEP<input name="cep"></label><label class="span-2">Logradouro<input name="logradouro"></label><label>Número<input name="numero"></label><label>Complemento<input name="complemento"></label><label>Bairro<input name="bairro"></label><label>Município<input name="municipio"></label><label>UF<input name="uf" maxlength="2"></label><label>Código IBGE<input name="codigo_ibge" maxlength="7"></label></div></div>
    <div class="md-pane" data-pane="fiscal"><div class="md-grid"><label>Indicador IE<select name="state_registration_indicator"><option value="9">Não contribuinte</option><option value="1">Contribuinte ICMS</option><option value="2">Isento</option></select></label><label>Inscrição estadual<input name="inscricao_estadual"></label><label>Inscrição municipal<input name="im"></label><label>SUFRAMA<input name="suprama"></label><label>Limite de crédito<input name="limite_credito" type="number" step="0.01"></label><label>Forma de pagamento<input name="forma_pagamento"></label></div></div>
    <div class="md-pane" data-pane="contact"><div class="md-grid"><label class="span-2">E-mail<input name="email" type="email"></label><label>Contato<input name="nome_contato"></label><label>Telefone principal<input name="fone_principal"></label><label>Telefone 2<input name="fone_2"></label><label>Telefone 3<input name="fone_3"></label></div></div>
    <div class="md-pane" data-pane="roles"><div class="md-checks"><label><input type="checkbox" name="tipo_pessoa[]" value="cliente"> Cliente</label><label><input type="checkbox" name="tipo_pessoa[]" value="fornecedor"> Fornecedor</label><label><input type="checkbox" name="tipo_pessoa[]" value="vendedor"> Vendedor</label><label><input type="checkbox" name="tipo_pessoa[]" value="transportadora"> Transportadora</label></div><p class="md-help">Uma pessoa pode desempenhar vários papéis sem duplicar o cadastro.</p></div>
    <div class="md-pane" data-pane="transport"><div class="md-grid"><label>Placa<input name="placa"></label><label>UF da placa<input name="placa_uf"></label><label>ANTT<input name="antt"></label><label>Frete (%)<input name="frete" type="number" step="0.01"></label></div></div>
  <?php elseif ($tab === 'produtos'): ?>
    <div class="md-form-tabs"><button type="button" class="active" data-pane="general">Geral</button><button type="button" data-pane="fiscal">Fiscal</button><button type="button" data-pane="stock">Estoque / Preços</button></div><div class="md-pane active" data-pane="general"><div class="md-grid"><label>Código<input name="codigo" required></label><label class="span-2">Nome<input name="nome" required></label><label>Categoria<input name="categoria"></label><label>Unidade<input name="unidade" value="UN"></label><label>Status<select name="status"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></label></div></div><div class="md-pane" data-pane="fiscal"><div class="md-grid"><label>NCM<input name="ncm" maxlength="8"></label><label>CEST<input name="cest" maxlength="7"></label><label>Origem<input name="merchandise_origin" maxlength="1"></label><label>GTIN<input name="gtin" value="SEM GTIN"></label><label>CFOP padrão<input name="cfop_padrao" maxlength="4"></label><label>Unidade tributável<input name="taxable_unit" value="UN"></label><label>Fator conversão<input name="conversion_factor" value="1"></label></div></div><div class="md-pane" data-pane="stock"><div class="md-grid"><label>Preço de venda<input name="preco" type="number" step="0.01"></label><label>Preço de custo<input name="cost_price" type="number" step="0.01"></label><label>Estoque atual<input name="estoque_atual" type="number" step="0.001"></label><label>Estoque mínimo<input name="minimum_stock" type="number" step="0.001"></label></div></div>
  <?php else: ?>
    <div class="md-pane active"><div class="md-grid"><label>CFOP<input name="codigo" maxlength="4" required></label><label class="span-2">Descrição<input name="descricao" required></label><label>Natureza<input name="natureza"></label><label class="span-2">Aplicação<textarea name="aplicacao" rows="4"></textarea></label><label>Status<select name="status"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></label></div></div>
  <?php endif ?>
  <footer><button type="button" class="btn secondary md-close">Fechar</button><button type="submit" class="btn secondary" data-stay>Salvar</button><button type="submit" class="btn primary">Salvar e fechar</button></footer></form></dialog>
</section><script src="/assets/master-data.js?v=1" defer></script>
